### PR TITLE
test(session-replay): Add deterministic sample rate to fix flakiness

### LINKED ISSUE #5994: Fix flaky SentrySessionReplayIntegrationTests.testBufferReplayIgnoredBecauseSampleRateForCrash
### GitHub action Run Link

https://github.com/getsentry/sentry-cocoa/actions/runs/17261278494?pr=5954

### Disabling PR

none

### Description

`SentrySessionReplayIntegrationTests.testBufferReplayIgnoredBecauseSampleRateForCrash` seems to be flaky

### PR DESCRIPTION
**Pull request by philprime**
## :scroll: Description

This PR fixes a flaky test `testBufferReplayIgnoredBecauseSampleRateForCrash` in the session replay integration tests by adding deterministic random number generation.

- Added `TestRandom(value: 0.5)` to ensure deterministic sample rate checking behavior
- Added detailed inline comments explaining the interaction between current session and previous session sample rates
- Clarified why the test uses `errorSampleRate: 1` for current session but `errorSampleRate: 0` for previous session data

The fix ensures the sample rate check `0.5 >= 0` always evaluates to `true`, making the replay consistently dropped as expected, eliminating the race condition that caused intermittent test failures.

## :bulb: Motivation and Context

The test `testBufferReplayIgnoredBecauseSampleRateForCrash` was experiencing flaky behavior with the error:
```
XCTAssertEqual failed: ("1") is not equal to ("0")
```

The flakiness was probably introduced by #5428 which refactored `SentryGlobalEventProcessor` from a singleton pattern to dependency injection. This architectural change affected how the random number generator was initialized, making the sample rate check non-deterministic.

- The test simulates a crash from a previous session that had `errorSampleRate: 0` (no error replays)
- Sample rate check: `random >= errorSampleRate` where `errorSampleRate = 0`
- With actual random numbers: sometimes `random = 0.0` (test passes), sometimes `random > 0.0` (test fails)
- The fix uses `TestRandom(value: 0.5)` so `0.5 >= 0` is always `true` → replay consistently dropped

The fix ensures the test verifies the correct behavior: **previous session sample rates should be respected for crash replays**, regardless of current session configuration.

Fixes #5994

## :green_heart: How did you test it?

I re-ran the CI tests 3 times and made sure the test didn't fail any time.

## :pencil: Checklist

You have to check all boxes before merging:

- [x] I added tests to verify the changes.
- [X] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [X] I updated the docs if needed.
- [X] I updated the wizard if needed.
- [X] Review from the native team if needed.
- [X] No breaking change or entry added to the changelog.
- [X] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

#skip-changelog

### CODE REVIEW

**Comment by philprime** [comment]
Seems to have failed again in https://github.com/getsentry/sentry-cocoa/actions/runs/17290909540/job/49081277996?pr=6012

**Comment by philprime** [comment]
Ran all unit tests three times, all passed:

- https://github.com/getsentry/sentry-cocoa/actions/runs/17294079755/attempts/1
- https://github.com/getsentry/sentry-cocoa/actions/runs/17294079755/attempts/2
- https://github.com/getsentry/sentry-cocoa/actions/runs/17294079755/attempts/3

File: Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayIntegrationTests.swift [hunk 1]
```diff
@@ -272,24 +272,46 @@ class SentrySessionReplayIntegrationTests: XCTestCase {
...
+        // CRITICAL: Set random value to 1.0 to ensure shouldReplayFullSession(sessionSampleRate) returns false,
+        // preventing the session from starting as a full session. Buffer replay sample rate checks
+        // only apply to non-full sessions. The sample rate check uses: random >= errorSampleRate
+        // With errorSampleRate=0 and random=1.0: 1.0 >= 0 = true → replay dropped
+        SentryDependencyContainer.sharedInstance().random = TestRandom(value: 1.0)
+
+        // Start current session with 0% session sample rate to ensure it's NOT a full session
+        // (shouldReplayFullSession: 1.0 < 0 = false), but 100% error sample rate would normally 
+        // capture all error replays if this were not a buffer replay from previous session
+        startSDK(sessionSampleRate: 0, errorSampleRate: 1)
```
Comment (itaybre) [inline Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayIntegrationTests.swift:286]: Since it is not a full session, any value lower than 1 should work, right?

Comment (philprime) [reply Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayIntegrationTests.swift:286]: No, `0` means to absolutely not start at all. More than `0` enables some the of internals, so any value above `0` will enable the full session mode.
