### PR TITLE
fix: Move SessionTracker file I/O off the main thread

### LINKED ISSUE #5815: Move SessionTracker IO operations to a BG thread
### Description

The `SentrySessionTracker` does a couple of file IO operations on the main thread. Even though they are lightweight, we should consider moving these to a BG thread. We have to ensure that the session tracking logic doesn't end up with race conditions and we have to ensure the logic doesn't break if the app crashes.

It's worth noting that a big customer reported this issue, and we have a [customer case](https://www.notion.so/sentry/Critical-Differences-Sentry-vs-Bugsnag-Session-Tracking-2468b10e4b5d80a1b197ea0d2a9dfbaa) for this.

### PR DESCRIPTION
**Pull request by denrase**
## :bulb: Motivation and Context

Fixes #5815

## :green_heart: How did you test it?

- Existing tests run without issue.
- Tested with sample app (backgrounding + new session after 30s in bg threshold).

## :pencil: Checklist

You have to check all boxes before merging:

- [ ] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: Sources/Swift/Integrations/Session/SessionTracker.swift [hunk 1]
```diff
@@ -106,13 +113,15 @@ final class SessionTracker {
     /// called due to a crash or unexpected behavior. Still, we don't want to lose such sessions and end
     /// them.
     func endCachedSession() {
-        let lastInForeground = SentryDependencyContainerSwiftHelper.readTimestampLastInForeground()
-        if lastInForeground != nil {
-            SentryDependencyContainerSwiftHelper.deleteTimestampLastInForeground()
-        }
+        dispatchQueue.dispatchAsync {
```
Comment (philprime) [inline Sources/Swift/Integrations/Session/SessionTracker.swift:116]: `h`: How is this behaving in case of crashes? Couldn't this lead to cases where the session is not properly ended? I don't have a particular case at hand right now, just a general concern

Comment (denrase) [reply Sources/Swift/Integrations/Session/SessionTracker.swift:116]: If the app crashes before the async block is executed, we pick it up on next launch when endCachedSession is re-tried.

If `willResignActive` fails to write the timestamps async due to a crash, the endCachedSession will be ended as abnormal, this is a slight behaviour change and is documented.
