### PR TITLE
fix: Trying to swizzle a class without a library name

### LINKED ISSUE #1331: Crash in WKWebKit when swizzling
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
@sentry/react-native 3.0.1, which uses version 7.2.6 of this library

### Steps to Reproduce

We have a custom-written in-app browser that uses WKWebView at its base. Since updating to the above versions of the sentry libraries this browser crashes in the following situation:

1. Navigate to https://www.babymarkt.de/
2. Add an item to your shopping cart
3. View shopping cart to begin checkout
4. Tap on the "Gutschein einlösen" button (leave the text field blank)

### Expected Result

The website should show a validation popup, like this:
CleanShot 2021-09-14 at 18 30 48

### Actual Result

The app crashes.

```
Fatal Exception: NSInvalidArgumentException
*** +[NSString stringWithCString:encoding:]: NULL cString
```

I believe this crashes due to the swizzling that takes place at https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryUIViewControllerSwizziling.m#L150.

### Logs

**Fatal Exception: NSInvalidArgumentException
*** +[NSString stringWithCString:encoding:]: NULL cString**
```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x19fa2a708 __exceptionPreprocess
1  libobjc.A.dylib                0x1b45347a8 objc_exception_throw
2  Foundation                     0x1a0ca80d0 +[NSUUID UUID]
3  Sentry                         0x105c7e564 (Missing)
4  Sentry                         0x105c7e4a8 (Missing)
5  Sentry                         0x105c7e05c (Missing)
6  WebCore                        0x1ad1382a0 (Missing)
7  WebKit                         0x1ac1fdb08 WebKit::PageClientImpl::createValidationBubble(WTF::String const&, WebCore::ValidationBubble::Settings const&)
8  WebKit                         0x1ac223edc WebKit::WebPageProxy::showValidationMessage(WebCore::IntRect const&, WTF::String const&)
9  WebKit                         0x1ac492518 WebKit::WebPageProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
10 WebKit                         0x1abe64504 IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&)
11 WebKit                         0x1ac1e3710 WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
12 WebKit                         0x1abe45cf8 IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >)
13 WebKit                         0x1abe455ec IPC::Connection::dispatchIncomingMessages()
14 JavaScriptCore                 0x1a9daa160 WTF::RunLoop::performWork()
15 JavaScriptCore                 0x1a9dab130 WTF::RunLoop::performWork(void*)
16 CoreFoundation                 0x19f9a4990 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
17 CoreFoundation                 0x19f9a488c __CFRunLoopDoSource0
18 CoreFoundation                 0x19f9a3b90 __CFRunLoopDoSources0
19 CoreFoundation                 0x19f99db70 __CFRunLoopRun
20 CoreFoundation                 0x19f99d308 CFRunLoopRunSpecific
21 GraphicsServices               0x1b7020734 GSEventRunModal
22 UIKitCore                      0x1a241b75c -[UIApplication _run]
23 UIKitCore                      0x1a2420fcc UIApplicationMain
24 [redacted]                         0x102708de4 main + 14 (main.m:14)
25 libdyld.dylib                  0x19f659cf8 start
Crashed: com.google.firebase.crashlytics.ios.exception
SIGABRT ABORT 0x00000001cdc15334
```

**Crashed: com.google.firebase.crashlytics.ios.exception**
```
0  FirebaseCrashlytics            0x104950560 FIRCLSProcessRecordAllThreads + 180
1  FirebaseCrashlytics            0x104950944 FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x104949704 FIRCLSHandler + 48
3  FirebaseCrashlytics            0x104943e80 __FIRCLSExceptionRecord_block_invoke + 92
4  libdispatch.dylib              0x19f61781c _dispatch_client_callout + 20
5  libdispatch.dylib              0x19f626910 _dispatch_lane_barrier_sync_invoke_and_complete + 60
6  FirebaseCrashlytics            0x104943618 FIRCLSExceptionRecord + 212
7  FirebaseCrashlytics            0x104943910 FIRCLSExceptionRecordNSException + 536
8  FirebaseCrashlytics            0x1049431f8 FIRCLSTerminateHandler() + 400
9  Sentry                         0x105c45124 CPPExceptionTerminate() + 108
10 libc++abi.dylib                0x1b4614fa0 std::__terminate(void (*)()) + 20
11 libc++abi.dylib                0x1b4617c0c __cxa_get_exception_ptr + 34
12 libc++abi.dylib                0x1b4617bb8 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 138
13 libobjc.A.dylib                0x1b45348d4 objc_exception_throw + 360
14 Foundation                     0x1a0ca80d0 +[NSUUID UUID] + 206
15 Sentry                         0x105c7e564 +[SentryUIViewControllerSwizziling shouldSwizzleViewController:] + 52
16 Sentry                         0x105c7e4a8 +[SentryUIViewControllerSwizziling swizzleViewControllerSubClass:isNib:] + 44
17 Sentry                         0x105c7e05c __62+[SentryUIViewControllerSwizziling swizzleViewControllerInits]_block_invoke_2.81 + 108
18 WebCore                        0x1ad1382a0 WebCore::ValidationBubble::ValidationBubble(UIView*, WTF::String const&, WebCore::ValidationBubble::Settings const&) + 120
19 WebKit                         0x1ac1fdb08 WebKit::PageClientImpl::createValidationBubble(WTF::String const&, WebCore::ValidationBubble::Settings const&) + 76
20 WebKit                         0x1ac223edc WebKit::WebPageProxy::showValidationMessage(WebCore::IntRect const&, WTF::String const&) + 156
21 WebKit                         0x1ac492518 WebKit::WebPageProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) + 10832
22 WebKit                         0x1abe64504 IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&) + 124
23 WebKit                         0x1ac1e3710 WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) + 40
24 WebKit                         0x1abe45cf8 IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >) + 656
25 WebKit                         0x1abe455ec IPC::Connection::dispatchIncomingMessages() + 460
26 JavaScriptCore                 0x1a9daa160 WTF::RunLoop::performWork() + 484
27 JavaScriptCore                 0x1a9dab130 WTF::RunLoop::performWork(void*) + 36
28 CoreFoundation                 0x19f9a4990 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
29 CoreFoundation                 0x19f9a488c __CFRunLoopDoSource0 + 208
30 CoreFoundation                 0x19f9a3b90 __CFRunLoopDoSources0 + 268
31 CoreFoundation                 0x19f99db70 __CFRunLoopRun + 820
32 CoreFoundation                 0x19f99d308 CFRunLoopRunSpecific + 600
33 GraphicsServices               0x1b7020734 GSEventRunModal + 164
34 UIKitCore                      0x1a241b75c -[UIApplication _run] + 1072
35 UIKitCore                      0x1a2420fcc UIApplicationMain + 168
36 [redacted]                         0x102708de4 main + 14 (main.m:14)
37 libdyld.dylib                  0x19f659cf8 start + 4
```

### PR DESCRIPTION
**Pull request by brustolin**
## :scroll: Description

Fixed a bug trying to get the image name from a class that does not have one.

## :bulb: Motivation and Context

Fixes #1331 

## :green_heart: How did you test it?

Unit test

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [ ] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

File: Sources/Sentry/SentryUIViewControllerSwizziling.m [hunk 1]
```diff
@@ -145,10 +145,14 @@ + (void)swizzleViewControllerSubClass:(Class)class isNib:(BOOL)isNib
  */
 + (BOOL)shouldSwizzleViewController:(Class)class
 {
+    // Some apple classes does not return an imageName
```
Comment (marandaneto) [inline Sources/Sentry/SentryUIViewControllerSwizziling.m:148]:
```suggestion
    // Some apple classes do not return an imageName
```

File: Sources/Sentry/SentryUIViewControllerSwizziling.m [hunk 2]
```diff
@@ -145,10 +145,14 @@ + (void)swizzleViewControllerSubClass:(Class)class isNib:(BOOL)isNib
...
+    const char *imageName = class_getImageName(class);
```
Comment (marandaneto) [inline Sources/Sentry/SentryUIViewControllerSwizziling.m:149]: can we add a test for such a use case? so we avoid regression

**Review by marandaneto — APPROVED** [review]
