### PR TITLE
fix: Don't create transactions for HTTP Requests

### LINKED ISSUE #1216: Don't create a transaction for HTTP spans
When creating spans for HTTP requests, the SDK shouldn't create a transaction if there is none active. This means the SDK discards HTTP spans if there is not an active transaction.

### PR DESCRIPTION
**Pull request by brustolin**
## :scroll: Description

Prevent SentryNetworkTracker from creating a transaction if there is no active transaction in SentryPerformanceTracker.

## :bulb: Motivation and Context

There should not be standalone transactions for HTTP requests 

Fix #1216 

## :green_heart: How did you test it?

Unit tests

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

**Comment by brustolin** [comment]
Right now, SentryNetworkTracker only works with SentryUIPerformanceTracker.
What if there is no UI Tracking happening but there is a span in the scope? 
Should we automatically track any request happening while there is a user span in the scope?

**Comment by philipphofmann** [comment]
> Right now, SentryNetworkTracker only works with SentryUIPerformanceTracker.
> What if there is no UI Tracking happening but there is a span in the scope?
> Should we automatically track any request happening while there is a user span in the scope?

Yes, I think if there is a span on the scope and `autoPerformanceTracking` is enabled we should add the HTTP span. Can you confirm this @bruno-garcia?

**Comment by brustolin** [comment]
> Yes, I think if there is a span on the scope and `autoPerformanceTracking` is enabled we should add the HTTP span. At least we do that [on Android](https://github.com/getsentry/sentry-java/blob/1f704cb3e630cb753ce0ac3390b6da5377c9e6ea/sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt#L26-L36). Can you confirm this @bruno-garcia?

So that's raise the question: if there is a UI transaction going on, but it is not in the scope because the user has attached something in the scope first. Which one should we use to create the request span, the UI transaction or the one in the scope?

If we take Android in consideration, since they use only the scope to manage performance tracking, this request span should be added to the one in the scope.

**Comment by bruno-garcia** [comment]
I believe we should add the http span created as a child of whatever transaction is bound to the scope (and not any of its spans).

**Comment by philipphofmann** [comment]
> I believe we should add the http span created as a child of whatever transaction is bound to the scope (and not any of its spans).

I agreee. I think this makes sense. We can start with that because it's simple and we can do more complex stuff later.

File: Sources/Sentry/SentryNetworkTracker.m [hunk 1]
```diff
@@ -101,34 +111,37 @@ - (void)observeValueForKeyPath:(NSString *)keyPath
...
+
+    NSInteger responseStatusCode = [self urlResponseStatusCode:sessionTask.response];
+
+    if (responseStatusCode != -1) {
+        [netSpan setDataValue:[NSNumber numberWithInteger:responseStatusCode]
+                       forKey:@"http.status_code"];
+    }
+
+    [netSpan finishWithStatus:[self statusForSessionTask:sessionTask]];
+    [sessionTask removeObserver:self forKeyPath:NSStringFromSelector(@selector(state))];
```
Comment (philipphofmann) [inline Sources/Sentry/SentryNetworkTracker.m:143]: `m`: I think we should also remove the observer if there is no `netSpan`, which means we should do this directly before checking if the `netSpan` is nil.

File: Sources/Sentry/SentryNetworkTracker.m [hunk 2]
```diff
@@ -101,34 +111,37 @@ - (void)observeValueForKeyPath:(NSString *)keyPath
...
-                                forKey:@"http.status_code"];
-                }
-
-                [self.tracker finishSpan:spanId withStatus:[self statusForSessionTask:sessionTask]];
-                [sessionTask removeObserver:self forKeyPath:NSStringFromSelector(@selector(state))];
-                [SentryLog logWithMessage:@"Finished HTTP span for sessionTask"
-                                 andLevel:kSentryLevelDebug];
-            }
-        }
+    if (![keyPath isEqualToString:NSStringFromSelector(@selector(state))]) {
```
Comment (philipphofmann) [inline Sources/Sentry/SentryNetworkTracker.m:114]: `m`: I changed the structure here a bit [to use guard clauses to reduce nesting](https://www.refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html). This reveals that we don't have tests for the return statements here. Can we please add some tests to get the coverage up to 100%.

File: Sources/Sentry/SentryPerformanceTracker.m [hunk 3]
```diff
@@ -135,7 +135,9 @@ - (void)finishSpan:(SentrySpanId *)spanId withStatus:(SentrySpanStatus)status
         [self.spans removeObjectForKey:spanId];
     }
 
-    [spanTracker finishWithStatus:status];
+    @synchronized(self.activeStack) {
+        [spanTracker finishWithStatus:status];
+    }
```
Comment (philipphofmann) [inline Sources/Sentry/SentryPerformanceTracker.m:140]: `l`: Why this change?

**Review by philipphofmann — COMMENTED** [review]
Thanks, we should add a few more tests and then we are ready to merge.

File: Sources/Sentry/SentryNetworkTracker.m (hunk 1 above)
Comment (brustolin) [reply Sources/Sentry/SentryNetworkTracker.m:143]: We had this before but was giving a race condition error in some tests bruno did.
We have no way to check if sessionTask has the observer before we try to remove it.

File: Sources/Sentry/SentryPerformanceTracker.m (hunk 3 above)
Comment (brustolin) [reply Sources/Sentry/SentryPerformanceTracker.m:140]: To avoid a race condition where we could be adding a child to a span being finished.

File: Sources/Sentry/SentryNetworkTracker.m (hunk 1 above)
Comment (philipphofmann) [reply Sources/Sentry/SentryNetworkTracker.m:143]: So we can only remove the observer if there is a `netSpan`? If so, I think we should add this as a comment.

**Review by philipphofmann — COMMENTED** [review]
Just one more open comment. Thanks for adding the tests.

**Review by philipphofmann — APPROVED** [review]
LGTM, let's address the comment about the removal of the observer somewhere else.
