### PR TITLE
fix: Redistributable static libraries should never be built with module debugging enabled

### LINKED ISSUE #3788: Xcode Warning: Redistributable static libraries should never be built with module debugging enabled
### Platform

iOS, macOS

### Environment

Production, TestFlight

### Installed

Swift Package Manager

### Version

8.22.4

### Did it work on previous versions?

8.21.0

### Steps to Reproduce

Xcode 15.3
integrate static lib via spm

### Expected Result

Expect no warnings

### Actual Result

/Users/runner/work/sentry-cocoa/sentry-cocoa/Carthage/DerivedData/ModuleCache.noindex/B94P7YC5KI7O/Foundation-1EXJ537PQIF6H.pcm: No such file or directory

Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.

image

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by brustolin**
## :scroll: Description

Removed symbol generation from Static framework.
Debug symbols will be generated by the project using our static framework.

## :bulb: Motivation and Context

close #3788

### CODE REVIEW

File: scripts/build-xcframework.sh [hunk 1]
```diff
@@ -45,8 +50,8 @@ generate_xcframework() {
     done
     
     #Create framework for mac catalyst
-    xcodebuild -project Sentry.xcodeproj/ -scheme "$scheme" -configuration Release -sdk macosx -destination 'platform=macOS,variant=Mac Catalyst' -derivedDataPath ./Carthage/DerivedData CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES MACH_O_TYPE=$MACH_O_TYPE SUPPORTS_MACCATALYST=YES ENABLE_CODE_COVERAGE=NO
-    
+    xcodebuild -project Sentry.xcodeproj/ -scheme "$scheme" -configuration Release -sdk iphoneos -destination 'platform=macOS,variant=Mac Catalyst' -derivedDataPath ./Carthage/DerivedData CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES MACH_O_TYPE=$MACH_O_TYPE SUPPORTS_MACCATALYST=YES ENABLE_CODE_COVERAGE=NO GCC_GENERATE_DEBUGGING_SYMBOLS="$GCC_GENERATE_DEBUGGING_SYMBOLS"
```
Comment (kahest) [inline scripts/build-xcframework.sh:53]:
```suggestion
    xcodebuild -project Sentry.xcodeproj/ -scheme "$scheme" -configuration Release -sdk macosx -destination 'platform=macOS,variant=Mac Catalyst' -derivedDataPath ./Carthage/DerivedData CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES MACH_O_TYPE=$MACH_O_TYPE SUPPORTS_MACCATALYST=YES ENABLE_CODE_COVERAGE=NO GCC_GENERATE_DEBUGGING_SYMBOLS="$GCC_GENERATE_DEBUGGING_SYMBOLS"
```

Comment (brustolin) [reply scripts/build-xcframework.sh:53]: Yes, it is. Some UIKit libs dont exist in the macOS SDK, but catalyst should work with iOS sdk.

File: CHANGELOG.md [hunk 2]
```diff
@@ -9,6 +9,7 @@
 ### Fixes
 
 - Don't run onCrashedLastSession for nil Events (#3785)
+- Redistributable static libraries should never be built with module debugging enabled (#3800)
```
Comment (philipphofmann) [inline CHANGELOG.md:12]: PR number 3800 🥇

File: scripts/build-xcframework.sh [hunk 3]
```diff
@@ -13,14 +13,19 @@ generate_xcframework() {
     local scheme="$1"
     local sufix="${2:-}"
     local MACH_O_TYPE="${3-mh_dylib}"
-    
     local createxcframework="xcodebuild -create-xcframework "
+    local GCC_GENERATE_DEBUGGING_SYMBOLS="YES"
+    
+    if [ "$MACH_O_TYPE" = "staticlib" ]; then
+        #For static framework we disabled everything related to symbols
```
Comment (philipphofmann) [inline scripts/build-xcframework.sh:20]: `l`: Please elaborate a bit on why we do that.

**Review by philipphofmann — APPROVED** [review]
LGTM, thanks @brustolin 👍

File: scripts/build-xcframework.sh (hunk 3 above)
Comment (brustolin) [reply scripts/build-xcframework.sh:20]:
```suggestion
        #For static framework we should disabled symbols because they are not distributed in the framework causing warnings.
```
