### PR TITLE
fix: Add masking for PDFView

### LINKED ISSUE #5120: Analyze and improve masking of PDFView
### Description

[This replay](https://kula-app.sentry.io/issues/6543454730/?project=5966520) is showing an unmasked PDF rendering. We need to analyze if this is expected or unexpected, because PDF documents can hold PII.

### PR DESCRIPTION
**Pull request by philprime**
## :scroll: Description

Adds `PDFKit.PDFView` to the default list of redacted views.

## :bulb: Motivation and Context

Fixes #5120

## :green_heart: How did you test it?

- Added a new screen in the iOS-Swift Sample App under **Extras > PDF View**.
- Reproduced the issue in [this session replay](https://sentry-sdks.sentry.io/explore/replays/d7772640448d4c74b26640a50921cb27/?project=5428557&query=&referrer=%2Fexplore%2Freplays%2F%3AreplaySlug%2F&statsPeriod=1h&yAxis=count%28%29&t=10), then checked the fixed version [here](https://sentry-sdks.sentry.io/explore/replays/8af806efaa7648d2bff97345eaf8cdc7/?project=5428557&query=&referrer=%2Fexplore%2Freplays%2F%3AreplaySlug%2F&statsPeriod=1h&yAxis=count%28%29&t=5).
- Added unit tests

## :pencil: Checklist

You have to check all boxes before merging:

- [X] I added tests to verify the changes.
- [X] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [X] I updated the docs if needed → https://github.com/getsentry/sentry-docs/pull/14510
- [X] I updated the wizard if needed.
- [X] Review from the native team if needed.
- [X] No breaking change or entry added to the changelog.
- [X] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: Samples/iOS-Swift/iOS-Swift/ViewControllers/SentryPDFViewController.swift [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+        pdfView.translatesAutoresizingMaskIntoConstraints = false
+        NSLayoutConstraint.activate([
+            pdfView.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor),
+            pdfView.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor),
+            pdfView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
+            pdfView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor)
+        ])
+
+        // Load a PDF document
```
Comment (philippsuess) [inline Samples/iOS-Swift/iOS-Swift/ViewControllers/SentryPDFViewController.swift]: `l`: A bit redundant. 
```suggestion
```

File: Samples/iOS-Swift/iOS-Swift/ViewControllers/SentryPDFViewController.swift [hunk 2]
```diff
@@ -0,0 +1,26 @@
+import PDFKit
+
+class SentryPDFViewController: UIViewController {
+    override func viewDidLoad() {
+        super.viewDidLoad()
+
+        // Set up the PDF view and add it to the view hierarchy
```
Comment (philippsuess) [inline Samples/iOS-Swift/iOS-Swift/ViewControllers/SentryPDFViewController.swift]: `l`: Not really needed
```suggestion
```
