### PR TITLE
fix: Update raw_description in runtime context for Mac Catalyst App

### LINKED ISSUE #7083: fix: Update raw_description in runtime context for Mac Catalyst App
> [!NOTE]
> The pull request "[fix: Update raw_description in runtime context for Mac Catalyst App](https://github.com/getsentry/sentry-cocoa/pull/7082)" was created by @philprime but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

Updated the runtime context's raw_description value from "raw_description" to "mac-catalyst-app" in SentryCrashWrapper. Adjusted corresponding tests to reflect this change.

### PR DESCRIPTION
**Pull request by philprime**
Updated the runtime context's raw_description value from "raw_description" to "mac-catalyst-app" in SentryCrashWrapper. Adjusted corresponding tests to reflect this change.

Closes #7083

### CODE REVIEW

File: Sources/Swift/SentryCrash/SentryCrashWrapper.swift [hunk 1]
```diff
@@ -210,7 +210,7 @@ public final class SentryCrashWrapper: NSObject {
 
             if self.processInfoWrapper.isMacCatalystApp {
                 runtimeContext["name"] = "Mac Catalyst App"
-                runtimeContext["raw_description"] = "raw_description"
+                runtimeContext["raw_description"] = "mac-catalyst-app"
```
Comment (itaybre) [inline Sources/Swift/SentryCrash/SentryCrashWrapper.swift:213]: 👏 nice find
