### PR TITLE
fix: SentryHub not checking spanContext sampled value

### LINKED ISSUE #1314: SentryOptions tracesSampleRate not work.
### Environment

How do you use Sentry?
self-hosted.

Which SDK and version?
sentry-cocoa: 'Sentry', '7.1.3'

### Steps to Reproduce

Define your transactions and set tracesSampleRate to 0.01.

### Expected Result

Upload sampled transactions.

### Actual Result

Upload all transactions.

### PR DESCRIPTION
**Pull request by brustolin**
## :scroll: Description

Fixed SentryHub to check the spanContext `sampled` value.

## :bulb: Motivation and Context
 Every span capture should respect tracesSampleRate 

Fixes #1314 

## :green_heart: How did you test it?

Unit tests

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [ ] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

File: Samples/iOS-Swift/iOS-Swift/AppDelegate.swift [hunk 1]
```diff
@@ -19,7 +19,7 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
             }
             options.debug = true
             // Sampling 100% - In Production you probably want to adjust this
-            options.tracesSampleRate = 1.0
+            options.tracesSampleRate = 0.001
```
Comment (marandaneto) [inline Samples/iOS-Swift/iOS-Swift/AppDelegate.swift:22]:
```suggestion
            options.tracesSampleRate = 1.0
```

for testing 0.001 makes sense but for debugging its always easier with 1.0

**Review by marandaneto — APPROVED** [review]
thanks @brustolin

**Review by HazAT — APPROVED** [review]
