### PR TITLE
fix: Create span for loadView

### LINKED ISSUE #1278: UIViewControllers with Nib files are missing loadView spans
### Environment

Sentry-Cocoa 7.2.2

### Steps to Reproduce

Open Sentry iOS-Swift sample app, click on the Show Nib button.

### Expected Result

The transaction should contain a span for `loadView`.

### Actual Result

The transaction misses the loadView span.

### PR DESCRIPTION
**Pull request by brustolin**
## :scroll: Description

Since we fix a problem with ViewControllers and NIbs, we don't create spans for `loadView` methods in ViewController performance tracker if the class does not have its own `loadView` implementation.

## :bulb: Motivation and Context

We want the entire ui life cycle inside the transaction.

Closes #1278

## :green_heart: How did you test it?

UI tests and Unit tests

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes 
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

File: Sources/Sentry/SentryUIViewControllerSwizzling.m [hunk 1]
```diff
@@ -222,6 +224,24 @@ - (void)swizzleRootViewControllerAndDescendant:(UIViewController *)rootViewContr
     }
 }
 
+/**
+ * We need to swizzle UIViewController 'loadView'
+ * because we can`t do it for controllers that use Nib files.
```
Comment (philipphofmann) [inline Sources/Sentry/SentryUIViewControllerSwizzling.m:229]: `m`: Can we please add the info on why we can't do that. We can grab the info from https://github.com/getsentry/sentry-cocoa/pull/1277

> When using an UIViewController with a nib, UIKit only loads the nib if the loadView method
is not overridden. Our swizzling confused the UIKit, and therefore, it didn't load the nib
leading to an empty view and then to a crash.

Or we just add see `swizzleLoadView`, because there the code docs explain it.

File: Sources/Sentry/SentryInAppLogic.m [hunk 2]
```diff
@@ -43,6 +44,16 @@ - (BOOL)isInApp:(nullable NSString *)imageName
     return NO;
 }
 
+- (BOOL)isClassInApp:(Class)targetClass
```
Comment (philipphofmann) [inline Sources/Sentry/SentryInAppLogic.m:47]: It totally makes sense to put that in here 👏

File: Sources/Sentry/SentryUIViewControllerSwizzling.m [hunk 3]
```diff
@@ -222,6 +224,24 @@ - (void)swizzleRootViewControllerAndDescendant:(UIViewController *)rootViewContr
...
+ * But because of a protection in SentryUIViewControllerPerformanceTracker
+ * we don`t get two spans for those ViewController that have their loadView swizzled.
```
Comment (philipphofmann) [inline Sources/Sentry/SentryUIViewControllerSwizzling.m:231]: `l`: Maybe a bit clearer:
```suggestion
 * SentryUIViewControllerPerformanceTracker makes sure we don't get two spans
 * if the loadView of an actual UIViewController is swizzled.
```

File: Sources/Sentry/SentryUIViewControllerPerformanceTracker.m [hunk 4]
```diff
@@ -38,6 +45,13 @@ - (instancetype)init
 - (void)viewControllerLoadView:(UIViewController *)controller
               callbackToOrigin:(void (^)(void))callbackToOrigin
 {
+    // Since this will be executed for every ViewController,
+    // we should not create transactions for classes that should no be swizzled.
+    if (![self.inAppLogic isClassInApp:[controller class]]) {
```
Comment (philipphofmann) [inline Sources/Sentry/SentryUIViewControllerPerformanceTracker.m:50]: `m`: Can we please add a test for that in `SentryUIViewControllerPerformanceTrackerTests`?

**Review by philipphofmann — COMMENTED** [review]
A few comments, but almost LGTM

File: CHANGELOG.md [hunk 5]
```diff
@@ -3,6 +3,7 @@
 ## 7.5.4
 
 - fix: Sending OOM when SDK is closed (#1487)
+- fix: Create span for loadView (#1495)
```
[the remark this answers is not in the document]
Comment (brustolin) [reply CHANGELOG.md:6]: 😕 The bot sabotaged me.

On it.

File: Sources/Sentry/SentryUIViewControllerPerformanceTracker.m (hunk 4 above)
Comment (brustolin) [reply Sources/Sentry/SentryUIViewControllerPerformanceTracker.m:50]: > A few comments, but almost LGTM. Can you also please test with the sample app?

I have a PR only focused on UI tests that Im just waiting to have the loadView spans to finish. 
Maybe I could commit that PR in this one and we review this later. What do you think?

**Comment by brustolin** [comment]
> A few comments, but almost LGTM. Can you also please test with the sample app?

I have a PR focused only on UI tests that is just waiting for `loadView` spans to be included in the transaction.
Maybe I could commit that PR on this one and then we review this one later. What do you think?

**Comment by philipphofmann** [comment]
> > A few comments, but almost LGTM. Can you also please test with the sample app?
> 
> I have a PR focused only on UI tests that is just waiting for `loadView` spans to be included in the transaction. Maybe I could commit that PR on this one and then we review this one later. What do you think?

Which PR is that?

**Comment by brustolin** [comment]
> Which PR is that?

https://github.com/getsentry/sentry-cocoa/pull/1484

**Review by philipphofmann — APPROVED** [review]
LGTM 🚀

**Comment by philipphofmann** [comment]
I disabled the `testSplitView` on iOS 10 so we can merge this and fix the test later: https://github.com/getsentry/sentry-cocoa/issues/1514
