### PR TITLE
ci: fix thread sanitizer job

### LINKED ISSUE #3200: Fix Thread Sanitizer
### Description

raised by @vaind:

> [TSAN] hasn't been running [on `main`] because it failed after a build due to malformed command. After fixing the call, the sanitizer fails. I suggest disabling the thread sanitizer step in CI for now and fixing its errors in a separate maintenance issue. See latest log: [getsentry/sentry-cocoa/suites/14737489895/artifacts/837486751](https://github.com/getsentry/sentry-cocoa/suites/14737489895/artifacts/837486751)

see https://github.com/getsentry/sentry-cocoa/pull/3197

### PR DESCRIPTION
**Pull request by armcknight**
fixes #3200 and #3069

Fixed the races that were detected locally. Here are the outputs from each: 
[data race in ANR tracker.txt](https://github.com/getsentry/sentry-cocoa/files/12969522/data.race.in.ANR.tracker.txt)
[data race in SentryNetworkTracker.isCaptureFailedRequestsEnabled.txt](https://github.com/getsentry/sentry-cocoa/files/12969523/data.race.in.SentryNetworkTracker.isCaptureFailedRequestsEnabled.txt)
[data race in SentrySpan.isFinished.txt](https://github.com/getsentry/sentry-cocoa/files/12969524/data.race.in.SentrySpan.isFinished.txt)
[data race in SentryThreadInspectorTests.txt](https://github.com/getsentry/sentry-cocoa/files/12969525/data.race.in.SentryThreadInspectorTests.txt)
[data race in TestThread (1).txt](https://github.com/getsentry/sentry-cocoa/files/12969526/data.race.in.TestThread.1.txt)
[data race in TestThread (2).txt](https://github.com/getsentry/sentry-cocoa/files/12969527/data.race.in.TestThread.2.txt)
data race in binaryImageAdded
data race in SentryFileManager currentFileCounter

# TODO

- [ ] i just discovered the [suppressions](https://github.com/getsentry/sentry-cocoa/blame/98cca71ab965606c68f46b2f6a0a9c710ce6cdb2/Tests/ThreadSanitizer.sup) file listing some skipped tests. Let's work on trying to fix those in a subsequent PR.

#skip-changelog

### CODE REVIEW

**Comment by armcknight** [comment]
Current status: "unexpected exit, crash, or test timeout" when run under TSAN in the following test cases
- `SentryNSDataTrackerTests.testWriteAtomically_CheckTransaction_FilterOut_nonProcessFrames`
- `SentryANRTrackerTests.testAppSuspended_NoANR`
- `SentryANRTrackerTests.testMultipleListeners`
- `-[SentryCrashBinaryImageCacheTests testAddBinaryImageInParallel]`
- `SentryFileManagerTests.testDefaultMaxEnvelopesConcurrent`

The message appears after a TSAN data race warning in each of them, along with this message (not sure if it's a red herring): `xctest(8596,0x10ef62280) malloc: nano zone abandoned due to inability to reserve vm space.`

**Comment by armcknight** [comment]
Right now I'm thinking we can merge this, and after merging main into #3290 et al, see if any of those failures resolve, then we can skip the remaining ones and open subsequent issues to investigate/fix them. What do you think @brustolin ?

**Comment by armcknight** [comment]
I changed https://github.com/getsentry/sentry-cocoa/pull/3290 to merge into this branch and reran all the unit tests against it, so let's see if any ANRTracker-based tsan warnings pop up there.

**Comment by philipphofmann** [comment]
The Thread Sanitizer CI job is still failing. @armcknight, what's the state of the PR?

**Comment by armcknight** [comment]
As of the latest run in CI, it doesn't produce any TSAN warnings, but is again taking long enough to time out the job :/ 

Looking at the logs, I still see the following failures:
- SentryTests.SentryFramesTrackerTests testFrameRateChange
- SentryTests.SentryNetworkTrackerIntegrationTests testCustomURLProtocol_BlocksAllRequests
- SentryTests.SentryNetworkTrackerIntegrationTests testGetCaptureFailedRequestsEnabled
- SentryTests.SentryNetworkTrackerIntegrationTests testGetRequest_CompareSentryTraceHeader
- SentryTests.SentryNetworkTrackerIntegrationTests testGetRequest_SpanCreatedAndBaggageHeaderAdded

**Comment by armcknight** [comment]
I've got it narrowed down to one failing test, `testStartOnTheMainThread`. Added more logging to see what's up.

File: Sources/Sentry/SentryDependencyContainer.m [hunk 1]
```diff
@@ -60,6 +60,12 @@ + (instancetype)sharedInstance
 
 + (void)reset
 {
+#if !TARGET_OS_WATCH
```
Comment (philipphofmann) [inline Sources/Sentry/SentryDependencyContainer.m:63]: I think this could solve some flaky reachability tests. IMO, this should be in an extra PR, so we can merge it right away. I don't want to steal your credit, so I leave it up to you if you want to open a PR or not. Otherwise, I can do it.

File: Sources/Sentry/SentrySDK.m [hunk 2]
```diff
@@ -137,24 +137,29 @@ + (void)setStartInvocations:(NSUInteger)value
 
 + (void)startWithOptions:(SentryOptions *)options
 {
+    [SentryLog configure:options.debug diagnosticLevel:options.diagnosticLevel];
+
     // We accept the tradeoff that the SDK might not be fully initialized directly after
     // initializing it on a background thread because scheduling the init synchronously on the main
     // thread could lead to deadlocks.
```
Comment (philipphofmann) [inline Sources/Sentry/SentrySDK.m:144]: `m`: I think that comment should stay directly above `[SentryThreadWrapper onMainThread:^{`

File: Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift [hunk 3]
```diff
@@ -70,48 +75,61 @@ class SentryStacktraceBuilderTests: XCTestCase {
...
         let waitForAsyncToRun = expectation(description: "Wait async functions")
         Task {
+            print("\(Date()) [Sentry] [TEST] running async task...")
             let filteredFrames = await self.firstFrame()
             waitForAsyncToRun.fulfill()
             XCTAssertGreaterThanOrEqual(filteredFrames, 3, "The Stacktrace must include the async callers.")
         }
-        wait(for: [waitForAsyncToRun], timeout: 1)
+
+        wait(for: [waitForAsyncToRun], timeout: 10)
```
Comment (philipphofmann) [inline Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift:97]: `m`: Increasing this to 10 looks a bit scary cause it can slow down our test suite. What made you increase this value?

File: Sources/Sentry/SentryDependencyContainer.m (hunk 1 above)
Comment (armcknight) [reply Sources/Sentry/SentryDependencyContainer.m:63]: Yep, that's exactly what it was for. In general I did plan to split up some of the fixes in here... I've just been trying to plow through anything that could possibly be causing problems in the TSAN tests for now. Easier to test the combinations together, then split them apart for discussion/historical purposes afterwards!

File: Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift (hunk 3 above)
Comment (armcknight) [reply Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift:97]: looking at the test logs, I saw it taking 5-6 seconds between the log statements that define the boundary completing the async task. no idea why though 🙁

**Comment by armcknight** [comment]
So, this finally got a green result on the tsan job, but I'm sure it's going to be really flaky moving forward. I think we could probably merge these changes, although I'm going to separate out some unrelated changes first. 

If it continues to cause problems, we should consider making TSAN jobs non-failable,, and instead only report TSAN warnings and test failures as comments/annotations on PRs instead. WDYT @philipphofmann ?

File: Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift (hunk 3 above)
Comment (armcknight) [reply Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift:97]: we can either special case it for tsan only, or skip these completely, but that seems unwise given what they're supposed to test.

File: Sources/Sentry/SentryDependencyContainer.m (hunk 1 above)
Comment (armcknight) [reply Sources/Sentry/SentryDependencyContainer.m]: See https://github.com/getsentry/sentry-cocoa/pull/3356

File: Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift (hunk 3 above)
Comment (philipphofmann) [reply Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift:97]: Maybe tsan doesn't work well with `backtrace_async`. I would rather special case them for tsan.

**Comment by armcknight** [comment]
> I don't think making them non-failable is a good idea cause I fear that we are going to ignore them if they are flaky. It could be a first step though, so your efforts here are not lost, if you think getting them stable is hard to achieve.

It's either that or we decide to throw them out, which seems unwise. It was finding actual issues. And, as I noted above, someone has been skipping tests anyways, as there is a suppression file with some test cases listed to skip.

It's a matter of how much effort we're willing to put into getting them stable and keeping them there.

I think it'll have better signal to noise ratio if it visibly comments on PRs that there is a warning on a given line of code, vs just a failing CI job that requires us to navigate through GitHub's clunky UI for checks and rerun it over and over again. Because what I'm seeing now are mostly flaky test failures, not failures specifically due to TSAN warnings like the text files I attached to this PR description.

I think that's better in any case because even if it fails, it's still a pain to track down what the TSAN failure actually was in said clunky UI, it's like 7-8 clicks. It'd be much better to have it bubble up in a comment where it's immediately visible.

File: scripts/tests-with-thread-sanitizer.sh [hunk 4]
```diff
@@ -1,11 +1,13 @@
...
 # When enableThreadSanitizer is enabled and ThreadSanitizer finds an issue,
 # the logs only show failing tests, but don't highlight the threading issues.
-# Therefore we print a hint to find the threading issues.
-env NSUnbufferedIO=YES xcodebuild -workspace Sentry.xcworkspace -scheme Sentry -configuration Test -enableThreadSanitizer YES \
-    -destination "platform=iOS Simulator,OS=14.4,name=iPhone 11" \
+# Therefore we print a hint to find the threading issues. Profiler doesn't
+# run when it detects TSAN is present, so we skip those tests.
+env NSUnbufferedIO=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO xcodebuild -workspace Sentry.xcworkspace -scheme Sentry -configuration Test -enableThreadSanitizer YES \
+    -destination "platform=iOS Simulator,OS=latest,name=iPhone 14" \
+    -skip-testing:"SentryProfilerTests" \
```
[the remark this answers is not in the document]
Comment (armcknight) [reply scripts/tests-with-thread-sanitizer.sh:10]: I already added that in the comment above, please check a few lines up.

[the remark this answers is not in the document]
Comment (philipphofmann) [reply scripts/tests-with-thread-sanitizer.sh:10]: Ups sorry, my bad 🤦

File: Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift [hunk 5]
```diff
@@ -75,48 +75,72 @@ class SentryStacktraceBuilderTests: XCTestCase {
...
+            print("\(Date()) [Sentry] [TEST] running async task...")
             let filteredFrames = await self.firstFrame()
             waitForAsyncToRun.fulfill()
             XCTAssertGreaterThanOrEqual(filteredFrames, 1, "The Stacktrace must have only one function.")
         }
-        wait(for: [waitForAsyncToRun], timeout: 1)
+        
+        // observed the async task taking a long time to finish if TSAN is attached
+        var timeout = 1
+        if threadSanitizerIsPresent() {
```
Comment (philipphofmann) [inline Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift:126]: Nice 👍

**Review by philipphofmann — COMMENTED** [review]
Then, let's go with GH comments and see how it goes 👍

**Review by philipphofmann — APPROVED** [review]
LGTM, when CI is green and TSAN is non-failable.

**Comment by armcknight** [comment]
Issue to track work for reporting TSAN warnings to PRs: https://github.com/getsentry/sentry-cocoa/issues/3358

**Comment by armcknight** [comment]
One of the UI tests started failing with no obviously related code changes. Still investigating.

**Comment by philipphofmann** [comment]
@armcknight, that is most likely because of https://github.com/getsentry/sentry-cocoa/pull/3372. Merging main back into your branch should solve the problem.
