### PR TITLE
fix(ui-tests): Fix duplicate accessibility identifiers and camera crashes

### LINKED ISSUE #6139: fix(ui-tests): Fix duplicate accessibility identifiers
> [!NOTE]
> The pull request "[fix(ui-tests): Fix duplicate accessibility identifiers](https://github.com/getsentry/sentry-cocoa/pull/6138)" was created by @philprime but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

The UI tests started to fail because the view accessibility identifier was duplicated, so the UI tests found more than one element and failed because they didn't know which one to use.

- Changed accessbility identifiers of "Show Camera UI"
- Add waiting for crash delay to view lifecycle tests

#skip-changelog

### PR DESCRIPTION
**Pull request by philprime**
The UI tests started to fail because the view accessibility identifier was duplicated, so the UI tests found more than one element and failed because they didn't know which one to use.

- Changed accessbility identifiers of "Show Camera UI"
- Add waiting for crash delay to view lifecycle tests

#skip-changelog

Closes #6139

### CODE REVIEW

File: Samples/iOS-Swift/iOS-Swift-UITests/ViewLifecycleUITests.swift [hunk 1]
```diff
@@ -30,6 +30,9 @@ class ViewLifecycleUITests: BaseUITest {
         app.buttons["view-lifecycle-test"].tap()
         app.buttons["dismiss-with-load-view"].tap()
 
+        // Wait a bit to ensure that any asynchronous operations have time to complete.
+        delay(seconds: 5)
```
Comment (philippsuess) [inline Samples/iOS-Swift/iOS-Swift-UITests/ViewLifecycleUITests.swift]: `m`: It's not clear to my why we need the delay now for the other tests as well. That seems a bit odd to me.

**Comment by philprime** [comment]
Unexpectedly the UI tests were failing because the app was crashing due this error:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Source type 1 not available'
terminating due to uncaught exception of type NSException
CoreSimulator 1048 - Device: iPhone 16 Pro (646D9594-719F-4611-8D7D-B9EF29AE6D7E) - Runtime: i0S 18.6 (22G86) - DeviceType: iPhone 16 Pro
```

This is the stracktrace, originating the error back to the displaying of the `UIImagePickerController:

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 7F686C39-61FA-43E1-8D16-B28A7F89B23E
CrashReporter Key:   1A558A11-DCA3-AF31-B70F-83D514B91A8E
Hardware Model:      VirtualMac2,1
Process:             iOS-Swift [36627]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/B52AA6A4-4D11-4FAA-8AD1-B7DAA02BB330/data/Containers/Bundle/Application/AD9F722C-16C4-4B9F-BD2F-4450CCA7B989/iOS-Swift.app/iOS-Swift
Identifier:          io.sentry.sample.iOS-Swift
Version:             8.56.0 (1)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [12690]
Coalition:           com.apple.CoreSimulator.SimDevice.B52AA6A4-4D11-4FAA-8AD1-B7DAA02BB330 [2826]
Responsible Process: SimulatorTrampoline [3350]

Date/Time:           2025-09-11 13:12:50.6072 +0000
Launch Time:         2025-09-11 13:12:42.3353 +0000
OS Version:          macOS 15.5 (24F74)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: iOS-Swift [36627]

Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	       0x1804f39dc __exceptionPreprocess + 160
1   libobjc.A.dylib               	       0x18009c084 objc_exception_throw + 72
2   UIKitCore                     	       0x1859cb7b4 -[UIImagePickerController sourceType] + 0
3   iOS-Swift.debug.dylib         	       0x10541081c ExtraViewController.showCameraUIAction(_:) + 116 (ExtraViewController.swift:418)
4   iOS-Swift.debug.dylib         	       0x105410908 @objc ExtraViewController.showCameraUIAction(_:) + 76
...
```

It seems that **iOS simulators running on macOS devices without a built-in camera, e.g. a Mac Mini, can not display an `UIImagePickerController` with the `sourceType` set to `camera`**. To be honest this is unexpected, because the camera doesn't work in the simulator anyways.

This means that the`SessionReplayUITests.testCameraUI_shouldNotCrashOnIOS26()` **can not run on CI**. As we still want this test to run locally I kept it in and added a conditional `XCTSkip` instead.
