### PR TITLE
test: convert some test code from crashable to failable

### LINKED ISSUE #3576: Remove force unwraps from test code
### Description

We have numerous force-unwraps in our Swift test code, which make it harder to iterate locally if you make a breaking change. This causes the test process to crash if an assumption is broken, disallowing the complete suite of tests to run, preventing you from seeing the total list of tests that would fail. This could mean many cycles of fixing one breakage, run the suite again, encounter the next crash. Of course, it's more painful if it happens in CI (and is harder to see what's going on there, too).

Convert such force unwraps to either `guard...else { XCTFail("message"); return }` or `try XCTUnwrap(...)`

### PR DESCRIPTION
**Pull request by armcknight**
Helps fix #3576 

I hit one of these today so just went through and removed some easy ones. There are still almost 603 uses of the force unwrap operator and 154 unchecked array indexes in the test code after these changes.

image
image

#skip-changelog

### CODE REVIEW

File: Tests/SentryProfilerTests/SentryTraceProfilerTests.swift [hunk 1]
```diff
@@ -428,9 +428,9 @@ private extension SentryTraceProfilerTests {
         }
     }
 
-    func printTimestamps(entries: [[String: Any]]) -> [NSString] {
-        entries.reduce(into: [NSString](), { partialResult, entry in
-            partialResult.append(entry["elapsed_since_start_ns"] as! NSString)
+    func printTimestamps(entries: [[String: Any]]) throws -> [NSString] {
+        try entries.reduce(into: [NSString](), { partialResult, entry in
+            partialResult.append(try XCTUnwrap(entry["elapsed_since_start_ns"] as? NSString))
```
Comment (brustolin) [inline Tests/SentryProfilerTests/SentryTraceProfilerTests.swift:433]: Does this really need to throw? Or you add it to add it just to comply with XCTUnwrap?

Can we use this?
```Swift
    func printTimestamps(entries: [[String: Any]]) -> [String] {
        return entries.compactMap { $0["elapsed_since_start_ns"] as? String }
    }
```

**Review by brustolin — APPROVED** [review]
Thanks. We should keep using this approach, it makes safer tests.

File: Tests/SentryProfilerTests/SentryTraceProfilerTests.swift (hunk 1 above)
Comment (armcknight) [reply Tests/SentryProfilerTests/SentryTraceProfilerTests.swift:433]: oh good point, i like that. then an xctunwrap will work on the result later 👍🏻
