### PR TITLE
fix: Cleanup issues from SentryCrashIntegration conversion to Swift

### LINKED ISSUE #7232: fix: Cleanup issues from SentryCrashIntegration conversion to Swift
> [!NOTE]
> The pull request "[fix: Cleanup issues from SentryCrashIntegration conversion to Swift](https://github.com/getsentry/sentry-cocoa/pull/7231)" was created by @itaybre but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

## :scroll: Description

Looks like some things were missing since the migration:
- Cleanup old conditions on SentryBaseIntegration.m
- Fix for flaky test: disable CrashIntegration installation on CreashInstallationReporter Tests
  - Having 2 installation reporters caused issues, since now the SDK creates a new one on each SDK start, the flakiness became more noticeable.
 

## :pencil: Checklist

You have to check all boxes before merging:

- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

#skip-changelog

### PR DESCRIPTION
**Pull request by itaybre**
## :scroll: Description

Looks like some things were missing since the migration:
- Cleanup old conditions on SentryBaseIntegration.m
- Fix for flaky test: disable CrashIntegration installation on CreashInstallationReporter Tests
  - Having 2 installation reporters caused issues, since now the SDK creates a new one on each SDK start, the flakiness became more noticeable.
 

## :pencil: Checklist

You have to check all boxes before merging:

- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

#skip-changelog

Closes #7232

### CODE REVIEW

File: Tests/SentryTests/SentryCrash/SentryCrashInstallationReporterTests.swift [hunk 1]
```diff
@@ -50,37 +50,39 @@ class SentryCrashInstallationReporterTests: XCTestCase {
...
-        
+
         XCTAssertEqual(self.testClient.captureFatalEventInvocations.count, 0)
         XCTAssertEqual(sentrycrash_getReportCount(), 0)
     }
     
     private func givenSutWithStartedSDK() {
         let options = Options()
         options.dsn = TestConstants.dsnAsString(username: "SentryCrashInstallationReporterTests")
+        // Disable crash handler so only
```
Comment (philippsuess) [inline Tests/SentryTests/SentryCrash/SentryCrashInstallationReporterTests.swift:84]: `l`: @itaybre I think this comment misses some text, please follow up with another PR.

**Review by philipphofmann — APPROVED** [review]
LGTM, thanks.
