### PR TITLE
fix: Add warning to addBreadcrumb when used before SDK init

### LINKED ISSUE #4015: Calling `addBreadcrumb` triggers `Main Thread Checker` warning
### Platform

iOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.26.0

### Xcode Version

15.2

### Did it work on previous versions?

not sure

### Steps to Reproduce

Call `SentrySDK.addBreadcrumb()` from a background thread

### Expected Result

No main thread checker issue is found.

### Result
Xcode shows a Main Thread checker warning. The SDK is calling UIKit methods that require Main Thread execution on a background thread.

### Logs and screenshots

```
Main Thread Checker: UI API called on a background thread: -[UIWindow screen]
PID: 45981, TID: 2549765, Thread name: (none), Queue name: com.apple.root.user-initiated-qos.cooperative, QoS: 25
```

Screenshot 2024-05-24 at 13 03 51
Screenshot 2024-05-24 at 13 03 42

### Question
I checked the iOS documentation and it does not mention that breadcrumb should be added from the main thread.
Is it an issue from Sentry SDK that needs to be addressed or does it actually recommended to call that method from the main thread ?

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by philprime**
## :scroll: Description

- Adds a fatal error log when using `SentrySDK.addBreadcrumb(_:)` before the SDK is ready.
- Adds null unwrapping to silence warnings in handled cases.

## :bulb: Motivation and Context

See this comment: https://github.com/getsentry/sentry-cocoa/issues/4015#issuecomment-3254127281

Fixes #4015 

## :green_heart: How did you test it?

Used `SentrySDK.addBreadcrumb(_:)` in an sample app before `SentrySDK.init` was called and could see this log line:

```
[Sentry] [fatal] [1757061012.9625359] [SentrySDKInternal:511] The SDK is disabled, so addBreadcrumb doesn't work. Please ensure to start the SDK before adding breadcrumbs.
```

## :pencil: Checklist

You have to check all boxes before merging:

- [X] I added tests to verify the changes.
- [X] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [X] I updated the docs if needed.
- [X] I updated the wizard if needed.
- [X] Review from the native team if needed.
- [X] No breaking change or entry added to the changelog.
- [X] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: Sources/Sentry/SentrySDKInternal.m [hunk 1]
```diff
@@ -500,6 +500,17 @@ + (SentryFeedbackAPI *)feedback
 
 + (void)addBreadcrumb:(SentryBreadcrumb *)crumb
 {
+    if (![SentrySDKInternal isEnabled]) {
```
Comment (philippsuess) [inline Sources/Sentry/SentrySDKInternal.m:503]: `m`: We should be able to add a unit test for this, if I'm not mistaken. Would be useful to avoid regressions.

File: Tests/SentryTests/SentrySDKInternalTests.swift [hunk 2]
```diff
@@ -303,6 +305,51 @@ class SentrySDKInternalTests: XCTestCase {
         XCTAssertEqual(0, logOutput.loggedMessages.count, "Expected no log messages, but got \(logOutput.loggedMessages.count)")
     }
 
+    func testAddBreadcrumbBeforeStartingSDK_LogsFatalMessage() throws {
```
Comment (philippsuess) [inline Tests/SentryTests/SentrySDKInternalTests.swift:306]: Thanks a lot @philprime 💯
