### PR TITLE
fix(session-replay): Fix conversion of frame rate to time interval

### LINKED ISSUE #6624: fix(session-replay): Fix conversion of frame rate to time interval
> [!NOTE]
> The pull request "[fix(session-replay): Fix conversion of frame rate to time interval](https://github.com/getsentry/sentry-cocoa/pull/6623)" was created by @philprime but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

When using `@_spi(Private) import Sentry` it is possible to set a higher frame rate using `options.sessionReplay.frameRate = 10`.

Due to a `UInt / UInt` this will result in a time interval since last frame of `0 ms` instead of e.g. `100ms`. 

This PR fixes the division.

No changelog needed because `frameRate` is internal.

#skip-changelog

### PR DESCRIPTION
**Pull request by philprime**
When using `@_spi(Private) import Sentry` it is possible to set a higher frame rate using `options.sessionReplay.frameRate = 10`.

Due to a `UInt / UInt` this will result in a time interval since last frame of `0 ms` instead of e.g. `100ms`. 

This PR fixes the division.

No changelog needed because `frameRate` is internal.

#skip-changelog

Closes #6624

### CODE REVIEW

File: Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift [hunk 1]
```diff
@@ -233,7 +233,7 @@ import UIKit
             return
         }
 
-        if now.timeIntervalSince(lastScreenShot) >= Double(1 / replayOptions.frameRate) {
+        if now.timeIntervalSince(lastScreenShot) >= 1.0 / Double(replayOptions.frameRate) {
```
Comment (philippsuess) [inline Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift:236]: `m`: The impact of this bug was critical, if I'm not mistaken. IMO, we should add a test to prevent the rounding error from happening again.

**Review by philipphofmann — APPROVED** [review]
> No changelog needed because frameRate is internal.

If I'm not mistaken, this fixes a critical bug. I think this PR is worth a changelog entry.

File: Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift (hunk 1 above)
Comment (philprime) [reply Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift:236]: Even if it never applied to any user? I can add one in the "internal" section

Comment (philippsuess) [reply Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift:236]: Sorry, I thought this fixed a critical bug. If not, then don't add a changelog entry.
