### PR TITLE
fix: resolve missing_docs SwiftLint violations

### LINKED ISSUE #7175: docs: Add linter to require public API documentation
### Description

SwiftLint or swift-format should have a rule to require public APIs to be well-documented. 

- Research options to enforce linting
- Enforce linting rule in CI
- Fix linting

### LINKED ISSUE #7184: fix: resolve missing_docs SwiftLint violations
> [!NOTE]
> The pull request "[fix: resolve missing_docs SwiftLint violations](https://github.com/getsentry/sentry-cocoa/pull/7183)" was created by @philprime but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

## Summary
- Add documentation or swiftlint disable comments to resolve all `missing_docs` violations across the Swift codebase
- For truly public API types, proper Swift documentation was added (e.g., `SentryTransactionNameSource`, `SentryRedactOptions`, `SentryRedactRegionType`)
- For `@_spi(Private) public` types that are only exposed for hybrid SDKs, `swiftlint:disable missing_docs` comments were used

## Test plan
- [x] Run `make lint 2>&1 | grep missing_docs` - no violations
- [ ] CI passes

#skip-changelog

### PR DESCRIPTION
**Pull request by philprime**
## Summary
- Add documentation or swiftlint disable comments to resolve all `missing_docs` violations across the Swift codebase
- For truly public API types, proper Swift documentation was added (e.g., `SentryTransactionNameSource`, `SentryRedactOptions`, `SentryRedactRegionType`)
- For `@_spi(Private) public` types that are only exposed for hybrid SDKs, `swiftlint:disable missing_docs` comments were used

## Test plan
- [x] Run `make lint 2>&1 | grep missing_docs` - no violations
- [ ] CI passes

#skip-changelog

Closes #7184
Closes #7175

### CODE REVIEW

File: Samples/SentrySampleShared/SentrySampleShared/AssertView.swift [hunk 1]
```diff
@@ -6,6 +7,7 @@ import UIKit
 
 public class AssertView: UIView {
     var span: Span?
+    /// nodoc
```
Comment (philprime) [inline Samples/SentrySampleShared/SentrySampleShared/AssertView.swift]:
```suggestion
```

File: Samples/SentrySampleShared/SentrySampleShared/DSNStorage.swift [hunk 2]
```diff
@@ -1,10 +1,12 @@
+// swiftlint:disable missing_docs
 import Foundation
 import Sentry
 
 /**
  * Stores the DSN to a file in the cache directory.
  */
 public class DSNStorage {
+    /// nodoc
```
Comment (philprime) [inline Samples/SentrySampleShared/SentrySampleShared/DSNStorage.swift]:
```suggestion
```

File: Samples/SentrySampleShared/SentrySampleShared/DSNStorage.swift [hunk 3]
```diff
@@ -15,11 +17,13 @@ public class DSNStorage {
         dsnFile = cachesDirectory.appendingPathComponent("dsn")
     }
 
+    /// nodoc
```
Comment (philprime) [inline Samples/SentrySampleShared/SentrySampleShared/DSNStorage.swift]:
```suggestion
```

File: Samples/SentrySampleShared/SentrySampleShared/DSNStorage.swift [hunk 4]
```diff
@@ -15,11 +17,13 @@ public class DSNStorage {
...
     public func saveDSN(dsn: String) throws {
         try deleteDSN()
         try dsn.write(to: dsnFile, atomically: true, encoding: .utf8)
     }
 
+    /// nodoc
```
Comment (philprime) [inline Samples/SentrySampleShared/SentrySampleShared/DSNStorage.swift]:
```suggestion
```

File: Samples/SentrySampleShared/SentrySampleShared/DSNStorage.swift [hunk 5]
```diff
@@ -30,10 +34,12 @@ public class DSNStorage {
         return try String(contentsOfFile: dsnFile.path)
     }
 
+    /// nodoc
```
Comment (philprime) [inline Samples/SentrySampleShared/SentrySampleShared/DSNStorage.swift]:
```suggestion
```

File: Samples/SentrySampleShared/SentrySampleShared/FeaturesViewController.swift [hunk 6]
```diff
@@ -1,10 +1,13 @@
+// swiftlint:disable missing_docs
 #if !os(macOS) && !os(tvOS) && !os(watchOS) && !os(visionOS)
 
 import UIKit
 
+/// nodoc
```
Comment (philprime) [inline Samples/SentrySampleShared/SentrySampleShared/FeaturesViewController.swift]:
```suggestion
```

File: Samples/SentrySampleShared/SentrySampleShared/FeaturesViewController.swift [hunk 7]
```diff
@@ -1,10 +1,13 @@
...
 public class FeaturesViewController: UIViewController {
     let tableView = UITableView(frame: .zero, style: .plain)
 
+    /// nodoc
```
Comment (philprime) [inline Samples/SentrySampleShared/SentrySampleShared/FeaturesViewController.swift]:
```suggestion
```

File: Samples/SentrySampleShared/SentrySampleShared/SentrySDKWrapper.swift [hunk 8]
```diff
@@ -1,15 +1,18 @@
...
 import UIKit
 #endif // !os(macOS)
 
+/// nodoc
 public struct SentrySDKWrapper {
+    /// nodoc
     public static let shared = SentrySDKWrapper()
 
 #if !os(macOS) && !os(tvOS) && !os(watchOS)
+    /// nodoc
```
Comment (philprime) [inline Samples/SentrySampleShared/SentrySampleShared/SentrySDKWrapper.swift]:
```suggestion
public struct SentrySDKWrapper {
    public static let shared = SentrySDKWrapper()

#if !os(macOS) && !os(tvOS) && !os(watchOS)
```

File: Samples/SentrySampleShared/SentrySampleShared/SentrySDKWrapper.swift [hunk 9]
```diff
@@ -20,6 +23,7 @@ public struct SentrySDKWrapper {
     }()
 #endif // !os(macOS) && !os(tvOS)  && !os(watchOS)
 
+    /// nodoc
```
Comment (philprime) [inline Samples/SentrySampleShared/SentrySampleShared/SentrySDKWrapper.swift]:
```suggestion
```

File: Sentry.xcodeproj/project.pbxproj [hunk 10]
```diff
@@ -5776,6 +5777,27 @@
 		};
 /* End PBXResourcesBuildPhase section */
 
+/* Begin PBXShellScriptBuildPhase section */
```
Comment (philprime) [inline Sentry.xcodeproj/project.pbxproj:5848]: This is a proposition to run SwiftLint on SDK build so we can see violations in Xcode. It adds a small overhead to the build experience, so I am open to not include it.

File: Sources/Swift/Helper/SentrySDK.swift [hunk 11]
```diff
@@ -255,6 +255,9 @@ import Foundation
     }
     
     #if os(iOS) && !SENTRY_NO_UIKIT
+    /// The API for capturing user feedback.
```
Comment (philprime) [inline Sources/Swift/Helper/SentrySDK.swift:307]: This is a minimal documentation and could probably be more elaborate. I would refrain from doing that right now, as the user feedback feature is quite incomplete.

File: Sources/Swift/Integrations/UserFeedback/SentryFeedbackAPI.swift [hunk 12]
```diff
@@ -1,3 +1,4 @@
+// swiftlint:disable missing_docs
```
Comment (philprime) [inline Sources/Swift/Integrations/UserFeedback/SentryFeedbackAPI.swift]: This file should be documented
```suggestion
```

File: Sources/Swift/Integrations/UserFeedback/SentryFeedbackAPI.swift [hunk 13]
```diff
@@ -26,3 +27,4 @@ public final class SentryFeedbackAPI: NSObject {
     }
 }
 #endif
+// swiftlint:enable missing_docs
```
Comment (philprime) [inline Sources/Swift/Integrations/UserFeedback/SentryFeedbackAPI.swift]:
```suggestion
```

File: Sources/Swift/Integrations/UserFeedback/SentryFeedbackAPI.swift [hunk 14]
```diff
@@ -1,3 +1,4 @@
+// swiftlint:disable missing_docs
 @_implementationOnly import _SentryPrivate
 
 #if os(iOS) && !SENTRY_NO_UIKIT
```
Comment (philprime) [inline Sources/Swift/Integrations/UserFeedback/SentryFeedbackAPI.swift:3]:
```suggestion
#if os(iOS) && !SENTRY_NO_UIKIT
/// API for interacting with the feature User Feedback
```

File: Sources/Swift/Options.swift [hunk 15]
```diff
@@ -1,4 +1,4 @@
-// swiftlint:disable file_length
+// swiftlint:disable file_length missing_docs
```
Comment (philprime) [inline Sources/Swift/Options.swift]: Clearly public

```suggestion
// swiftlint:disable file_length
```

File: Sources/Swift/Options.swift [hunk 16]
```diff
@@ -636,4 +636,4 @@ extension NSNumber {
     }
 }
 
-// swiftlint:enable file_length
+// swiftlint:enable file_length missing_docs
```
Comment (philprime) [inline Sources/Swift/Options.swift]:
```suggestion
// swiftlint:enable file_length
```

File: Sources/Swift/Protocol/SentryAttributeValue.swift [hunk 17]
```diff
@@ -1,3 +1,4 @@
+// swiftlint:disable missing_docs
```
Comment (philprime) [inline Sources/Swift/Protocol/SentryAttributeValue.swift]: Also public
```suggestion
```

File: Sources/Swift/Protocol/SentryAttributeValue.swift [hunk 18]
```diff
@@ -231,3 +232,4 @@ extension Array: SentryAttributeValue {
         return .stringArray(mappedStringValues)
     }   
 }
+// swiftlint:enable missing_docs
```
Comment (philprime) [inline Sources/Swift/Protocol/SentryAttributeValue.swift]:
```suggestion
```

File: Sources/Swift/Protocol/SentryLog.swift [hunk 19]
```diff
@@ -1,3 +1,4 @@
+// swiftlint:disable missing_docs
```
Comment (philprime) [inline Sources/Swift/Protocol/SentryLog.swift]: Also public
```suggestion
```

File: Sources/Swift/Protocol/SentryLog.swift [hunk 20]
```diff
@@ -108,3 +109,4 @@ public final class SentryLog: NSObject {
         try container.encodeIfPresent(severityNumber?.intValue, forKey: .severityNumber)
     }
 }
+// swiftlint:enable missing_docs
```
Comment (philprime) [inline Sources/Swift/Protocol/SentryLog.swift]:
```suggestion
```

File: Sources/Swift/Protocol/SentryLogLevel.swift [hunk 21]
```diff
@@ -1,3 +1,4 @@
+// swiftlint:disable missing_docs
```
Comment (philprime) [inline Sources/Swift/Protocol/SentryLogLevel.swift]: Also public

```suggestion
```

File: Sources/Swift/Protocol/SentryLogLevel.swift [hunk 22]
```diff
@@ -100,3 +101,4 @@ extension SentryLog {
         }
     }
 }
+// swiftlint:enable missing_docs
```
Comment (philprime) [inline Sources/Swift/Protocol/SentryLogLevel.swift]:
```suggestion
```

File: Sources/Swift/SentryClient.swift [hunk 23]
```diff
@@ -1,3 +1,4 @@
+// swiftlint:disable missing_docs
```
Comment (philprime) [inline Sources/Swift/SentryClient.swift]:
```suggestion
```

File: Sources/Swift/SentryClient.swift [hunk 24]
```diff
@@ -130,3 +131,4 @@ import Foundation
     }
     
 }
+// swiftlint:enable missing_docs
```
Comment (philprime) [inline Sources/Swift/SentryClient.swift]:
```suggestion
```

File: Sources/Swift/SentryDsn.swift [hunk 25]
```diff
@@ -1,3 +1,4 @@
+// swiftlint:disable missing_docs
```
Comment (philprime) [inline Sources/Swift/SentryDsn.swift]:
```suggestion
```

File: Sources/Swift/SentryDsn.swift [hunk 26]
```diff
@@ -198,3 +199,4 @@ public final class SentryDsn: NSObject {
         }
     }
 }
+// swiftlint:enable missing_docs
```
Comment (philprime) [inline Sources/Swift/SentryDsn.swift]:
```suggestion
```

File: Sources/Swift/SentryExperimentalOptions.swift [hunk 27]
```diff
@@ -1,3 +1,4 @@
+// swiftlint:disable missing_docs
```
Comment (philprime) [inline Sources/Swift/SentryExperimentalOptions.swift]:
```suggestion
```

File: Sources/Swift/SentryExperimentalOptions.swift [hunk 28]
```diff
@@ -32,3 +33,4 @@ public final class SentryExperimentalOptions: NSObject {
     @_spi(Private) public func validateOptions(_ options: [String: Any]?) {
     }
 }
+// swiftlint:enable missing_docs
```
Comment (philprime) [inline Sources/Swift/SentryExperimentalOptions.swift]:
```suggestion
```

File: Sources/Swift/SentryHub.swift [hunk 29]
```diff
@@ -1,3 +1,4 @@
+// swiftlint:disable missing_docs
```
Comment (philprime) [inline Sources/Swift/SentryHub.swift]:
```suggestion
```

File: Sources/Swift/SentryHub.swift [hunk 30]
```diff
@@ -249,3 +250,4 @@ import Foundation
     }
     #endif
 }
+// swiftlint:enable missing_docs
```
Comment (philprime) [inline Sources/Swift/SentryHub.swift]:
```suggestion
```

File: Sources/Swift/Tools/SentryLogger.swift [hunk 31]
```diff
@@ -1,3 +1,4 @@
+// swiftlint:disable missing_docs
```
Comment (philprime) [inline Sources/Swift/Tools/SentryLogger.swift]:
```suggestion
```

File: Sources/Swift/Tools/SentryLogger.swift [hunk 32]
```diff
@@ -200,3 +201,4 @@ public final class SentryLogger: NSObject {
         delegate.capture(log: log)
     }
 }
+// swiftlint:enable missing_docs
```
Comment (philprime) [inline Sources/Swift/Tools/SentryLogger.swift]:
```suggestion
```

File: Tests/SentryProfilerTests/SentryAppStartProfilingConfigurationTests.swift [hunk 33]
```diff
@@ -55,9 +56,11 @@ private extension SentryAppStartProfilingConfigurationTests {
 
         let actualIsValid = sentry_willProfileNextLaunch(actualOptions)
         if shouldProfileLaunch {
-            XCTAssert(actualIsValid, "Expected to enable app launch profiling with options:\n\(expectedOptions.description)")
+            XCTAssert(actualIsValid, "Expected to enable app launch profiling with options:
+\(expectedOptions.description)")
```
Comment (philprime) [inline Tests/SentryProfilerTests/SentryAppStartProfilingConfigurationTests.swift]:
```suggestion
            XCTAssert(actualIsValid, "Expected to enable app launch profiling with options:\n\(expectedOptions.description)")
```

File: Tests/SentryProfilerTests/SentryAppStartProfilingConfigurationTests.swift [hunk 34]
```diff
@@ -55,9 +56,11 @@ private extension SentryAppStartProfilingConfigurationTests {
...
         } else {
-            XCTAssertFalse(actualIsValid, "Expected to disable app launch profiling with options:\n\(expectedOptions.description)")
+            XCTAssertFalse(actualIsValid, "Expected to disable app launch profiling with options:
+\(expectedOptions.description)")
```
Comment (philprime) [inline Tests/SentryProfilerTests/SentryAppStartProfilingConfigurationTests.swift]:
```suggestion
            XCTAssertFalse(actualIsValid, "Expected to disable app launch profiling with options:\(expectedOptions.description)")
```

File: Tests/SentryProfilerTests/SentryAppStartProfilingConfigurationTests.swift [hunk 35]
```diff
@@ -124,9 +127,12 @@ struct LaunchProfileOptions: Equatable {
...
     var description: String {
-        return "LaunchProfileOptions(\n"
-        + "\ttracesSampleRate: \(String(describing: tracesSampleRate)),\n"
-        + "\tcontinuousProfileV2Options: \(String(describing: continuousProfileV2Options))\n"
+        return "LaunchProfileOptions(
+"
+        + "	tracesSampleRate: \(String(describing: tracesSampleRate)),
+"
+        + "	continuousProfileV2Options: \(String(describing: continuousProfileV2Options))
+"
```
Comment (philprime) [inline Tests/SentryProfilerTests/SentryAppStartProfilingConfigurationTests.swift]:
```suggestion
        return "LaunchProfileOptions(\n"
        + "\ttracesSampleRate: \(String(describing: tracesSampleRate)),\n"
        + "\tcontinuousProfileV2Options: \(String(describing: continuousProfileV2Options))\n"
```

File: Tests/SentryProfilerTests/SentryAppStartProfilingConfigurationTests.swift [hunk 36]
```diff
@@ -146,12 +152,17 @@ extension SentryProfileOptions.SentryProfileLifecycle {
...
-        + "\t)"
+        return "ContinuousProfileV2Options(
+"
+        + "		lifecycle: \(lifecycle.description),
+"
+        + "		sessionSampleRate: \(sessionSampleRate),
+"
+        + "		profileAppStarts: \(profileAppStarts)
+"
+        + "	)"
```
Comment (philprime) [inline Tests/SentryProfilerTests/SentryAppStartProfilingConfigurationTests.swift]:
```suggestion
        return "ContinuousProfileV2Options(\n"
        + "\t\tlifecycle: \(lifecycle.description),\n"
        + "\t\tsessionSampleRate: \(sessionSampleRate),\n"
        + "\t\tprofileAppStarts: \(profileAppStarts)\n"
        + "\t)"
```

File: Sources/Swift/Protocol/SentryLogMessage.swift [hunk 37]
```diff
@@ -1,3 +1,4 @@
+// swiftlint:disable missing_docs
```
Comment (philprime) [inline Sources/Swift/Protocol/SentryLogMessage.swift]:
```suggestion
```

File: Sources/Swift/Protocol/SentryLogMessage.swift [hunk 38]
```diff
@@ -105,3 +106,4 @@ public struct SentryLogMessage: ExpressibleByStringInterpolation {
         }
     }
 }
+// swiftlint:enable missing_docs
```
Comment (philprime) [inline Sources/Swift/Protocol/SentryLogMessage.swift]:
```suggestion
```

File: Tests/SentryProfilerTests/SentryAppStartProfilingConfigurationTests.swift [hunk 39]
```diff
@@ -57,7 +58,7 @@ private extension SentryAppStartProfilingConfigurationTests {
         if shouldProfileLaunch {
             XCTAssert(actualIsValid, "Expected to enable app launch profiling with options:\n\(expectedOptions.description)")
         } else {
-            XCTAssertFalse(actualIsValid, "Expected to disable app launch profiling with options:\n\(expectedOptions.description)")
+            XCTAssertFalse(actualIsValid, "Expected to disable app launch profiling with options:\(expectedOptions.description)")
```
Comment (philprime) [inline Tests/SentryProfilerTests/SentryAppStartProfilingConfigurationTests.swift]:
```suggestion
            XCTAssertFalse(actualIsValid, "Expected to disable app launch profiling with options:\n\(expectedOptions.description)")
```

**Comment by philprime** [comment]
Sorry for the spam, this should have been a draft PR first

File: Samples/SentrySampleShared/SentrySampleShared/DSNDisplayViewController.swift [hunk 40]
```diff
@@ -1,3 +1,4 @@
+// swiftlint:disable missing_docs
```
Comment (philippsuess) [inline Samples/SentrySampleShared/SentrySampleShared/DSNDisplayViewController.swift]: I would rather add a .swiftlint config file to the samples folder and disable missing_docs completely. We already have specific rules for tests as well here https://github.com/getsentry/sentry-cocoa/blob/main/Tests/.swiftlint.yml

File: SentryTestUtils/Sources/Dynamic/Dynamic.swift [hunk 41]
```diff
@@ -4,6 +4,8 @@
 //  Created by Mhd Hejazi on 4/15/20.
 //  Copyright © 2020 Samabox. All rights reserved.
 //
+
+// swiftlint:disable missing_docs
```
Comment (philippsuess) [inline SentryTestUtils/Sources/Dynamic/Dynamic.swift]: `m`: I would rater disable this rule altogether in this TestUtilsFolder similar to what we do https://github.com/getsentry/sentry-cocoa/blob/main/Tests/.swiftlint.yml

File: .swiftlint.yml [hunk 42]
```diff
@@ -100,3 +101,11 @@ type_name:
     error: 60
 large_tuple:
   - 3
+
+missing_docs:
```
Comment (philippsuess) [inline .swiftlint.yml:105]: `m`: I think it would be better to only enable this rule in the Sources/ folder

**Review by philipphofmann — APPROVED** [review]
LGTM. Thanks a lot 👍

**Comment by philprime** [comment]
For future reference: SwiftLint does not allow exclusion of files for certain rules in the root `.swiftlint.yml` configuration file. Instead one must create configuration files per directory extending the root and disable the rule there.

File: Sources/Swift/Protocol/SentryLog.swift [hunk 43]
```diff
@@ -97,6 +97,7 @@ public final class SentryLog: NSObject {
         case severityNumber = "severity_number"
     }
     
+    // swiftlint:disable:next missing_docs
```
Comment (philippsuess) [inline Sources/Swift/Protocol/SentryLog.swift]: `m`: It looks like this one misses it's pair `// swiftlint:enable:next missing_docs`

Comment (philprime) [reply Sources/Swift/Protocol/SentryLog.swift]: nice catch!

Comment (philprime) [inline Sources/Swift/Protocol/SentryLog.swift]:
```suggestion
```
