### PR TITLE
fix: Remove Sentry keys from cached HTTP request headers

### LINKED ISSUE #1827: TraceId persisting and not re-generating after Transactions Flush
### Platform

iOS

### Installed

CocoaPods

### Version

7.11.0

### Steps to Reproduce

1. Auto instrument transactions from MainViewController (first one that opens when you Cold Start boot your iOS mobile app)
2. These transactions call a backend in Python instrumented with Sentry SDK for Performance
3. Verify traceId is set appropriately on each so far. Call this traceId-A
4. User sits idle for a few seconds, no transactions are started (none waiting to flush)
5. Navigate to a different ViewController, and see that new traceId+transactions are started and flushed, as traceId-B
6. Call a Custom Transaction on this final ViewController, it must call a backend in Python instrumented with Sentry SDK for Performance. When this transaction+trace flushes, see that hte traceId is now traceId-A again, and did not become a new one (like a traceId-C)

Also, the final error that gets made, does not have a traceId.

Problem also described this way:
**Problem:** The first ViewController that loads during app start gets a traceId, and the next ViewControllers that are loaded due to user navigation get new trace Ids, which makes sense, because the transactions from the first trace have flushed already. However, the backend transactions for the 2nd and 3rd ViewControllers have the traceId from the 1st ViewController. This sucks to explain and I will re-read this again tomorrow hoping this isn’t happening.

### Expected Result

When the final custom transaction is flushed, I'm expecting a traceId-C, as this is happening many seconds after the initial app load and the initial transactions+trace.

Expecting the final error that gets made in iOS, to have a traceId (same as from purchase/checkout, the traceId-C I'm speaking of)

**Expected Behavior:**
trace:f418e658 should not be appearing on application-monitoring-python here. The ‘purchase’ transaction from iOS generates a new trace called 37c765b5 and I expect to see 37c765b5 on the application-monitoring-python’s ‘checkout’ transaction (the purchase function in iOS calls /checkout on the backend)

### Actual Result

also available by this debugging video

https://www.loom.com/share/d5758309b31642bbb3933fca829bd638

and here's a link to the the problematic events:
https://sentry.io/organizations/testorg-az/discover/results/?end=2022-05-11T18%3A24%3A00&field=title&field=event.type&field=project&field=trace&field=timestamp&name=All+Events&project=6249899&project=5808655&query=project%3Awill-cocoa+OR+url%3A%22http%3A%2F%2F127%2A%22&sort=-timestamp&start=2022-05-11T17%3A48%3A35&yAxis=count%28%29

image

### PR DESCRIPTION
**Pull request by kevinrenskers**
## :scroll: Description

When an HTTP request is happening without a span, it used to just reuse the existing headers, which can include an old and unrelated traceId. This caused weird behavior where the request would seem to happen from a totally different part of the app.

## :bulb: Motivation and Context

The root cause of the bug as described in #1827 was actually user error, by doing the HTTP request in a new transaction that wasn't bound to the scope at all. Contrast to the initial request which was done in the scope of `viewDidLoad`, which does get an automatic transaction added to the scope. But because the 2nd request happened with a `nil` value for `SentrySDK.currentHub.scope.span`, the headers from the first request were sent along with the second request (cached by `NSURLSession` itself!).

By scrubbing the cached headers of the Sentry keys, we can prevent the weird behavior as described in the issue, and it'll make it more obvious to the user when the request doesn't show up as part of the trace at all.

Dhiogo and I came to this conclusion/solution together.

Fixes #1827

## :green_heart: How did you test it?

Unit test

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

File: Sources/Sentry/SentryNetworkTracker.m [hunk 1]
```diff
@@ -284,7 +284,9 @@ - (nullable NSDictionary *)addTraceHeader:(nullable NSDictionary *)headers
 
     id<SentrySpan> span = SentrySDK.currentHub.scope.span;
     if (span == nil) {
-        return headers;
+        NSMutableDictionary *existingHeaders = headers.mutableCopy;
+        [existingHeaders removeObjectsForKeys:@[ SENTRY_TRACE_HEADER, SENTRY_BAGGAGE_HEADER ]];
+        return [existingHeaders copy];
```
Comment (brustolin) [inline Sources/Sentry/SentryNetworkTracker.m:289]: Please just add a comment here why we removing the header. 
Because NSURLSession itself caches its, and were good to go.

**Review by brustolin — APPROVED** [review]

**Comment by philipphofmann** [comment]
Thanks @kevinrenskers 👌
