### PR TITLE
fix: Always tracks App start for Hybrid SDKs

### LINKED ISSUE #1657: Sentry Cocoa tracks App start only if `isTracingEnabled` is enabled
### Platform

iOS

### Installed

CocoaPods

### Version

7.9.0

### Steps to Reproduce

Run Sample without traces sampler or traces sample rate
https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryAppStartTrackingIntegration.m#L69-L75

`PrivateSentrySDKOnly.appStartMeasurementHybridSDKMode` is enabled but it's not enough since the `SentryAppStartTracker` only gets installed if the `SentryAppStartTrackingIntegration` is also instaled.

### Expected Result

Hybrid SDKs like RN or Flutter don't sync down the traces sampler or traces sample rate to the Native SDKs for different reasons, but they should be able to still get the App Start data via `PrivateSentrySDKOnly.appStartMeasurement`

### Actual Result

`PrivateSentrySDKOnly.appStartMeasurement` is null

### PR DESCRIPTION
**Pull request by brustolin**
## :scroll: Description

When used by a hybrid SDK, Cocoa SDK should track app start.

## :bulb: Motivation and Context

closes #1657

## :green_heart: How did you test it?

Unit test

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [ ] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

File: Sources/Sentry/SentryAppStartTracker.m [hunk 1]
```diff
@@ -136,8 +136,12 @@ - (void)buildAppStartMeasurement
 
     // With only running this once we know that the process is a new one when the following code is
     // executed.
+#    if TEST
```
Comment (bruno-garcia) [inline Sources/Sentry/SentryAppStartTracker.m:139]:
```suggestion
// We need to make sure the block runs on each test instead of only once
#    if TEST
```

**Review by bruno-garcia — APPROVED** [review]
