### PR TITLE
[WIP] Check type of key before use it as NSString

### LINKED ISSUE #382: SDK crash if event.extra contains a dictionary value with a non-string key
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 5.1
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.4.1**

---
I have following issue:

SDK crash if event.extra contains a dictionary value with a non-string key
```objc
- (NSDictionary *)sentry_sanitize {
    NSMutableDictionary *dict = [NSMutableDictionary dictionary];
    for (NSString *key in self.allKeys) {
        if ([[self objectForKey:key] isKindOfClass:NSDictionary.class]) {
            [dict setValue:[((NSDictionary *)[self objectForKey:key]) sentry_sanitize] forKey:key];
        } else if ([[self objectForKey:key] isKindOfClass:NSDate.class]) {
            [dict setValue:[((NSDate *)[self objectForKey:key]) sentry_toIso8601String] forKey:key];
        } else if ([key hasPrefix:@"__sentry"]) {
            continue; // We don't want to add __sentry variables
        } else {
            [dict setValue:[self objectForKey:key] forKey:key];
        }
    }
    return dict;
}
```
Sentry SDK recursive sanitize dictionary without check for its key
**Steps to reproduce:**
```swift
let event = Event(level: .error)
event.message = "test"
event.extra = ["stringKey": [UIView(): ""]]
Client.shared?.send(event: event, completion: nil)
```

**Actual result:**
- crash

**Expected result:**
- the non-string key should be converted to string by its description

### PR DESCRIPTION
**Pull request by ainopara**
Fixes #382

### CODE REVIEW

File: Sources/Sentry/NSDictionary+SentrySanitize.m [hunk 1]
```diff
@@ -20,15 +20,22 @@ @implementation NSDictionary (SentrySanitize)
...
+        NSString *stringKey;
+        if ([rawKey isKindOfClass:[NSString class]]) {
+            stringKey = rawKey;
+        } else {
+            stringKey = [rawKey description];
+        }
+
+        if ([[self objectForKey:rawKey] isKindOfClass:NSDictionary.class]) {
+            [dict setValue:[((NSDictionary *)[self objectForKey:rawKey]) sentry_sanitize] forKey:stringKey];
+        } else if ([[self objectForKey:stringKey] isKindOfClass:NSDate.class]) {
```
Comment (ainopara) [inline Sources/Sentry/NSDictionary+SentrySanitize.m]: The `stringKey` in this line should be rawKey

**Comment by ainopara** [comment]
Hi, recently I found this pr contains a bug. I'll fix it soon in subsequent pr.
