### PR TITLE
fix: Send release version of the crash instead of actual app version

### LINKED ISSUE #218: Use version and build from crash report instead of actual version

### PR DESCRIPTION
**Pull request by HazAT**
Fixes #218

### CODE REVIEW

File: Sources/Sentry/SentryKSCrashReportConverter.m [hunk 1]
```diff
@@ -90,6 +90,10 @@ - (SentryEvent *)convertReportToEvent {
     event.threads = [self convertThreads];
     event.exceptions = [self convertExceptions];
     event.context = [self convertContext];
+    if (event.context.appContext[@"app_identifier"] && event.context.appContext[@"app_version"] && event.context.appContext[@"app_build"]) {
```
Comment (mitsuhiko) [inline Sources/Sentry/SentryKSCrashReportConverter.m]: Doesn't this do the wrong thing if dist is not in there?

**Comment by mitsuhiko** [comment]
nevermind
