### PR TITLE
fix: Fix watchdog tracking on V9

### LINKED ISSUE #6227: fix: Fix watchdog tracking on V9
> [!NOTE]
> The pull request "[fix: Fix watchdog tracking on V9](https://github.com/getsentry/sentry-cocoa/pull/6226)" was created by @noahsmartin but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

Watchdog tracking requires the hang tracker, and on V9 the hand tracker requires frame tracking.

#skip-changelog

### LINKED ISSUE #6228: fix: Fix watchdog tracking on V9
> [!NOTE]
> The pull request "[fix: Fix watchdog tracking on V9](https://github.com/getsentry/sentry-cocoa/pull/6226)" was created by @noahsmartin but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

Watchdog tracking requires the hang tracker, and on V9 the hang tracker requires frame tracking.

#skip-changelog

### LINKED ISSUE #6229: fix: Fix watchdog tracking on V9
> [!NOTE]
> The pull request "[fix: Fix watchdog tracking on V9](https://github.com/getsentry/sentry-cocoa/pull/6226)" was created by @noahsmartin but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

Watchdog tracking requires the hang tracker, and on V9 the hang tracker requires frame tracking. If you disable hang tracking on V9 but have watchdog tracking enabled, we need to make sure the frame tracker still runs

#skip-changelog

### PR DESCRIPTION
**Pull request by noahsmartin**
Watchdog tracking requires the hang tracker, and on V9 the hang tracker requires frame tracking. If you disable hang tracking on V9 but have watchdog tracking enabled, we need to make sure the frame tracker still runs

#skip-changelog

Closes #6227
Closes #6228
Closes #6229

### CODE REVIEW

**Review by philprime — APPROVED** [review]
LGTM. I changed the PR description to close the duplicate issues

File: Sources/Sentry/SentryBaseIntegration.m [hunk 1]
```diff
@@ -186,8 +186,14 @@ - (BOOL)shouldBeEnabledWithOptions:(SentryOptions *)options
...
         BOOL appHangsV2Disabled = options.isAppHangTrackingV2Disabled;
+#    if SDK_V9
+        BOOL watchdogDisabled = !options.enableWatchdogTerminationTracking;
+#    else
+        // Before V9 this should have no effect so set it to YES
+        BOOL watchdogDisabled = YES;
+#    endif // SDK_V9
 
-        if (performanceDisabled && appHangsV2Disabled) {
+        if (performanceDisabled && appHangsV2Disabled && watchdogDisabled) {
```
Comment (itaybre) [inline Sources/Sentry/SentryBaseIntegration.m:196]: `l`: I would love if you could add the PR description in here so we have some more context here

Comment (noahsmartin) [reply Sources/Sentry/SentryBaseIntegration.m:196]: 👍  Will add this separately to avoid re-running CI
