### PR TITLE
fix: remove release from scope

### LINKED ISSUE #447: enableAutoSessionTracking does not honor own release
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> 5.2
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.0.0-beta.3**

---
I have following issue:
I have enabled the new Release session tracking feature by adding `"enableAutoSessionTracking": true`.
The automatic session tracking works fine, but it always reports with the default release Sentry.io.

I set my own release code like this:
```
SentrySDK.configureScope { scope in
	scope.setRelease(baseAppVersion)
}
```
This is never called, when the automatic tracking is sending data.
I also tried to set the release in the constructor like this:
```
_ = SentrySDK(options:
	["dsn": apiKey,
	 "debug": true,
	 "release": baseAppVersion,
	 "enableAutoSessionTracking": true])
```
This also seems to not produce the desired result.

**Steps to reproduce:**
- use enableAutoSessionTracking in the options during initialization.
- set own release
- publish to testflight

**Actual result:**
- the session is reported as BundleID@Version+Number

**Expected result:**
- the session should be reported as the version set for the scope (or set in the options)

### PR DESCRIPTION
**Pull request by bruno-garcia**
Resolves #447

### CODE REVIEW

File: Sources/Sentry/SentryOptions.m [hunk 1]
```diff
@@ -23,6 +23,17 @@ - (_Nullable instancetype)initWithDict:(NSDictionary<NSString *, id> *)options
         if (nil != error && nil != *error) {
             return nil;
         }
+
+        // If no user define release, use default.
```
Comment (philipphofmann) [inline Sources/Sentry/SentryOptions.m:27]: I think we have a typo in this comment. I don't get it sorry 😄

File: Sources/Sentry/SentryOptions.m [hunk 2]
```diff
@@ -23,6 +23,17 @@ - (_Nullable instancetype)initWithDict:(NSDictionary<NSString *, id> *)options
...
+        if (nil  == self.releaseName) {
+            NSDictionary *infoDict = [[NSBundle mainBundle] infoDictionary];
+            if (nil != infoDict) {
+                self.releaseName = [NSString stringWithFormat:@"%@@%@+%@",
+                                                             infoDict[@"CFBundleIdentifier"],
+                                                             infoDict[@"CFBundleShortVersionString"],
+                                                             infoDict[@"CFBundleVersion"]];
```
Comment (philipphofmann) [inline Sources/Sentry/SentryOptions.m:34]: Can we reformat this to the following please?
```suggestion
                self.releaseName = [NSString stringWithFormat:@"%@@%@+%@",
                                    infoDict[@"CFBundleIdentifier"],
                                    infoDict[@"CFBundleShortVersionString"],
                                    infoDict[@"CFBundleVersion"]];
```

File: Sources/Sentry/SentryOptions.m [hunk 3]
```diff
@@ -23,6 +23,17 @@ - (_Nullable instancetype)initWithDict:(NSDictionary<NSString *, id> *)options
         if (nil != error && nil != *error) {
             return nil;
         }
+
+        // If no user define release, use default.
+        if (nil  == self.releaseName) {
```
Comment (philipphofmann) [inline Sources/Sentry/SentryOptions.m:28]:
```suggestion
        if (nil == self.releaseName) {
```

File: Tests/SentryTests/SentryOptionsTest.m [hunk 4]
```diff
@@ -48,14 +48,27 @@ - (void)testInvalidDsn {
...
 - (void)testRelease {
     SentryOptions *options = [self getValidOptions:@{}];
     XCTAssertNil(options.releaseName);
-    
+
     options = [self getValidOptions:@{@"release": @"abc"}];
     XCTAssertEqualObjects(options.releaseName, @"abc");
 }
+
+- (void)testNoReleaseSetUsesDefault {
```
Comment (philipphofmann) [inline Tests/SentryTests/SentryOptionsTest.m:60]: The tests `testRelease` and `testNoReleaseSetUsesDefault` are failing for me. If we have one for no release set and another one for setting the release, I'm good.

File: Sources/Sentry/SentryOptions.m (hunk 1 above)
Comment (bruno-garcia) [reply Sources/Sentry/SentryOptions.m:27]: image
yeah sorry I never pushed my own "fix".
Will fix

File: Sources/Sentry/SentryScope.m [hunk 5]
```diff
@@ -265,12 +246,6 @@ - (void)applyToSession:(SentrySession *)session {
             session.user = self.userObject.copy;
         }
 
-        NSString *releaseName = [self releaseString];
-        if (nil != releaseName) {
-            // TODO: Make sure release set on options is applied to the scope so it's available now
-            session.releaseName = releaseName;
-        }
```
Comment (marandaneto) [inline Sources/Sentry/SentryScope.m:272]: `high:` should not it be like `session.releaseName = options.releaseName;` instead? I don't see how the session would take the release's name from options.

Comment (bruno-garcia) [reply Sources/Sentry/SentryScope.m:272]: It wasn't there yet. Now it's part of `startSession` using the options of the bound client

File: Tests/SentryTests/SentryOptionsTest.m (hunk 4 above)
Comment (bruno-garcia) [reply Tests/SentryTests/SentryOptionsTest.m:57]: tests are there, lets see if CI is happy now

File: Sources/Sentry/SentryScope.m (hunk 5 above)
Comment (marandaneto) [reply Sources/Sentry/SentryScope.m:272]: got it, LGTM

File: Sources/Sentry/SentryHub.m [hunk 6]
```diff
@@ -32,12 +32,20 @@ - (instancetype)initWithClient:(SentryClient *_Nullable)client andScope:(SentryS
 - (void)startSession {
     SentrySession *lastSession = nil;
     SentryScope *scope = [self getScope];
+    SentryClient *client = [self getClient];
+    SentryOptions *options = [client options];
+    if (nil == options || nil == options.releaseName) {
+        [SentryLog logWithMessage:[NSString stringWithFormat:@"No option or release to start a session."] andLevel:kSentryLogLevelDebug];
```
Comment (philipphofmann) [inline Sources/Sentry/SentryHub.m:38]: Shouldn't this be `kSentryLogLevelError`?
```suggestion
        [SentryLog logWithMessage:[NSString stringWithFormat:@"No option or release to start a session."] andLevel:kSentryLogLevelError];
```

File: Sources/Sentry/SentryHub.m [hunk 7]
```diff
@@ -32,12 +32,20 @@ - (instancetype)initWithClient:(SentryClient *_Nullable)client andScope:(SentryS
...
+        return;
```
Comment (philipphofmann) [inline Sources/Sentry/SentryHub.m:39]: But is it really so bad to have the `releaseName` missing? Isn't it better to have a session without a `releaseName` than to have no session? If the options work fine, the `releaseName` is set to default, if the user doesn't set it. If the user sets the `releaseName` to `nil` manually then sessions would break, if I am not mistaken. So for me it would maybe make sense to just set `releaseName` no matter what.

File: Sources/Sentry/SentryHub.m [hunk 8]
```diff
@@ -32,12 +32,20 @@ - (instancetype)initWithClient:(SentryClient *_Nullable)client andScope:(SentryS
...
+    }
     @synchronized (_sessionLock) {
         if (nil != _session) {
             lastSession = _session;
         }
         _session = [[SentrySession alloc] init];
+        _session.releaseName = options.releaseName;
```
Comment (philipphofmann) [inline Sources/Sentry/SentryHub.m:46]: Can we maybe add tests for this change?

File: Sources/Sentry/SentryOptions.m [hunk 9]
```diff
@@ -23,6 +23,17 @@ - (_Nullable instancetype)initWithDict:(NSDictionary<NSString *, id> *)options
...
+        // If no user-defined release, use default.
+        if (nil == self.releaseName) {
+            NSDictionary *infoDict = [[NSBundle mainBundle] infoDictionary];
+            if (nil != infoDict) {
+                self.releaseName = [NSString stringWithFormat:@"%@@%@+%@",
+                                    infoDict[@"CFBundleIdentifier"],
+                                    infoDict[@"CFBundleShortVersionString"],
+                                    infoDict[@"CFBundleVersion"]];
+            }
+        }
```
Comment (philipphofmann) [inline Sources/Sentry/SentryOptions.m:36]: Would it make sense to also set the default if the user calls `[options setReleaseName:nil];`? What do you think @marandaneto and @HazAT ?

File: Tests/SentryTests/SentryOptionsTest.m [hunk 10]
```diff
@@ -48,14 +48,22 @@ - (void)testInvalidDsn {
...
+    SentryOptions *options = [self getValidOptions:@{}];
+
+    NSDictionary *infoDict = [[NSBundle mainBundle] infoDictionary];
+    NSString *expectedRelease = [NSString stringWithFormat:@"%@@%@+%@",
+                                                           infoDict[@"CFBundleIdentifier"],
+                                                           infoDict[@"CFBundleShortVersionString"],
+                                                           infoDict[@"CFBundleVersion"]];
```
Comment (philipphofmann) [inline Tests/SentryTests/SentryOptionsTest.m:64]: Nitpick
```suggestion
                                 infoDict[@"CFBundleIdentifier"],
                                 infoDict[@"CFBundleShortVersionString"],
                                 infoDict[@"CFBundleVersion"]];

```

File: Tests/SentryTests/SentryOptionsTest.m [hunk 11]
```diff
@@ -48,14 +48,22 @@ - (void)testInvalidDsn {
...
 - (void)testRelease {
-    SentryOptions *options = [self getValidOptions:@{}];
-    XCTAssertNil(options.releaseName);
-    
-    options = [self getValidOptions:@{@"release": @"abc"}];
+    SentryOptions *options = [self getValidOptions:@{@"release": @"abc"}];
     XCTAssertEqualObjects(options.releaseName, @"abc");
 }
+
+- (void)testNoReleaseSetUsesDefault {
```
Comment (philipphofmann) [inline Tests/SentryTests/SentryOptionsTest.m:57]: Nice tests 👏

File: Sources/Sentry/SentryHub.m (hunk 7 above)
Comment (marandaneto) [reply Sources/Sentry/SentryHub.m:39]: @philipphofmann the session protocol requires a `release` version.

File: Sources/Sentry/SentryHub.m (hunk 8 above)
Comment (marandaneto) [reply Sources/Sentry/SentryHub.m:46]: @philipphofmann what's your logaf scale here?

File: Sources/Sentry/SentryOptions.m (hunk 9 above)
Comment (marandaneto) [reply Sources/Sentry/SentryOptions.m:36]: mmm not sure if it's a good idea, if the user calls passing `null`, its purposely or a mistake, I'd rather make the method non-null then

File: Tests/SentryTests/SentryOptionsTest.m (hunk 10 above)
Comment (marandaneto) [reply Tests/SentryTests/SentryOptionsTest.m:64]: @philipphofmann use the logaf scale instead of `Nitpick`

File: Sources/Sentry/SentryHub.m (hunk 8 above)
Comment (bruno-garcia) [reply Sources/Sentry/SentryHub.m:46]: start/end session still has no tests. Will come in a new PR (don't want to hold this PR until then)
