### PR TITLE
fix: Unable to find class: SentryCrashExceptionApplication

### LINKED ISSUE #3949: Mac app crashes on launch when using Sentry static framework
### Platform

macOS

### Environment

Production, Develop, TestFlight

### Installed

Swift Package Manager

### Version

8.25.0

### Did it work on previous versions?

8.21.0

### Steps to Reproduce

1. Create a new macOS app
2. Add Sentry as an SPM dependency
3. Change the Principal Class to `SentryCrashExceptionApplication`, [as described here](https://docs.sentry.io/platforms/apple/guides/macos/usage/#capturing-uncaught-exceptions-in-macos).
4. Run the app

See the attached sample project, which should reproduce the issue.

### Expected Result

The app should launch when run.

### Actual Result

The app crashes on launch. Nothing appears in the Xcode console, but in the macOS console, we see this:

```
Unable to find class: SentryCrashExceptionApplication, exiting
```

I suspect that because there is no reference to `SentryCrashExceptionApplication` in the code, the class was never linked in from the static library, and thus is not present at runtime. If I add any reference to `SentryCrashExceptionApplication` in the code, it launches correctly. For example, I can add this:

```swift
let x = SentryCrashExceptionApplication.self
print(x)
```

Note, though, that if this reference were optimized out by the compiler, then the app might crash again. (Hence the need to actually `print` it.)

It would be nice if Sentry itself could reference `SentryCrashExceptionApplication` on macOS, so that it is seen as a transitive dependency and thus would be linked in when other Sentry APIs are referenced. Alternatively, if referencing `SentryCrashExceptionApplication` in code is necessary, this should be documented.

### Are you willing to submit a PR?

I'd be willing to, but it's not clear what route the team wants to take

### PR DESCRIPTION
**Pull request by brustolin**
## :scroll: Description

Added a reference `SentryCrashExceptionApplication` inside the SDK to prevent compiler from stripping it.

## :bulb: Motivation and Context

closes #3949 

## :green_heart: How did you test it?

Sample

## :pencil: Checklist

You have to check all boxes before merging:

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: Sources/Sentry/SentrySDK.m [hunk 1]
```diff
@@ -196,6 +200,11 @@ + (void)startWithOptions:(SentryOptions *)options
     SENTRY_LOG_DEBUG(@"Configured options: %@", options.debugDescription);
 #endif // defined(DEBUG) || defined(TEST) || defined(TESTCI)
 
+#if TARGET_OS_OSX
+    // Reference to SentryCrashExceptionApplication to prevent compiler from stripping it
```
Comment (philipphofmann) [inline Sources/Sentry/SentrySDK.m:204]: Thanks for the comment 🥇

**Review by philipphofmann — APPROVED** [review]
LGTM
