### PR TITLE
Provide fallbacks for assertions in production

### LINKED ISSUE #2109: Provide fallbacks for assertions in production
### Description

We have a couple `NSAssert`/`NSParameterAssert` usages and some corresponding `XCTAssertThrows` for them, but in release builds, these are compiled out with this setting: 
image

Not all of the assertions are coupled with a corresponding `if` check to e.g. early return or skip usages of the thing being asserted, where in at least one case we could see a crash. We should figure out what should be the proper logic for each location:

- https://github.com/getsentry/sentry-cocoa/blob/0ec4dfeba82f0bbd41f249e300b038986ac0aced/Sources/Sentry/SentryClient.m#L461-L468
- https://github.com/getsentry/sentry-cocoa/blob/0ec4dfeba82f0bbd41f249e300b038986ac0aced/Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodecObjC.m#L126-L130
- https://github.com/getsentry/sentry-cocoa/blob/0ec4dfeba82f0bbd41f249e300b038986ac0aced/Sources/Sentry/SentrySerialization.m#L216-L218
- **Note:** `nil` here is redundant: https://github.com/getsentry/sentry-cocoa/blob/0ec4dfeba82f0bbd41f249e300b038986ac0aced/Sources/Sentry/SentrySwizzle.m#L22-L31
- **Note:** this should be a `NSParameterAssert`: https://github.com/getsentry/sentry-cocoa/blob/0ec4dfeba82f0bbd41f249e300b038986ac0aced/Sources/Sentry/SentrySwizzle.m#L139-L161

### PR DESCRIPTION
**Pull request by kevinrenskers**
Provide fallbacks for assertions in production.

Closes #2109
#skip-changelog

### CODE REVIEW

File: Sources/Sentry/SentrySwizzle.m [hunk 1]
```diff
@@ -136,9 +139,14 @@ + (BOOL)swizzleInstanceMethod:(SEL)selector
                          mode:(SentrySwizzleMode)mode
                           key:(const void *)key
 {
-    NSAssert(!(NULL == key && SentrySwizzleModeAlways != mode),
+    NSAssert(!(key == NULL && mode != SentrySwizzleModeAlways),
```
Comment (kevinrenskers) [inline Sources/Sentry/SentrySwizzle.m:142]: @armcknight mentioned in #2109 that this should be a `NSParameterAssert`, but that can't have a description with it. So I think  `NSAssert` is probably better in the end.

File: Sources/Sentry/SentrySwizzle.m [hunk 2]
```diff
@@ -20,6 +20,9 @@ @implementation SentrySwizzleInfo
 - (SentrySwizzleOriginalIMP)getOriginalImplementation
 {
     NSAssert(_impProviderBlock, nil);
```
Comment (kevinrenskers) [inline Sources/Sentry/SentrySwizzle.m:22]: @armcknight mentioned the redundant `nil` here, but if I remove it the code no longer compiles 🤔
`Too few arguments provided to function-like macro invocation`

So I guess the `nil` was added with good reason. Or we could give it a proper string instead?

File: Sources/Sentry/SentrySwizzle.m (hunk 1 above)
Comment (armcknight) [reply Sources/Sentry/SentrySwizzle.m:142]: TIL NSParameterAssert is just an NSAssert with a predefined message
```
#define NSParameterAssert(condition) NSAssert((condition), @"Invalid parameter not satisfying: %@", @#condition)
```

File: Sources/Sentry/SentrySwizzle.m (hunk 2 above)
Comment (armcknight) [reply Sources/Sentry/SentrySwizzle.m:22]: We should add a message, otherwise we get an assertion/exception with an empty message 
image

Comment (armcknight) [reply Sources/Sentry/SentrySwizzle.m:22]: Typically in the past I've wrapped this in a macro like `SENTRY_ASSERT_NONNULL`

**Review by armcknight — APPROVED** [review]

File: Sources/Sentry/SentrySwizzle.m (hunk 2 above)
Comment (kevinrenskers) [reply Sources/Sentry/SentrySwizzle.m]: I added a message
