### PR TITLE
fix: Remove symbolication that causes deadlocks

### LINKED ISSUE #6698: fix: Remove symbolication that causes deadlocks
> [!NOTE]
> The pull request "[fix: Remove symbolication that causes deadlocks](https://github.com/getsentry/sentry-cocoa/pull/6562)" was created by @noahsmartin but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

Resolves https://github.com/getsentry/sentry-cocoa/issues/6560 (and all the other related issues)

This also has the benefit of unifying the debug and non-debug codepaths to reduce the chances that a bug affects one environment but not the other. For example, the debug behavior of buildStacktraceForCurrentThread would remove the frame for that function itself, but this wouldn't happen in non-debug (since it relied on symbolication). This PR preserves the non-debug behavior, now in all configurations

#skip-changelog

### PR DESCRIPTION
**Pull request by noahsmartin**
Resolves https://github.com/getsentry/sentry-cocoa/issues/6560 (and all the other related issues)

This also has the benefit of unifying the debug and non-debug codepaths to reduce the chances that a bug affects one environment but not the other. For example, the debug behavior of buildStacktraceForCurrentThread would remove the frame for that function itself, but this wouldn't happen in non-debug (since it relied on symbolication). This PR preserves the non-debug behavior, now in all configurations

#skip-changelog

Closes #6698

### CODE REVIEW

File: Sources/Sentry/SentryCrashReportConverter.m [hunk 1]
```diff
@@ -307,15 +307,13 @@ - (SentryFrame *)stackFrameAtIndex:(NSInteger)frameIndex inThreadIndex:(NSIntege
         = (uintptr_t)[frameDictionary[@"instruction_addr"] unsignedLongLongValue];
     NSDictionary *binaryImage = [self binaryImageForAddress:instructionAddress];
     SentryFrame *frame = [[SentryFrame alloc] init];
-    frame.symbolAddress = sentry_formatHexAddress(frameDictionary[@"symbol_addr"]);
+    // The symbol address is not known, so it defaults to 0
+    frame.symbolAddress = @"0x0000000000000000";
```
Comment (philippsuess) [inline Sources/Sentry/SentryCrashReportConverter.m]: `m`: We usually then set these things to `nil` and let the backend set default values, because it gives us more flexibility. Or do we absolutely need to set this to `@"0x0000000000000000"`?

File: Sources/SentryCrash/Recording/SentryCrashReport.c [hunk 2]
```diff
@@ -799,20 +799,6 @@ writeBacktrace(const SentryCrashReportWriter *const writer, const char *const ke
...
-                            writer->addStringElement(writer, SentryCrashField_ObjectName,
-                                sentrycrashfu_lastPathEntry(stackCursor->stackEntry.imageName));
-                        }
-                        writer->addUIntegerElement(writer, SentryCrashField_ObjectAddr,
-                            stackCursor->stackEntry.imageAddress);
-                        if (stackCursor->stackEntry.symbolName != NULL) {
-                            writer->addStringElement(writer, SentryCrashField_SymbolName,
-                                stackCursor->stackEntry.symbolName);
-                        }
-                        writer->addUIntegerElement(writer, SentryCrashField_SymbolAddr,
```
Comment (philippsuess) [inline Sources/SentryCrash/Recording/SentryCrashReport.c:813]: `m`: We should be able to remove also `SentryCrashField_ObjectName`, `SentryCrashField_ObjectAddr`, `SentryCrashField_SymbolName`, `SentryCrashField_SymbolAddr` completely from the codebase.

**Review by philipphofmann — COMMENTED** [review]
We definitely need a clear changelog entry to explain that local symbolication is gone now, and we should add a decision log entry here https://github.com/getsentry/sentry-cocoa/blob/main/develop-docs/DECISIONS.md to explain why we removed local symbolication.

Also, we must check our onboarding here https://docs.sentry.io/platforms/apple/guides/ios/ and the wizard if we shouldn't mention that you need to upload dSYMs to guarantee a great experience. Otherwise, some users might be frustrated during the onboarding, because it usuallally sets `options.debug = true`.

And huge thanks for doing this @noahsmartin

File: Sources/Sentry/SentryCrashReportConverter.m (hunk 1 above)
Comment (noahsmartin) [reply Sources/Sentry/SentryCrashReportConverter.m]: I was trying to leave behavior completely unchanged for when debug = False, which was to set this to this string

File: Sources/SentryCrash/Recording/SentryCrashReport.c (hunk 2 above)
Comment (noahsmartin) [reply Sources/SentryCrash/Recording/SentryCrashReport.c:813]: I actually did that and then undid it because it made the PR even larger, I will re-do it though

**Comment by noahsmartin** [comment]
Thanks @philipphofmann just made those changes?

File: develop-docs/DECISIONS.md [hunk 3]
```diff
@@ -1,5 +1,13 @@
 # Decision Log
 
+## No local symbolication of crashes
+
+Date: Nov 7th, 2025
+Contributors: @noahsmartin, @philipphofmann
+
+We decided to remove local symbolication when capturing a crash. The existing local symbolication was not signal-safe and caused deadlocks (https://github.com/getsentry/sentry-cocoa/issues/6560).
```
Comment (philippsuess) [inline develop-docs/DECISIONS.md]: `m`: It's not just about crashes. It's completely removing it, if I'm not mistaken.
```suggestion
We decided to remove local symbolication. The existing local symbolication was not signal-safe and caused deadlocks (https://github.com/getsentry/sentry-cocoa/issues/6560).
```

File: Sources/Sentry/SentryCrashReportConverter.m (hunk 1 above)
Comment (philippsuess) [reply Sources/Sentry/SentryCrashReportConverter.m]: Please remove it and let it `nil`, I don't think that's required. At least I didn't find anything in our develop docs or in our repos https://github.com/search?q=repo%3Agetsentry%2Fsentry%200x0000000000000000&type=code. I would try sending a frame with the symbol address manually setting to `nil` in `beforeSend` and check what happens. If it makes a difference, we can consider adding it back.

File: develop-docs/DECISIONS.md (hunk 3 above)
Comment (noahsmartin) [reply develop-docs/DECISIONS.md]: I thought of the removal of the rest of it as more of an implementation detail that is more likely to change in the future. Like one day we may add back symbolication on the next launch of the app (assuming it didn't update and change the binary) but maybe I overcomplicated it, will change it

File: Tests/SentryTests/SentryCrash/SentryDefaultThreadInspectorTests.swift [hunk 4]
```diff
@@ -48,74 +46,14 @@ class SentryDefaultThreadInspectorTests: XCTestCase {
...
-    func testGetCurrentThreadsWithStacktrace_WithSymbolication() {
+    func testGetCurrentThreadsWithStacktrace() {
         let queue = DispatchQueue(label: "test-queue", attributes: [.concurrent, .initiallyInactive])
         
         let expect = expectation(description: "Read every thread")
         expect.expectedFulfillmentCount = 10
         
         let sut = self.fixture.getSut(testWithRealMachineContextWrapper: true)
 
-        for _ in 0..<10 {
```
Comment (philippsuess) [inline Tests/SentryTests/SentryCrash/SentryDefaultThreadInspectorTests.swift:59]: I removed this test as we had two of these. One withSymbolication and one without. As we don't have symbolication anymore, we can delete one.

File: Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift [hunk 5]
```diff
@@ -46,33 +45,28 @@ class SentryStacktraceBuilderTests: XCTestCase {
...
         let actual = fixture.sut.buildStacktraceForCurrentThread()
 
         // -- Assert --
-        // Make sure the first 4 frames contain main
-        let isMainInFirstFrames = actual.frames[...3].contains(where: { $0.function == "main" })
+        // Make sure the first 4 frames contain an address close to the main function
+        let isMainInFirstFrames = actual.frames[...3].contains(where: { frame in
+            let inst = Int(frame.instructionAddress?.replacingOccurrences(of: "0x", with: "") ?? "", radix: 16) ?? 0
+            #if targetEnvironment(simulator)
+            return name(for: inst) == "start_sim"
```
Comment (philprime) [inline Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift:63]: `m`: Couldn't this break in future simulator versions? If yes, we should add a comment.

**Review by philprime — APPROVED** [review]
LGTM
