### PR TITLE
test: Fix SentryDestinationTests to handle array type for tags

### LINKED ISSUE #7241: test: Fix SentryDestinationTests to handle array type for tags
> [!NOTE]
> The pull request "[test: Fix SentryDestinationTests to handle array type for tags](https://github.com/getsentry/sentry-cocoa/pull/7240)" was created by @itaybre but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

## :scroll: Description

Fixes a broken test in main branch

## :bulb: Motivation and Context

Our testing structure seems broken because we are not using swift from source but the latest release.
This needs to be fixed

## :pencil: Checklist

You have to check all boxes before merging:

- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### PR DESCRIPTION
**Pull request by itaybre**
## :scroll: Description

Fixes a broken test in main branch

## :bulb: Motivation and Context

Our testing structure seems broken because we are not using swift from source but the latest release.
This needs to be fixed

## :pencil: Checklist

You have to check all boxes before merging:

- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

Closes #7241

### CODE REVIEW

File: 3rd-party-integrations/SentrySwiftyBeaver/Tests/SentryDestinationTests.swift [hunk 1]
```diff
@@ -193,13 +193,12 @@ final class SentryDestinationTests: XCTestCase {
...
-        XCTAssertNotNil(tagsValue)
-        XCTAssertTrue(tagsValue?.contains("production") ?? false, "Tags string should contain 'production'")
-        XCTAssertTrue(tagsValue?.contains("api") ?? false, "Tags string should contain 'api'")
-        XCTAssertTrue(tagsValue?.contains("v2") ?? false, "Tags string should contain 'v2'")
+        XCTAssertEqual(log.attributes["swiftybeaver.context.tags"]?.type, "string[]")
+        if let tagsValue = log.attributes["swiftybeaver.context.tags"]?.value as? [String] {
+            XCTAssertEqual(tagsValue, ["production", "api", "v2"])
+        } else {
+            XCTFail("Tags value should be a [String]")
+        }
```
Comment (philprime) [inline 3rd-party-integrations/SentrySwiftyBeaver/Tests/SentryDestinationTests.swift]: `l`: Should be inlineable

```suggestion
        XCTAssertEqual(log.attributes["swiftybeaver.context.tags"]?.value as? [String], ["production", "api", "v2"])
```
