### PR TITLE
fix: Build failure for Apple Silicon Macs

### LINKED ISSUE #587: Build fails for macOS ARM architecture
_Platform:_
- [ ]  iOS
- [ ]  tvOS
- [X ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [X ]  No

_sentry-cocoa installed with:_
- [X ] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**3.x.x**

---
I have following issue:

When building Sentry as a Universal binary including the new ARM Mac architecture, compilation fails on SentryCrashObjC.c line 236 because it is guarded by `#if defined(__arm64__)` when it actually wants to check for iOS with `#if TARGET_OS_IOS`

**Steps to reproduce:**
- Download new Universal Build version of Xcode 12
- Attempt to build Sentry

**Actual result:**
- Compilation error

**Expected result:**
- Compilation succeeds

### PR DESCRIPTION
**Pull request by cmsj**
## :scroll: Description

See https://github.com/getsentry/sentry-cocoa/issues/587

## :bulb: Motivation and Context

We want to support Apple Silicon Macs.

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify the changes
- [x] All tests are passing
- [x] I've updated the CHANGELOG

## :crystal_ball: Next steps

### CODE REVIEW

File: Sources/SentryCrash/Recording/Tools/SentryCrashObjC.c [hunk 1]
```diff
@@ -232,7 +232,7 @@ decodeIsaPointer(const void *const isaPointer)
 #if ISA_TAG_MASK
     uintptr_t isa = (uintptr_t)isaPointer;
     if (isa & ISA_TAG_MASK) {
-#    if defined(__arm64__)
```
Comment (bruno-garcia) [inline Sources/SentryCrash/Recording/Tools/SentryCrashObjC.c:235]: I found more usages of this approach: https://github.com/getsentry/sentry-cocoa/search?q=defined%28__arm64__%29&unscoped_q=defined%28__arm64__%29

Does it make sense to change it everywhere?

Comment (cmsj) [reply Sources/SentryCrash/Recording/Tools/SentryCrashObjC.c:235]: I won’t pretend to be an expert on either Sentry or ARM architectures, but I believe that at least some of the other places where it’s used, are valid, in that they relate to things like page sizes, which Apple Silicon retains from the iOS CPUs.

Comment (philipphofmann) [reply Sources/SentryCrash/Recording/Tools/SentryCrashObjC.c:235]: The build fails because `kCFCoreFoundationVersionNumber_iOS_8_x_Max` doesn't exist in macOS. It is located in CoreFoundation/CFBase.h of iOS. Before Apple Silicon, only iPhones and iPads used `arm64`. Now we can't use `arm64` to find out whether we are on an iPhone/iPad or a Mac. So we have to use `TARGET_OS_IOS`. The other usages of `__arm64__` pointed out by you @bruno-garcia are processor and not operating system specific so it is fine to keep them.

File: Sources/SentryCrash/Recording/Tools/SentryCrashObjC.c [hunk 2]
```diff
@@ -232,7 +232,7 @@ decodeIsaPointer(const void *const isaPointer)
...
+#    if TARGET_OS_IOS
```
Comment (philipphofmann) [inline Sources/SentryCrash/Recording/Tools/SentryCrashObjC.c:235]: `h`: Travis failed because [`ISA_MASK_OLD` only exists for `__arm64__`](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/SentryCrash/Recording/Tools/SentryCrashObjCApple.h#L52). Some iPhones with the A6 and A6X chip use armv7s. Can we please change it to the following:
```suggestion
#    if TARGET_OS_IOS && defined(__arm64__)
```

**Comment by philipphofmann** [comment]
Thanks, @cmsj for the update. Can you please add
```
- fix: Build failure for Apple Silicon Macs #588
```
In the unreleased section of the [Changelog](https://github.com/getsentry/sentry-cocoa/blob/master/CHANGELOG.md#unreleased) please. Then we are good to merge this.

**Comment by cmsj** [comment]
Thanks @philipphofmann for the reviews/feedback :)

**Comment by mRs-** [comment]
awesome work, I just wanted to start with this as well. Thanks for saving my time!
