### PR TITLE
fix: Transaction default status should be OK

### LINKED ISSUE #1411: Change the default finish status for transactions
Based on @dashed comment in #1350, the `Undefined` status of a transaction is consider an error.

Should we change default finish status in SentryTracer and PerformanceTracker to `Ok`?

@bruno-garcia, @marandaneto, @philipphofmann

### PR DESCRIPTION
**Pull request by brustolin**
## :scroll: Description

Changed the default status of transactions to OK.

## :bulb: Motivation and Context

closes #1411

## :green_heart: How did you test it?

Unit Tests

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

File: Sources/Sentry/SentryTracer.m [hunk 1]
```diff
@@ -223,7 +223,7 @@ - (void)removeTagForKey:(NSString *)key
 
 - (void)finish
 {
-    [self finishWithStatus:kSentrySpanStatusUndefined];
+    [self finishWithStatus:kSentrySpanStatusOk];
```
Comment (philipphofmann) [inline Sources/Sentry/SentryTracer.m:226]: `m`: It's a bad sign, that no test needs to be modified for this change. Can we please add one?

**Review by philipphofmann — APPROVED** [review]
LGTM 🚀, but we need one more test.

File: Tests/SentryTests/Performance/SentryTracerTests.swift [hunk 2]
```diff
@@ -111,6 +111,12 @@ class SentryTracerTests: XCTestCase {
         }
     }
     
+    func testFinish_CheckDefaultStatus() {
```
Comment (philipphofmann) [inline Tests/SentryTests/Performance/SentryTracerTests.swift:114]: Told ya, that only a simple test is needed 😃
