### PR TITLE
fix: Per-instance unmaskView propagates to child views

### LINKED ISSUE #6295: [Session Replay] Unmasking configuration not working - views still masked in Sentry
### Platform

iOS

### Environment

Production, Develop

### Installed

Carthage

### Version

8.53.2

### Xcode Version

16.4

### Did it work on previous versions?

_No response_

### Steps to Reproduce

1. Clone this repo https://github.com/serglom21/sentry-ios-bundle-execution
2. Run the app on a simulator
3. Look at the Replay events

### Expected Result

I would expect the buttons on the first screen to be unmasked

- [Shop Tile Button Unmasking](https://github.com/serglom21/sentry-ios-bundle-execution/blob/main/WhiteLabel/WhiteLabel/NewShopViewController.swift#L194)
- [Test Button Unmasking](https://github.com/serglom21/sentry-ios-bundle-execution/blob/main/WhiteLabel/WhiteLabel/NewShopViewController.swift#L200)

This issue occurs in a **modular iOS app** with the following architecture:

### **Framework-Based Architecture**
- **Main App Bundle**: `SampleApp` (contains AppDelegate and basic setup)
- **Framework Bundle**: `WhiteLabel.framework` (contains view controllers and UI logic)
- **View Controllers**: Located in framework bundle, not main app bundle

### Actual Result

Buttons are not unmasked in the Replay event in Sentry

Image

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by denrase**
Fixes #6295

## :scroll: Description

unmaskView(_:) / sentryReplayUnmask() now unmasks the entire subtree of the target view, matching the documented behavior ("All its content will be visible in the replay"). An explicit maskView(_:) on a descendant still takes precedence. The class-based unmaskedViewClasses option is unchanged — it does not propagate to children.

## :bulb: Motivation and Context

Fixes #6295

## :green_heart: How did you test it?

Unit tests. Sample app.

## :pencil: Checklist

You have to check all boxes before merging:

- [x] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] I updated the wizard if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Comment by denrase** [comment]
@itaybre We need to make sure that this is indeed how it's supposed to be, don't want to introduce unintended PII leakage.

File: Sources/Swift/Core/Tools/ViewCapture/SentryUIRedactBuilder.swift [hunk 1]
```diff
@@ -506,18 +506,19 @@ final class SentryUIRedactBuilder {
...
         let newTransform = concatenateTranform(transform, from: layer, withParent: parentLayer)
         var enforceRedact = forceRedact
+        var enforceIgnore = forceIgnore
 
         if let view = layer.delegate as? UIView {
             // Check if the subtree should be ignored to avoid crashes with some special views.
             if isViewSubtreeIgnored(view) {
                 // If a subtree is ignored, it should be fully redacted and we return early to prevent duplicates, unless the view was marked explicitly to be ignored (e.g. UISwitch).
-                if !shouldIgnore(view: view) {
+                if !forceIgnore && !shouldIgnore(view: view) {
```
Comment (itaybre) [inline Sources/Swift/Core/Tools/ViewCapture/SentryUIRedactBuilder.swift]: Personal preference, but if we have `enforceIgnore`, we should use that variable to avoid confusions

File: Sources/Swift/Core/Tools/ViewCapture/SentryUIRedactBuilder.swift [hunk 2]
```diff
@@ -529,7 +530,11 @@ final class SentryUIRedactBuilder {
                 return
             }
 
-            let ignore = !forceRedact && shouldIgnore(view: view)
+            // Per-instance unmask propagates to the entire subtree so that
+            // children (e.g. the UILabel inside a UIButton) are also unmasked.
+            // Class-based and container-based ignore do NOT propagate.
+            let instanceUnmasked = SentryRedactViewHelper.shouldUnmask(view)
+            let ignore = !forceRedact && (shouldIgnore(view: view) || (forceIgnore && !SentryRedactViewHelper.shouldMaskView(view)))
```
Comment (itaybre) [inline Sources/Swift/Core/Tools/ViewCapture/SentryUIRedactBuilder.swift]: Same here

File: Sources/Swift/Core/Tools/ViewCapture/SentryUIRedactBuilder.swift [hunk 3]
```diff
@@ -546,7 +551,13 @@ final class SentryUIRedactBuilder {
...
                 }
                 enforceRedact = true
-            } else if isOpaque(view) {
+            } else if instanceUnmasked {
+                enforceIgnore = true
+                // Fall through to opaque handling below — an unmasked opaque view
+                // still needs to clip out redact regions behind it.
+            }
+
+            if !enforceRedact && isOpaque(view) {
```
Comment (itaybre) [inline Sources/Swift/Core/Tools/ViewCapture/SentryUIRedactBuilder.swift]: `m`: I understand this enforceRedact was added here to simulate the previous `else if`. Can you add some comments for this?
Also maybe it should be:


```suggestion
            }

            if (ignore || !redact) && isOpaque(view) {
```

**Comment by itaybre** [comment]
##  Performance metrics :rocket:
<table>
  <tr>
    <th>&nbsp;</th>
    <th align="right">Plain</th>
    <th align="right">With Sentry</th>
    <th align="right">Diff</th>
  </tr>
  <tr>
    <th align="left">Startup time</th>
    <td align="right">1250.13 ms</td>
    <td align="right">1272.73 ms</td>
    <td align="right"><strong>22.61 ms</strong></td>
  </tr>
  <tr>
    <th align="left">Size</th>
    <td align="right">23.75 KiB</td>
    <td align="right">956.09 KiB</td>
    <td align="right"><strong>932.34 KiB</strong></td>
  </tr>
</table>
<details><summary><h3>Baseline results on branch: main</h3></summary>
<h3>Startup times</h3>
<table>
  <tr>
    <th>Revision</th>
    <th align="right">Plain</th>
    <th align="right">With Sentry</th>
    <th align="right">Diff</th>
  </tr><tr>
  <th align="left">5b1e2a14e3c5e06609e230b6fdffc8804cca72ea</th>
  <td align="right">1217.63 ms</td>
  <td align="right">1245.49 ms</td>
  <td align="right"><strong>27.86 ms</strong></td>
</tr><tr>
  <th align="left">21cd5ba3b2bde72d691860aa30fecc430a205051</th>
  <td align="right">1218.68 ms</td>
  <td align="right">1255.54 ms</td>
  <td align="right"><strong>36.86 ms</strong></td>
</tr><tr>
  <th align="left">142310c0df20b2317a596f3ae7f8306ce96a2aaf</th>
  <td align="right">1219.87 ms</td>
  <td align="right">1248.71 ms</td>
  <td align="right"><strong>28.84 ms</strong></td>
</tr><tr>
  <th align="left">adeec820112ffcca3bef42d9dbf6957280befd8b</th>
  <td align="right">1220.43 ms</td>
  <td align="right">1254.94 ms</td>
  <td align="right"><strong>34.51 ms</strong></td>
</tr><tr>
  <th align="left">b0c71c84633853557481d184a5e296a61900c442</th>
  <td align="right">1206.29 ms</td>
  <td align="right">1242.13 ms</td>
  <td align="right"><strong>35.84 ms</strong></td>
</tr><tr>
  <th align="left">3bff9ff212460f47d302e631ed0236fc5f73b7d6</th>
  <td align="right">1217.72 ms</td>
  <td align="right">1246.43 ms</td>
  <td align="right"><strong>28.71 ms</strong></td>
</tr><tr>
  <th align="left">d4416bc5141ff5f3d35741589feb021c58ddbe7f</th>
  <td align="right">1219.00 ms</td>
  <td align="right">1248.98 ms</td>
  <td align="right"><strong>29.98 ms</strong></td>
</tr><tr>
  <th align="left">b590539abff0d7a133f18ecc31357d51c1c36778</th>
  <td align="right">1220.42 ms</td>
  <td align="right">1239.82 ms</td>
  <td align="right"><strong>19.40 ms</strong></td>
</tr><tr>
  <th align="left">02391fd0bfea0f2d602e3317862a427761fc0775</th>
  <td align="right">1205.51 ms</td>
  <td align="right">1228.66 ms</td>
  <td align="right"><strong>23.15 ms</strong></td>
</tr><tr>
  <th align="left">d3c19cc947723f2c8ce54178680fdb684152b009</th>
  <td align="right">1204.38 ms</td>
  <td align="right">1225.71 ms</td>
  <td align="right"><strong>21.33 ms</strong></td>
</tr></table>
<h3>App size</h3>
<table>
  <tr>
    <th>Revision</th>
    <th align="right">Plain</th>
    <th align="right">With Sentry</th>
    <th align="right">Diff</th>
  </tr><tr>
  <th align="left">5b1e2a14e3c5e06609e230b6fdffc8804cca72ea</th>
  <td align="right">24.14 KiB</td>
  <td align="right">1.11 MiB</td>
  <td align="right"><strong>1.09 MiB</strong></td>
</tr><tr>
  <th align="left">21cd5ba3b2bde72d691860aa30fecc430a205051</th>
  <td align="right">24.14 KiB</td>
  <td align="right">1.04 MiB</td>
  <td align="right"><strong>1.02 MiB</strong></td>
</tr><tr>
  <th align="left">142310c0df20b2317a596f3ae7f8306ce96a2aaf</th>
  <td align="right">24.14 KiB</td>
  <td align="right">1.12 MiB</td>
  <td align="right"><strong>1.10 MiB</strong></td>
</tr><tr>
  <th align="left">adeec820112ffcca3bef42d9dbf6957280befd8b</th>
  <td align="right">24.14 KiB</td>
  <td align="right">1.04 MiB</td>
  <td align="right"><strong>1.02 MiB</strong></td>
</tr><tr>
  <th align="left">b0c71c84633853557481d184a5e296a61900c442</th>
  <td align="right">24.14 KiB</td>
  <td align="right">1.08 MiB</td>
  <td align="right"><strong>1.06 MiB</strong></td>
</tr><tr>
  <th align="left">3bff9ff212460f47d302e631ed0236fc5f73b7d6</th>
  <td align="right">24.14 KiB</td>
  <td align="right">1.11 MiB</td>
  <td align="right"><strong>1.09 MiB</strong></td>
</tr><tr>
  <th align="left">d4416bc5141ff5f3d35741589feb021c58ddbe7f</th>
  <td align="right">24.14 KiB</td>
  <td align="right">1.12 MiB</td>
  <td align="right"><strong>1.10 MiB</strong></td>
</tr><tr>
  <th align="left">b590539abff0d7a133f18ecc31357d51c1c36778</th>
  <td align="right">24.14 KiB</td>
  <td align="right">1.12 MiB</td>
  <td align="right"><strong>1.09 MiB</strong></td>
</tr><tr>
  <th align="left">02391fd0bfea0f2d602e3317862a427761fc0775</th>
  <td align="right">24.14 KiB</td>
  <td align="right">1.11 MiB</td>
  <td align="right"><strong>1.09 MiB</strong></td>
</tr><tr>
  <th align="left">d3c19cc947723f2c8ce54178680fdb684152b009</th>
  <td align="right">24.14 KiB</td>
  <td align="right">1.13 MiB</td>
  <td align="right"><strong>1.10 MiB</strong></td>
</tr></table>
</details>
<details><summary><h3>Previous results on branch: fix/unmask-descendants-as-well</h3></summary>
<h3>Startup times</h3>
<table>
  <tr>
    <th>Revision</th>
    <th align="right">Plain</th>
    <th align="right">With Sentry</th>
    <th align="right">Diff</th>
  </tr><tr>
  <th align="left">ecce2e2718b6d97ad62220fca05627900b061ed5+dirty</th>
  <td align="right">1250.13 ms</td>
  <td align="right">1272.73 ms</td>
  <td align="right"><strong>22.61 ms</strong></td>
</tr><tr>
  <th align="left">ecce2e2718b6d97ad62220fca05627900b061ed5+dirty</th>
  <td align="right">1250.13 ms</td>
  <td align="right">1272.73 ms</td>
  <td align="right"><strong>22.61 ms</strong></td>
</tr><tr>
  <th align="left">4c4980abf09f06d688b82e81cfa8973e4ba5cefe+dirty</th>
  <td align="right">0.00 ms</td>
  <td align="right">0.00 ms</td>
  <td align="right"><strong>0.00 ms</strong></td>
</tr><tr>
  <th align="left">ecce2e2718b6d97ad62220fca05627900b061ed5+dirty</th>
  <td align="right">1250.13 ms</td>
  <td align="right">1272.73 ms</td>
  <td align="right"><strong>22.61 ms</strong></td>
</tr></table>
<h3>App size</h3>
<table>
  <tr>
    <th>Revision</th>
    <th align="right">Plain</th>
    <th align="right">With Sentry</th>
    <th align="right">Diff</th>
  </tr><tr>
  <th align="left">ecce2e2718b6d97ad62220fca05627900b061ed5+dirty</th>
  <td align="right">23.75 KiB</td>
  <td align="right">956.09 KiB</td>
  <td align="right"><strong>932.34 KiB</strong></td>
</tr><tr>
  <th align="left">ecce2e2718b6d97ad62220fca05627900b061ed5+dirty</th>
  <td align="right">23.75 KiB</td>
  <td align="right">956.09 KiB</td>
  <td align="right"><strong>932.34 KiB</strong></td>
</tr><tr>
  <th align="left">4c4980abf09f06d688b82e81cfa8973e4ba5cefe+dirty</th>
  <td align="right">23.74 KiB</td>
  <td align="right">889.60 KiB</td>
  <td align="right"><strong>865.86 KiB</strong></td>
</tr><tr>
  <th align="left">ecce2e2718b6d97ad62220fca05627900b061ed5+dirty</th>
  <td align="right">23.75 KiB</td>
  <td align="right">956.09 KiB</td>
  <td align="right"><strong>932.34 KiB</strong></td>
</tr></table>
</details>
