### PR TITLE
fix: Clean up old envelopes

### LINKED ISSUE #1812: Handle DSN changes
### Description

Currently, when having session, app state, or envelopes stored on disk and the user changes the DSN to a new one, this data stays there forever. As the path for storing this data depends on the hash of the DSN see

https://github.com/getsentry/sentry-cocoa/blob/4125751b104bee6763236cf539d46aec78549926/Sources/Sentry/SentryFileManager.m#L48-L54

The SDK should delete this data and maybe also send cached envelopes to Sentry with the new DSN. Just deleting might be fine as this is an edge case. 

Please align this behavior with Android.

### PR DESCRIPTION
**Pull request by kevinrenskers**
## :scroll: Description

We now clean up old envelopes after 90 days. So when changing DSN for example, old envelopes don't linger around forever and ever.

## :bulb: Motivation and Context

Fixes #1812

## :green_heart: How did you test it?

Unit tests

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

**Comment by kevinrenskers** [comment]
How can we test this? Maybe we can create files on disk with an old creation date? Is that possible? 🤔

**Comment by brustolin** [comment]
> How can we test this? Maybe we can create files on disk with an old creation date? Is that possible? 🤔

Well, sound like a good idea.
I believe you can use https://developer.apple.com/documentation/foundation/nsfilemanager/1413667-setattributes to achieve this.

File: Sources/Sentry/SentryFileManager.m [hunk 1]
```diff
@@ -81,6 +82,9 @@ - (nullable instancetype)initWithOptions:(SentryOptions *)options
 
         self.currentFileCounter = 0;
         self.maxEnvelopes = options.maxCacheItems;
+
+        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0),
```
Comment (philipphofmann) [inline Sources/Sentry/SentryFileManager.m:86]: `m`: I think we could delay this for a couple of seconds when the app and the SDK finished launching. What about 10 seconds? You then could use the `DispatchQueueWrapper` to improve testability, so you don't have to wait for 10 seconds.

File: Sources/Sentry/SentryFileManager.m [hunk 2]
```diff
@@ -158,6 +161,44 @@ - (SentryFileContents *_Nullable)getFileContents:(NSString *)folderPath
     }
 }
 
+// Delete every envelope in self.basePath older than 90 days
```
Comment (philipphofmann) [inline Sources/Sentry/SentryFileManager.m:164]: `l`: Please clarify why it is acceptable to delete these.

File: Sources/Sentry/SentryFileManager.m [hunk 3]
```diff
@@ -158,6 +161,44 @@ - (SentryFileContents *_Nullable)getFileContents:(NSString *)folderPath
...
+        }
+
+        // Then we will remove all old items from the envelopes subdirectory
+        [self deleteOldEnvelopesFromPath:[fullPath stringByAppendingPathComponent:@"envelopes"]];
+    }
+}
+
+- (void)deleteOldEnvelopesFromPath:(NSString *)envelopesPath
+{
+    NSTimeInterval now = [[NSDate date] timeIntervalSince1970];
```
Comment (philipphofmann) [inline Sources/Sentry/SentryFileManager.m:183]: `m`: Please use the `SentryCurrentDateProvider` to improve testability.

File: Sources/Sentry/SentryFileManager.m [hunk 4]
```diff
@@ -158,6 +161,44 @@ - (SentryFileContents *_Nullable)getFileContents:(NSString *)folderPath
...
+                                                                              error:nil];
+        if (!dict || !dict[NSFileCreationDate]) {
+            continue;
+        }
+
+        NSTimeInterval age = now - [dict[NSFileCreationDate] timeIntervalSince1970];
+        if (age > 90 * 24 * 60 * 60) {
+            [self removeFileAtPath:fullPath];
+            SENTRY_LOG_DEBUG(
+                @"Removed envelope at path %@ becuase it was older than 90 days", fullPath);
```
Comment (philipphofmann) [inline Sources/Sentry/SentryFileManager.m:197]:
```suggestion
                @"Removed envelope at path %@ because it was older than 90 days", fullPath);
```

File: Sources/Sentry/SentryFileManager.m [hunk 5]
```diff
@@ -158,6 +161,44 @@ - (SentryFileContents *_Nullable)getFileContents:(NSString *)folderPath
...
+    }
+}
+
+- (void)deleteOldEnvelopesFromPath:(NSString *)envelopesPath
+{
+    NSTimeInterval now = [[NSDate date] timeIntervalSince1970];
+
+    for (NSString *path in [self allFilesInFolder:envelopesPath]) {
+        NSString *fullPath = [envelopesPath stringByAppendingPathComponent:path];
+        NSDictionary *dict = [[NSFileManager defaultManager] attributesOfItemAtPath:fullPath
```
Comment (philipphofmann) [inline Sources/Sentry/SentryFileManager.m:187]: `m`: We can at least check if the error is `nil` and if it's not, log a message and call `continue`.

File: Sources/Sentry/include/SentryFileManager.h [hunk 6]
```diff
@@ -36,8 +36,8 @@ SENTRY_NO_INIT
 
 + (BOOL)createDirectoryAtPath:(NSString *)path withError:(NSError **)error;
 
+- (void)deleteOldEnvelopesFromAllSentryPaths;
```
Comment (philipphofmann) [inline Sources/Sentry/include/SentryFileManager.h:39]: `m`: This doesn't have to be public. We can test it by calling the constructor.
```suggestion
```

File: Tests/SentryTests/Helper/SentryFileManagerTests.swift [hunk 7]
```diff
@@ -139,6 +139,19 @@ class SentryFileManagerTests: XCTestCase {
         let actualData = envelopes[0].contents
         XCTAssertEqual(expectedData, actualData as Data)
     }
+
+    func testDeleteOldEnvelopes() throws {
```
Comment (philipphofmann) [inline Tests/SentryTests/Helper/SentryFileManagerTests.swift:143]: `m`: Please add a test case where the folder is older than 90 days to ensure we only delete files in that folder older than 90 days and not the folder. If that happened, it would be nasty.

File: Tests/SentryTests/Helper/SentryFileManagerTests.swift [hunk 8]
```diff
@@ -139,6 +139,19 @@ class SentryFileManagerTests: XCTestCase {
...
+        let envelope = TestConstants.envelope
+        let path = sut.store(envelope)
+
+        try FileManager.default.setAttributes([FileAttributeKey.creationDate: Date(timeIntervalSince1970: 0)], ofItemAtPath: path)
```
Comment (philipphofmann) [inline Tests/SentryTests/Helper/SentryFileManagerTests.swift:147]: `m`: Please add one test case where the file is exactly 90 days old and doesn't get deleted and one where the file is 90.0001 days old, and gets deleted. This is testing the [boundary values of the equivalence classes](https://www.geeksforgeeks.org/equivalence-class-testing-next-date-problem/), which improves the test and minimizes off by one errors.

**Review by philipphofmann — COMMENTED** [review]
A couple of comments. Thank you, @kevinrenskers, for fixing that 💪.

File: Sources/Sentry/include/SentryFileManager.h (hunk 6 above)
Comment (kevinrenskers) [reply Sources/Sentry/include/SentryFileManager.h:39]: It's not public since the entire header isn't public. And I think testing it by calling the method is a whole lot easier?

File: Tests/SentryTests/Helper/SentryFileManagerTests.swift (hunk 8 above)
Comment (kevinrenskers) [reply Tests/SentryTests/Helper/SentryFileManagerTests.swift]: Done

File: Tests/SentryTests/Helper/SentryFileManagerTests.swift (hunk 7 above)
Comment (kevinrenskers) [reply Tests/SentryTests/Helper/SentryFileManagerTests.swift:143]: Done

File: Sources/Sentry/SentryFileManager.m (hunk 1 above)
Comment (kevinrenskers) [reply Sources/Sentry/SentryFileManager.m:86]: Is that better than just using `DISPATCH_QUEUE_PRIORITY_LOW`?

File: Sources/Sentry/include/SentryFileManager.h (hunk 6 above)
Comment (philipphofmann) [reply Sources/Sentry/include/SentryFileManager.h:39]: Testing it via the constructor has the advantage of testing it like the SDK code calls this method. Right now, your tests don't ensure the code gets executed when calling the constructor.

Comment (kevinrenskers) [reply Sources/Sentry/include/SentryFileManager.h:39]: I see your point, but we don't have to deal with async code and the flakiness that brings either 😬

File: Sources/Sentry/SentryFileManager.m (hunk 1 above)
Comment (philipphofmann) [reply Sources/Sentry/SentryFileManager.m:86]: Even with `DISPATCH_QUEUE_PRIORITY_LOW` it adds overhead at the beginning of the app start. This has a really low priority and can run later.

File: Sources/Sentry/SentryFileManager.m [hunk 9]
```diff
@@ -158,6 +161,47 @@ - (SentryFileContents *_Nullable)getFileContents:(NSString *)folderPath
     }
 }
 
+// Delete every envelope in self.basePath older than 90 days,
+// as Sentry only retains data for 90 days.
```
Comment (philipphofmann) [inline Sources/Sentry/SentryFileManager.m:165]: Thanks 🙏

File: Tests/SentryTests/Helper/SentryFileManagerTests.swift [hunk 10]
```diff
@@ -139,7 +139,49 @@ class SentryFileManagerTests: XCTestCase {
...
+    func testDontDeleteYoungEnvelopes() throws {
+        let envelope = TestConstants.envelope
+        let path = sut.store(envelope)
+
+        let date = Date(timeIntervalSinceNow: (-90 * 24 * 60 * 60) + 1)
+        try FileManager.default.setAttributes([FileAttributeKey.creationDate: date], ofItemAtPath: path)
+
+        XCTAssertEqual(sut.getAllEnvelopes().count, 1)
+
+        sut.deleteOldEnvelopesFromAllSentryPaths()
```
Comment (philipphofmann) [inline Tests/SentryTests/Helper/SentryFileManagerTests.swift:166]: That code could lead now to a flaky test when testing with the actual date, as I pointed out in https://github.com/getsentry/sentry-cocoa/pull/2322#discussion_r1004147731

If the test is really slow, it could be that more than a second passes between setting the date in the file manager above and calling `deleteOldEnvelopesFromAllSentryPaths`.

File: Tests/SentryTests/Helper/SentryFileManagerTests.swift [hunk 11]
```diff
@@ -139,7 +139,49 @@ class SentryFileManagerTests: XCTestCase {
...
+
+        XCTAssertEqual(sut.getAllEnvelopes().count, 0)
+    }
+
+    func testDontDeleteYoungEnvelopes() throws {
+        let envelope = TestConstants.envelope
+        let path = sut.store(envelope)
+
+        let date = Date(timeIntervalSinceNow: (-90 * 24 * 60 * 60) + 1)
```
Comment (philipphofmann) [inline Tests/SentryTests/Helper/SentryFileManagerTests.swift:161]: If you want to be even more precise you can change this to, and then for sure your test would start failing some times when using NSDate in the implementation.
```suggestion
        let date = Date(timeIntervalSinceNow: (-90 * 24 * 60 * 60) + 0.001)
```

File: Sources/Sentry/SentryFileManager.m (hunk 1 above)
Comment (kevinrenskers) [reply Sources/Sentry/SentryFileManager.m]: That is true, but then again after 10 seconds you might be starting some heavy operation as well 😅

In fact it's probably more likely that you're using the app and navigation between different screens 10 seconds after starting the app vs immediately after starting the app. Not sure about this!

File: Sources/Sentry/SentryFileManager.m (hunk 3 above)
Comment (kevinrenskers) [reply Sources/Sentry/SentryFileManager.m]: Done

File: Sources/Sentry/include/SentryFileManager.h (hunk 6 above)
Comment (philipphofmann) [reply Sources/Sentry/include/SentryFileManager.h:39]: That's why you can use `SentryDispatchQueueWrapper` in the code and `TestSentryDispatchQueueWrapper` in the tests to avoid the flakyness.

File: Sources/Sentry/SentryFileManager.m (hunk 1 above)
Comment (kevinrenskers) [reply Sources/Sentry/SentryFileManager.m]: I've used SentryDispatchQueueWrapper, but I am not sure the 10 second delay is a great idea. Also, SentryDispatchQueueWrapper uses a default queue instead of a low priority queue.

File: Sources/Sentry/include/SentryFileManager.h (hunk 6 above)
Comment (kevinrenskers) [reply Sources/Sentry/include/SentryFileManager.h]: Done

**Comment by kevinrenskers** [comment]
This PR has been waiting for a (re-)review for six days now. All checks are green, it's not marked as a draft either. What's blocking it?

**Review by brustolin — APPROVED** [review]
LGTM
