### PR TITLE
fix: Correctly attribute enterprise builds

### LINKED ISSUE #778: Attribute issues from enterprise builds with build_type "enterprise" instead of "test"
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**6.0.0**

---

Currently apps signed and distributed as enterprise apps, are attributed with `build_type` `"test"`. I'm not completely sure if there's a good way for determining this, but I believe enterprise apps include the `embedded.mobileprovision` file in the bundle, so maybe that can be used to determine the app is an enterprise build?

### PR DESCRIPTION
**Pull request by kevinrenskers**
## :scroll: Description

This uses the check as suggested in the ticket, and I've found similar suggestions in StackOverflow and in HockeySDK-iOS (the old HockeyApp SDK). But I have no way of verifying this, and it feels a bit scary. I am also not sure how well this will age, maybe this will change with future iOS versions?

If users already have a way of overriding the build type, I am not 100% convinced we should add this to the SDK.

## :bulb: Motivation and Context

Closes #778

## :green_heart: How did you test it?

Impossible :/

## :pencil: Checklist

- [x] I reviewed the submitted code
- [ ] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

File: Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m [hunk 1]
```diff
@@ -368,26 +368,15 @@
 
 /** The file path for the bundle’s App Store receipt.
  *
- * @return App Store receipt for iOS 7+, nil otherwise.
+ * @return App Store receipt for iOS, nil otherwise.
  */
 static NSString *
 getReceiptUrlPath()
 {
-    NSString *path = nil;
```
Comment (kevinrenskers) [inline Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m:376]: All these checks seemed a bit silly as we support iOS 9 and up.

**Review by brustolin — APPROVED** [review]
LGTM

**Review by philipphofmann — APPROVED** [review]
Let's give it a try. LGTM
