### PR TITLE
fix: Remove SentrySystemEventBreadcrumbs observers with the most specific detail possible

### LINKED ISSUE #2486: Crash when changing timeZone
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.31.3

### Steps to Reproduce

1. Have app with sentry configured
2. Go into the app with default timeZone
3. minimize the app and in settings change time zone
4. return back to app

### Expected Result

App not to crash

### Actual Result

App crashes with #6	0x10234b74c in -[SentrySystemEventBreadcrumbs timezoneEventTriggered:] at /Users/****/Library/Developer/Xcode/DerivedData/*****-fwzmbhprgokykgdjwnmlxdqviucf/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentrySystemEventBreadcrumbs.m:238

### PR DESCRIPTION
**Pull request by kevinrenskers**
## :scroll: Description

Same as we did in the other files. Maybe this fixes #2486, although I am not sure. Doesn't hurt either way.

## :bulb: Motivation and Context

Could maybe fix #2486.

## :green_heart: How did you test it?

Unit tests

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

File: Sources/Sentry/SentrySystemEventBreadcrumbs.m [hunk 1]
```diff
@@ -41,11 +41,28 @@ - (void)start
 - (void)stop
 {
 #if TARGET_OS_IOS
+    // Remove the observers with the most specific detail possible, see
+    // https://developer.apple.com/documentation/foundation/nsnotificationcenter/1413994-removeobserver
     NSNotificationCenter *defaultCenter = [NSNotificationCenter defaultCenter];
-    [defaultCenter removeObserver:self];
+    [defaultCenter removeObserver:self name:UIKeyboardDidShowNotification object:nil];
```
[the remark this answers is not in the document]
Comment (kevinrenskers) [reply Sources/Sentry/SentrySystemEventBreadcrumbs.m]: I don't think this is the cause of the crash, but it's still a good change to make.

**Comment by kevinrenskers** [comment]
I ran `brew upgrade` today and now I got a bunch of code formatting changes, that were then overwritten again by CI. How can we make sure that we all + CI are on the same version? I think the problem is SwiftLint: I am running version 0.50.1 but the version in `Brewfile.lock.json` is 0.49.1.

Then again the version of clang-format is locked to 15.0.4 yet the Format Code workflow installs 15.0.6, so I don't understand how that works 🤔

File: Tests/SentryTests/Integrations/Breadcrumbs/SentryAutoBreadcrumbTrackingIntegrationTests.swift [hunk 2]
```diff
@@ -37,7 +37,7 @@ class SentryAutoBreadcrumbTrackingIntegrationTests: XCTestCase {
         
         let options = Options()
         options.enableSwizzling = false
-        sut.install(with: options, breadcrumbTracker: fixture.tracker, systemEventBreadcrumbs: SentrySystemEventBreadcrumbs(fileManager: SentryDependencyContainer.sharedInstance().fileManager, andCurrentDateProvider: DefaultCurrentDateProvider.sharedInstance()))
+        sut.install(with: options, breadcrumbTracker: fixture.tracker, systemEventBreadcrumbs: SentrySystemEventBreadcrumbs(fileManager: SentryDependencyContainer.sharedInstance().fileManager, andCurrentDateProvider: DefaultCurrentDateProvider.sharedInstance(), andNotificationCenterWrapper: TestNSNotificationCenterWrapper()))
```
Comment (kevinrenskers) [inline Tests/SentryTests/Integrations/Breadcrumbs/SentryAutoBreadcrumbTrackingIntegrationTests.swift:40]:
```suggestion
        sut.install(with: options, breadcrumbTracker: fixture.tracker, systemEventBreadcrumbs: SentrySystemEventBreadcrumbs(fileManager: SentryDependencyContainer.sharedInstance().fileManager, andCurrentDateProvider: DefaultCurrentDateProvider.sharedInstance(), andNotificationCenterWrapper: SentryNSNotificationCenterWrapper()))
```

File: Sources/Sentry/SentrySystemEventBreadcrumbs.m [hunk 3]
```diff
@@ -41,11 +45,30 @@ - (void)start
 - (void)stop
 {
 #if TARGET_OS_IOS
-    NSNotificationCenter *defaultCenter = [NSNotificationCenter defaultCenter];
-    [defaultCenter removeObserver:self];
+    // Remove the observers with the most specific detail possible, see
+    // https://developer.apple.com/documentation/foundation/nsnotificationcenter/1413994-removeobserver
+    [self.notificationCenterWrapper removeObserver:self name:UIKeyboardDidShowNotification];
```
Comment (armcknight) [inline Sources/Sentry/SentrySystemEventBreadcrumbs.m:50]: If we're removing observers via the wrapper object, shouldn't we also be adding observers using it instead of the defaultCenter used on lines 98, 158, 189, 215 and 234?

Comment (kevinrenskers) [reply Sources/Sentry/SentrySystemEventBreadcrumbs.m:50]: Sure thing

**Review by brustolin — APPROVED** [review]
LGTM
