### PR TITLE
fix: Concurrency crash for Swift 6

### LINKED ISSUE #4509: Crash caused by inclusion of `beforeSend` option.
### Platform

iOS

### Environment

TestFlight, Production, Develop

### Installed

Swift Package Manager

### Version

8.36.0

### Xcode Version

16.1

### Did it work on previous versions?

No

### Steps to Reproduce

1. Include a `beforeSend` block in SentrySDK initialisation.
2. Invoke a crash in the application.
3. Attempt to relaunch the application

It's worth calling out that this crash started appearing with Xcode 16.0 & Xcode 16.1 builds. Builds with Xcode 15 haven't shown this issue.
I've also tried updating Sentry to v8.39.0, but this doesn't resolve the issue.

Sample project for reproduction attached. 
This crash occurs intermittently in the supplied sample project, but ever time in our main project. 

[BeforeSendCrash.zip](https://github.com/user-attachments/files/17635843/BeforeSendCrash.zip)

### Expected Result

Application relaunches as usual and report is sent to Sentry.

### Actual Result

Application crashes on first attempted relaunch.
Application launches successfully on second attempt, and sends two crash reports to Sentry - the original crash and the SentrySDK crash.

Image
Image

https://github.com/user-attachments/assets/465e3f5f-065b-4566-b626-cceda34cfbd4

### Are you willing to submit a PR?

No

### PR DESCRIPTION
**Pull request by brustolin**
## :scroll: Description

Swift 6 introduce some concurrency checks to avoid race conditions, but objc does not have this features.
We need to annotate of callbacks so swift knows how it will be used.

## :bulb: Motivation and Context

Close #4509 

## :green_heart: How did you test it?

Samples and UITest

## :pencil: Checklist

You have to check all boxes before merging:

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Comment by brustolin** [comment]
>  This looks great. I'm only waiting for CI to be green. Thanks for adding a sample

Ci is drunk today.

File: Samples/iOS-Swift/iOS-Swift6/ViewController.swift [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import Sentry
+import UIKit
+
+class ViewController: UIViewController {
```
Comment (philipphofmann) [inline Samples/iOS-Swift/iOS-Swift6/ViewController.swift:4]: Can we change the sample to SwiftUI? I guess most people using Swift 6 will also use SwiftUI.

File: Samples/iOS-Swift/iOS-Swift6UITests/UITests.swift [hunk 2]
```diff
@@ -0,0 +1,15 @@
+import XCTest
+
+final class UITests: XCTestCase {
```
Comment (philipphofmann) [inline Samples/iOS-Swift/iOS-Swift6UITests/UITests.swift:3]: `m`: As this can lead to crashes we could add this to UI tests critical and migrate this test to maestro.

**Review by philipphofmann — APPROVED** [review]
Thanks for adding a sample. Maybe it makes sense to use SwiftUI; see comment. LGTM.

File: Samples/iOS-Swift/iOS-Swift6UITests/UITests.swift (hunk 2 above)
Comment (brustolin) [reply Samples/iOS-Swift/iOS-Swift6UITests/UITests.swift:3]: We're using Mastro for tests that require the app to crash and be reopened.
This is not the case. If the app closes in this test, it's because something went wrong.
I prefer to avoid an external tool (Maestro in this case) as much as possible.

File: Samples/iOS-Swift/iOS-Swift6/ViewController.swift (hunk 1 above)
Comment (philipphofmann) [reply Samples/iOS-Swift/iOS-Swift6/ViewController.swift:4]: SwiftUI would have been less code 😄

File: Samples/iOS-Swift/iOS-Swift6UITests/UITests.swift (hunk 2 above)
Comment (philipphofmann) [reply Samples/iOS-Swift/iOS-Swift6UITests/UITests.swift:3]: Also fine.
