### PR TITLE
fix: Capture instance and class method `[NSApplication _crashOnException]` exceptions

### LINKED ISSUE #6620: Stacktrace shows +[SentryCrashExceptionApplicationHelper _crashOnException:] instead of actual stacktrace
### Platform

macOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.53.1

### Xcode Version

26.0

### Did it work on previous versions?

_No response_

### Steps to Reproduce

My current guess is that this specific crash is an old AppKit/SwiftUI crash that happens when dragging a window with AppKit/SwiftUI content between 1x and 2x (retina) displays. Drag back and forth quickly to try to reproduce it. 
The actual problem reported in this issue is not that specific Apple crash but that it is missing the full stacktrace in Sentry. As I don't see the real stack in Sentry, I am not 100% that's a good way to reproduce it. And we do get the actual stack for that case *sometimes*.

### Expected Result

If my guess is correct, this is what I would expect:
```
Application Specific Information:
*** Collection <__NSArrayM: 0x600003a96cd0> was mutated while being enumerated.

Thread 0 Crashed:
0   CoreFoundation                  0x31f153c94         __exceptionPreprocess
1   libobjc.A.dylib                 0x31e7aeb8c         objc_exception_throw
2   CoreFoundation                  0x31f202988         __NSFastEnumerationMutationHandler
3   AppKit                          0x327d716d8         -[NSView(NSConstraintBasedLayoutInternal) _adjustLayoutForResolutionChangeToRetina:]
4   AppKit                          0x327d716e8         [inlined] -[NSView(NSConstraintBasedLayoutInternal) _adjustLayoutForResolutionChangeToRetina:]
5   AppKit                          0x327d716e8         [inlined] -[NSView(NSConstraintBasedLayoutInternal) _adjustLayoutForResolutionChangeToRetina:]
6   AppKit                          0x327d716e8         [inlined] -[NSView(NSConstraintBasedLayoutInternal) _adjustLayoutForResolutionChangeToRetina:]
7   AppKit                          0x327d716e8         [inlined] -[NSView(NSConstraintBasedLayoutInternal) _adjustLayoutForResolutionChangeToRetina:]
8   AppKit                          0x327d716e8         [inlined] -[NSView(NSConstraintBasedLayoutInternal) _adjustLayoutForResolutionChangeToRetina:]
9   AppKit                          0x327d716e8         [inlined] -[NSView(NSConstraintBasedLayoutInternal) _adjustLayoutForResolutionChangeToRetina:]
10  AppKit                          0x327d716e8         [inlined] -[NSView(NSConstraintBasedLayoutInternal) _adjustLayoutForResolutionChangeToRetina:]
11  AppKit                          0x327d716e8         -[NSView(NSConstraintBasedLayoutInternal) _adjustLayoutForResolutionChangeToRetina:]
12  AppKit                          0x327aaa890         -[NSWindow _updateInheritedBackingScaleFactorIfNeeded]
13  AppKit                          0x32712fd48         __67-[NSWindow _updateSettingsSendingScreenChangeNotificationToScreen:]_block_invoke
14  AppKit                          0x326fb206c         NSPerformVisuallyAtomicChange
15  AppKit                          0x32712fbac         -[NSWindow _updateSettingsSendingScreenChangeNotificationToScreen:]
16  AppKit                          0x326fb35b8         -[NSWindow _setFrameCommon:display:fromServer:]
17  AppKit                          0x327aa133c         -[NSWindow(NSScreenLayout) _setFrame:fromAdjustmentToScreen:anchorIfNeeded:animate:]
18  AppKit                          0x32724c488         -[NSWindow _adjustWindowToScreen]
19  AppKit                          0x32726bee4         -[NSWindow _displayChangedSoAdjustWindows:]
20  AppKit                          0x327df3874         ___NSApplicationPerformScreenInvalidationReactions_block_invoke
21  AppKit                          0x326f6b804         -[NSApplication enumerateWindowsWithOptions:usingBlock:]
22  AppKit                          0x327df3174         ___NSApplicationReactToScreenInvalidation_block_invoke
23  AppKit                          0x327df29b4         _NSApplicationReactToScreenInvalidation
24  AppKit                          0x327df2c00         -[NSApplication(ScreenHandling) _reactToDisplayChanges:]
25  AppKit                          0x3278a0818         _NSCGSDisplayConfigurationUpdateAndInvokeObservers
26  AppKit                          0x3278a0cfc         _NSCGSDisplayConfigurationDidReconfigureNotificationHandler
27  SkyLight                        0x32b01502c         (anonymous namespace)::notify_datagram_handler
28  SkyLight                        0x32b422d98         CGSDatagramReadStream::dispatchMainQueueDatagrams
29  SkyLight                        0x32b422c5c         CGSDatagramReadStream::mainQueueWakeup
30  libdispatch.dylib               0x31ec17b28         _dispatch_call_block_and_release
31  libdispatch.dylib               0x31ec31858         _dispatch_client_callout
32  libdispatch.dylib               0x31ec4eb54         _dispatch_main_queue_drain.cold.5
33  libdispatch.dylib               0x31ec26dac         _dispatch_main_queue_drain
34  libdispatch.dylib               0x31ec26ce8         _dispatch_main_queue_callback_4CF
35  CoreFoundation                  0x31f120da0         __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
36  CoreFoundation                  0x31f0e1a98         __CFRunLoopRun
37  CoreFoundation                  0x31f0e0c54         CFRunLoopRunSpecific
38  HIToolbox                       0x3365c1278         RunCurrentEventLoopInMode
39  HIToolbox                       0x3365c44e4         ReceiveNextEventCommon
```

### Actual Result

This is the stack I see:
```
Application Specific Information:
Signal 6, Code 0

Thread 0 Crashed:
0   libsystem_kernel.dylib          0x3031c7388         __pthread_kill
1   libsystem_pthread.dylib         0x30323c848         pthread_kill
2   libsystem_c.dylib               0x302fdc9e4         abort
3   MyApp                           0x200cfb22c         +[SentryCrashExceptionApplicationHelper _crashOnException:]
4   AppKit                          0x30b347128         __62+[CATransaction NS_setFlushesWithDisplayLink]_block_invoke
5   AppKit                          0x30bd90888         ___NSRunLoopObserverCreateWithHandler_block_invoke
6   CoreFoundation                  0x30339bed8         __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
7   CoreFoundation                  0x30339bdc0         __CFRunLoopDoObservers
8   CoreFoundation                  0x30339b430         __CFRunLoopRun
9   CoreFoundation                  0x30339aa98         CFRunLoopRunSpecific
10  HIToolbox                       0x31a89727c         RunCurrentEventLoopInMode
11  HIToolbox                       0x31a89a4e8         ReceiveNextEventCommon
12  HIToolbox                       0x31aa25484         _BlockUntilNextEventMatchingListInModeWithFilter
13  AppKit                          0x30b224a34         _DPSNextEvent
14  AppKit                          0x30bbc3940         -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
15  AppKit                          0x30b217be4         -[NSApplication run]
16  AppKit                          0x30b1ee2dc         NSApplicationMain
17  MyApp                           0x2001af644         main (main.swift:18)
18  dyld                            0x302afab98         <redacted>
```

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

Fix macOS NSException crash reports showing _crashOnException: in the stacktrace instead of the actual exception callstack.

- Replace async captureCrashOnException: with synchronous uncaughtExceptionHandler so the crash report is written before abort() terminates the process
- Swizzle both class and instance _crashOnException: to cover different macOS versions
- Deduplicate capture: reportException: internally calls _crashOnException: (when NSApplicationCrashOnExceptions is YES, which Sentry sets), so both paths now go through SentryNSExceptionCaptureHelper which ensures a single capture
- Remove no unused code: captureCrashOnException:, SentryUseNSExceptionCallstackWrapper

Fixes both the subclass approach (SentryCrashExceptionApplication) and the swizzle approach (enableUncaughtNSExceptionReporting).

Closes #6620

## :pencil: Checklist

You have to check all boxes before merging:

- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] I updated the wizard if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: Sources/Sentry/SentryCrashExceptionApplicationHelper.m [hunk 1]
```diff
@@ -19,14 +17,6 @@ + (void)reportException:(NSException *)exception
     }
 }
 
-+ (void)_crashOnException:(NSException *)exception
-{
-    [SentrySDKInternal captureCrashOnException:exception];
```
Comment (denrase) [inline Sources/Sentry/SentryCrashExceptionApplicationHelper.m:24]: This was introduced in #5306 and goes through our SDK path, where it eventually dispatches file write to a queue, which could have raced with `abort()`, so crash reports were not written.

I could not reproduce this though, as the runtime called the static `+[NSApplication _crashOnException:]` function instead of the instance once, both are present in the run-time.

Using `uncaughtExceptionHandler`, we write the report sync and don't have this issue.

@itaybre Do you know why we introduced `[SentrySDKInternal captureCrashOnException:]` instead of calling `uncaughtExceptionHandler`, i'm probably missing something important here.

Here is the [issue](https://denrase.sentry.io/issues/7287964162/?project=4508007036551168&query=&referrer=issue-stream) which was captured using the approach in this PR.

File: Sources/Sentry/SentrySDKInternal.m [hunk 2]
```diff
@@ -358,22 +357,6 @@ + (SentryId *)captureException:(NSException *)exception withScope:(SentryScope *
     return [SentrySDKInternal.currentHub captureException:exception withScope:scope];
 }
 
-#if TARGET_OS_OSX
-
-+ (SentryId *)captureCrashOnException:(NSException *)exception
-{
-    SentryUseNSExceptionCallstackWrapper *wrappedException =
```
Comment (denrase) [inline Sources/Sentry/SentrySDKInternal.m:365]: If we decide that this is the way to go, we could also remove `SentryUseNSExceptionCallstackWrapper`, as this is the only place it is used.

**Comment by denrase** [comment]
If calling the class function `+[NSApplication _crashOnException:]` is indeed the way to go for the runtime from here on out, only the swizzle approach will work correctly, as we can/should not override this class function in our custom subclass.

File: Sources/Sentry/SentryCrashExceptionApplication.m [hunk 3]
```diff
@@ -19,7 +25,12 @@ - (void)reportException:(NSException *)exception
 
 - (void)_crashOnException:(NSException *)exception
 {
-    [SentryCrashExceptionApplicationHelper _crashOnException:exception];
+    // AppKit calls -[NSApp _crashOnException:] on the application instance in some code paths
+    // (e.g., CATransaction flush). We capture the exception via the crash reporter's uncaught
+    // exception handler, which synchronously writes the crash report with the exception's original
+    // call stack before the process terminates.
+    [SentryCrashExceptionApplicationHelper reportException:exception];
+    [super _crashOnException:exception];
```
[the remark this answers is not in the document]
Comment (itaybre) [reply Sources/Sentry/SentryCrashExceptionApplication.m:30]: Worth taking a look on old macOS

File: Sources/Sentry/SentryCrashExceptionApplicationHelper.m (hunk 1 above)
Comment (itaybre) [reply Sources/Sentry/SentryCrashExceptionApplicationHelper.m:24]: This was probably a bug when introduced, this approach makes more sense.

When tested it worked fine, so I never noticed the queue being used.

File: Sources/Sentry/SentrySDKInternal.m (hunk 2 above)
Comment (itaybre) [reply Sources/Sentry/SentrySDKInternal.m:365]: Yes please!

File: Sources/Sentry/SentryNSExceptionCaptureHelper.m [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+
++ (void)crashOnException:(NSException *)exception
+{
+    // When called from within reportException: (i.e., [super reportException:] internally
+    // dispatches to _crashOnException: when NSApplicationCrashOnExceptions is YES),
+    // the exception was already captured, so skip to avoid duplicate reports.
+    if (!_insideReportException) {
+        [self captureException:exception];
+    }
+}
```
[the remark this answers is not in the document]
Comment (denrase) [reply Sources/Sentry/SentryNSExceptionCaptureHelper.m:32]: Incorrect usage when both are active.

File: Sources/Sentry/SentryNSExceptionCaptureHelper.m [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+
+@implementation SentryNSExceptionCaptureHelper
+
+static BOOL _insideReportException = NO;
+
++ (void)reportException:(NSException *)exception
+{
+    [self captureException:exception];
+    _insideReportException = YES;
+}
```
[the remark this answers is not in the document]
Comment (denrase) [reply Sources/Sentry/SentryNSExceptionCaptureHelper.m:17]: Incorrect usage to have both.

**Comment by denrase** [comment]
@itaybre I have added your feedback as well as the ones from the agents (de-duplication). Would you care to re-review this? I checked again with our sample app and AFAIK we do the correct thing now, you can double-check here: https://denrase.sentry.io/issues/7287964162/?project=4508007036551168&query=is%3Aunresolved&referrer=issue-stream thank you! 🙇

File: Sources/Sentry/SentryCrashExceptionApplication.m [hunk 6]
```diff
@@ -13,13 +19,15 @@ - (void)reportException:(NSException *)exception
...
     [super reportException:exception];
+    [SentryNSExceptionCaptureHelper reportExceptionDidFinish];
 }
 
 - (void)_crashOnException:(NSException *)exception
 {
-    [SentryCrashExceptionApplicationHelper _crashOnException:exception];
+    [SentryNSExceptionCaptureHelper crashOnException:exception];
+    [super _crashOnException:exception];
 }
```
[the remark this answers is not in the document]
Comment (denrase) [reply Sources/Sentry/SentryCrashExceptionApplication.m:31]: Not a valid use-case

File: Sources/Sentry/SentryNSExceptionCaptureHelper.m [hunk 7]
```diff
@@ -0,0 +1,45 @@
...
+#    import "SentrySwift.h"
+
+@implementation SentryNSExceptionCaptureHelper
+
+static BOOL _insideReportException = NO;
+
++ (void)reportException:(NSException *)exception
+{
+    [self captureException:exception];
+    _insideReportException = YES;
```
Comment (itaybre) [inline Sources/Sentry/SentryNSExceptionCaptureHelper.m:15]: `m`: Should we set `_insideReportException` first just in case?

File: CHANGELOG.md [hunk 8]
```diff
@@ -23,6 +23,7 @@
 
 - Preserve NSException and C++ exception reason instead of overwriting with unrelated `crash_info_message` from `libswiftCore.dylib` (#7515)
 - Fix unexpected null value when unwrapping view controller window (#7508)
+- Capture instance and class method `[NSApplication _crashOnException]` exceptions (#7510)
```
Comment (itaybre) [inline CHANGELOG.md]: `l`: You will have to move this to unreleased
