### PR TITLE
Fix and reenable testANRDetected_UpdatesAppStateToTrue

### LINKED ISSUE #2522: Fix flaky test testANRDetected_UpdatesAppStateToTrue
### Description

It's been disabled for a while now, but we had no issue yet to actually fix it.

### PR DESCRIPTION
**Pull request by kevinrenskers**
## :scroll: Description

- The test calls `SentryWatchdogTerminationTrackingIntegration.anrDetected`.
- This calls `self.appStateManager.updateAppState`, but that used the TestFileManager under the hood!
- `updateAppState` fails because `[self.fileManager readAppState]` returns `nil`.

Using the normal file manager fixes the test. 

#skip-changelog

## :bulb: Motivation and Context

Closes #2522

## :green_heart: How did you test it?

Unit test

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

**Comment by kevinrenskers** [comment]
My first idea was to have the test filemanager call the super's methods when reading the app state, but that broke some other tests. So now instead we simply use the real file manager again, done.

File: Sources/Sentry/SentryAppStateManager.m [hunk 1]
```diff
@@ -173,7 +173,7 @@ - (void)updateAppState:(void (^)(SentryAppState *))block
 {
     @synchronized(self) {
         SentryAppState *appState = [self.fileManager readAppState];
-        if (nil != appState) {
+        if (appState != nil) {
```
Comment (philipphofmann) [inline Sources/Sentry/SentryAppStateManager.m:176]: Like I do that, get rid of style Yoda. 😁

**Review by philipphofmann — APPROVED** [review]
LGTM
