### PR TITLE
fix: thread index check for crashed thread

### LINKED ISSUE #239: SentryKSCrashReportConverter Crashing
_Platform:_
- [x]  iOS

_Swift:_
- [x]  Yes -> 4

_sentry-cocoa installed with:_
- [x] CocoaPods

Version of sentry-cocoa:
  - Sentry/Core (3.12.2)
  - Sentry/KSCrash (3.12.2):
    - KSCrash/Core (~> 1.15.12)

---
I have following issue:
Fabric is reporting a decent number of crashes (over the past ~week).  This appears to be on app load, as none of our logging comes back for those crash instances in Fabric.
```
SentryKSCrashReportConverter.m line 208
-[SentryKSCrashReportConverter threadAtIndex:stripCrashedStacktrace:]
```

image

### PR DESCRIPTION
**Pull request by HazAT**
Fixes #239

### CODE REVIEW

File: Tests/SentryTests/SentryRequestTests.m [hunk 1]
```diff
@@ -76,9 +76,12 @@ @interface SentryMockNSURLSession: NSURLSession
 
 @implementation SentryMockNSURLSession
 
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wunused-parameter"
```
Comment (HazAT) [inline Tests/SentryTests/SentryRequestTests.m]: This only silicenes a compiler warning in the tests
