### PR TITLE
fix: sanitize span data

### LINKED ISSUE #1307: Sanitize data of Span when serializing it
The SDK doesn't sanitize the dict of data of SentrySpan when serializing it. Use [sentry_sanitize](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/NSDictionary+SentrySanitize.m) for it and add tests.

### PR DESCRIPTION
**Pull request by kevinrenskers**
## :scroll: Description

Sanitize span data when serializing.

## :bulb: Motivation and Context

Closes #1307

## :green_heart: How did you test it?

Unit tests

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

File: Sources/Sentry/SentrySpan.m [hunk 1]
```diff
@@ -130,15 +131,15 @@ - (NSDictionary *)serialize
...
+            mutableDictionary[@"data"] = [_data.copy sentry_sanitize];
         }
     }
 
     @synchronized(_tags) {
         if (_tags.count > 0) {
             NSMutableDictionary *tags = _context.tags.mutableCopy;
             [tags addEntriesFromDictionary:_tags.copy];
-            mutableDictionary[@"tags"] = tags;
+            mutableDictionary[@"tags"] = [tags sentry_sanitize];
```
Comment (kevinrenskers) [inline Sources/Sentry/SentrySpan.m:142]: Since it's impossible to set a tag other than a simple string, we probably don't need to call sentry_sanitize here, correct? I can remove it. It's also not possible to test this since I can't set a Date as a tag for example.

File: CHANGELOG.md [hunk 2]
```diff
@@ -10,6 +10,7 @@
 
 - Properly sanitize the event context and SDK information (#1943)
 - Don't send error 429 as `network_error` (#1957)
+- Sanitize SentrySpan data and tags (#1963)
```
Comment (philipphofmann) [inline CHANGELOG.md:13]:
```suggestion
- Sanitize Span data and tags (#1963)
```

File: Sources/Sentry/SentrySpan.m (hunk 1 above)
Comment (philipphofmann) [reply Sources/Sentry/SentrySpan.m:142]: Yep, please remove it.

**Review by philipphofmann — APPROVED** [review]
Please remove the sanitation for the tags. Then LGTM 🚀 and we can merge.

**Comment by kevinrenskers** [comment]
Uh, it has a changelog entry. Weird.
