### PR TITLE
fix: Return SentryNoOpSpan when starting a child on a finished transaction

### LINKED ISSUE #1624: Return NoOpSpan when starting a child on a finished transaction
### Problem Statement

Related to https://github.com/getsentry/sentry-java/issues/1840

### Solution Brainstorm

After calling finish, the transaction should return a NoOpSpan when starting a new child span, and log a message that the SDK is not sending the span to Sentry.

### PR DESCRIPTION
**Pull request by kevinrenskers**
## :scroll: Description

Return a SentryNoOpSpan when starting a child on a finished transaction, and log a warning.

## :bulb: Motivation and Context

Closes #1624.

## :green_heart: How did you test it?

Unit test.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

File: Sources/Sentry/SentrySpan.m [hunk 1]
```diff
@@ -33,12 +34,23 @@ - (instancetype)initWithTracer:(SentryTracer *)tracer context:(SentrySpanContext
 
 - (id<SentrySpan>)startChildWithOperation:(NSString *)operation
 {
+    if (self.isFinished) {
+        SENTRY_LOG_WARN(
+            @"Starting a child on a finished span is not supported; it won't be sent to Sentry.");
+        return [SentryNoOpSpan shared];
+    }
```
Comment (brustolin) [inline Sources/Sentry/SentrySpan.m:41]: m: I think we dont need this logic here since we have it in `startChildWithOperation:description:`

File: Tests/SentryTests/Transaction/SentrySpanTests.swift [hunk 2]
```diff
@@ -153,6 +159,18 @@ class SentrySpanTests: XCTestCase {
...
+    func testStartChildOnFinishedSpan() {
+        let span = fixture.getSut()
+        span.finish()
+
+        let childSpan = span.startChild(operation: fixture.someOperation, description: fixture.someDescription)
+
+        XCTAssertNil(childSpan.context.parentSpanId)
+        XCTAssertEqual(childSpan.context.operation, "")
+        XCTAssertNil(childSpan.context.spanDescription)
+        XCTAssertTrue(logOutput.loggedMessages.contains("Sentry - warning:: Starting a child on a finished span is not supported; it won\'t be sent to Sentry."))
```
Comment (philipphofmann) [inline Tests/SentryTests/Transaction/SentrySpanTests.swift:172]: 🥇 Thanks for testing the log message

File: Sources/Sentry/SentrySpan.m (hunk 1 above)
Comment (kevinrenskers) [reply Sources/Sentry/SentrySpan.m]: Ah of course, good point. Not sure why I missed that 😅

File: Tests/SentryTests/Transaction/SentrySpanTests.swift [hunk 3]
```diff
@@ -153,6 +159,18 @@ class SentrySpanTests: XCTestCase {
         XCTAssertEqual(childSpan.context.operation, fixture.someOperation)
         XCTAssertEqual(childSpan.context.spanDescription, fixture.someDescription)
     }
+
+    func testStartChildOnFinishedSpan() {
```
Comment (philipphofmann) [inline Tests/SentryTests/Transaction/SentrySpanTests.swift:163]: `m`: I think we should also add a test that this logic works for a grandchild. So basically, it should work as well when
```Swift
let span = fixture.getSut()
let childSpan = span.startChild(operation: fixture.someOperation)
childSpan.finish()
span.finish()
let grandChild = childSpan.startChild(operation: fixture.someOperation, description: fixture.someDescription)
```

File: Tests/SentryTests/Performance/SentryTracerTests.swift [hunk 4]
```diff
@@ -262,13 +262,14 @@ class SentryTracerTests: XCTestCase {
...
+        // The grandchild is a NoOp span
         let grandChild = child.startChild(operation: fixture.transactionOperation)
-        XCTAssertEqual(3, fixture.dispatchQueue.dispatchCancelInvocations.count)
+        XCTAssertEqual(2, fixture.dispatchQueue.dispatchCancelInvocations.count)
         
         grandChild.finish()
-        XCTAssertEqual(3, fixture.dispatchQueue.dispatchAfterInvocations.count)
-        XCTAssertEqual(4, fixture.dispatchQueue.dispatchCancelInvocations.count)
+        XCTAssertEqual(2, fixture.dispatchQueue.dispatchAfterInvocations.count)
+        XCTAssertEqual(2, fixture.dispatchQueue.dispatchCancelInvocations.count)
```
Comment (philipphofmann) [inline Tests/SentryTests/Performance/SentryTracerTests.swift:272]: `h`: Hmm, why do we have to change these? I think this should still work. You should still be able to create a child span on a finished span. You only should get a no op when the transaction is finished.

Sentry can handle this see https://sentry.io/organizations/sentry-sdks/discover/sentry-cocoa:60e32f111dbb4ad18dcf3327f56f5a8d/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=device&field=os&id=15529&name=Cocoa+Events&project=5428557&query=event.type%3Atransaction&sort=-timestamp&statsPeriod=24h&topEvents=5&yAxis=count%28%29
Screen Shot 2022-09-30 at 10 24 19

File: Sources/Sentry/SentrySpan.m [hunk 5]
```diff
@@ -39,6 +40,12 @@ - (instancetype)initWithTracer:(SentryTracer *)tracer context:(SentrySpanContext
 - (id<SentrySpan>)startChildWithOperation:(NSString *)operation
                               description:(nullable NSString *)description
 {
+    if (self.isFinished) {
```
Comment (philipphofmann) [inline Sources/Sentry/SentrySpan.m:43]: `h`: I think this should be the following, see comment in SentryTracerTest
```suggestion
    if (self.tracer.isFinished) {
```

**Review by philipphofmann — COMMENTED** [review]
The Span should only return a NoOp if the transaction is finished, not itself.

File: Tests/SentryTests/Performance/SentryTracerTests.swift (hunk 4 above)
Comment (kevinrenskers) [reply Tests/SentryTests/Performance/SentryTracerTests.swift]: Ok, that wasn't clear to me from the ticket. Changed.

**Comment by brustolin** [comment]
> The Span should only return a NoOp if the transaction is finished, not itself.

If this is the requirement, we only need to check this at SentryTracer, since is the only place we actually create the child.

**Review by brustolin — APPROVED** [review]
LGTM
