### PR TITLE
Convert SentryCrashIntegration to Swift

### LINKED ISSUE #7195: Convert SentryCrashIntegration to Swift
> [!NOTE]
> The pull request "[Convert SentryCrashIntegration to Swift](https://github.com/getsentry/sentry-cocoa/pull/7187)" was created by @itaybre but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

## :scroll: Description

Converts `SentryCrashIntegration` to Swift.
No user change: #skip-changelog

## :pencil: Checklist

You have to check all boxes before merging:

- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### PR DESCRIPTION
**Pull request by itaybre**
## :scroll: Description

Converts `SentryCrashIntegration` to Swift.
No user change: #skip-changelog

## :pencil: Checklist

You have to check all boxes before merging:

- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

Closes #7195

### CODE REVIEW

File: Sources/Sentry/include/SentryPrivate.h [hunk 1]
```diff
@@ -73,4 +80,7 @@
 #import "SentryTraceHeader.h"
 #import "SentryTraceOrigin.h"
 #import "SentryTraceProfiler.h"
+#if TARGET_OS_OSX
+#    import "SentryUncaughtNSExceptions.h"
+#endif
```
Comment (itaybre) [inline Sources/Sentry/include/SentryPrivate.h]:
```suggestion
#import "SentryUncaughtNSExceptions.h"
```

File: Sources/Swift/Core/Integrations/Integrations.swift [hunk 2]
```diff
@@ -35,8 +35,12 @@ private struct AnyIntegration {
     @objc public class func install(with options: Options) {
         let dependencies = SentryDependencyContainer.sharedInstance()
 
+        // The order of integrations here is important.
```
Comment (philprime) [inline Sources/Swift/Core/Integrations/Integrations.swift:39]: `l`: We might want to organize this in a tree structure at some point. This would also make sure we do not have circular dependencies. I would not do this in this PR but maybe a follow-up issue makes sense?

File: Sources/Swift/Integrations/SentryCrash/SentryCrashIntegration.swift [hunk 3]
```diff
@@ -0,0 +1,301 @@
...
+
+// MARK: - C Callback Function
+
+/// Global function to finish and save transaction when a crash occurs.
+/// This function is called from C crash reporting code.
+@_cdecl("sentry_finishAndSaveTransaction")
+public func sentry_finishAndSaveTransaction() {
+    let scope = SentrySDKInternal.currentHub().scope as Scope
+    guard let span = scope.getCastedInternalSpan() else {
+        return
```
Comment (philprime) [inline Sources/Swift/Integrations/SentryCrash/SentryCrashIntegration.swift:17]: `l`: Might be a good opportunity to add more sdk debug logs here

File: Sources/Swift/Integrations/SentryCrash/SentryCrashIntegration.swift [hunk 4]
```diff
@@ -0,0 +1,301 @@
...
+// MARK: - Dependency Provider
+
+/// Provides dependencies for `SentryCrashIntegration`.
+typealias CrashIntegrationProvider = DispatchQueueWrapperProvider & CrashWrapperProvider & SentryCrashReporterProvider & CrashIntegrationSessionHandlerBuilder
+
+// MARK: - Static State
+
+/// Static installation state shared across instances.
+/// SentryCrash installation is a one-time operation per app lifecycle.
+/// We could use just 2 vars here, but using an singleton should make it easier to integrate with Swift 6
```
Comment (philprime) [inline Sources/Swift/Integrations/SentryCrash/SentryCrashIntegration.swift]: `l`: Please explain why

File: Sources/Swift/Integrations/SentryCrash/SentryCrashIntegration.swift [hunk 5]
```diff
@@ -0,0 +1,301 @@
...
+    private func initializeCrashHandler(
+        cacheDirectory: String,
+        enableSigtermReporting: Bool,
+        enableReportingUncaughtExceptions: Bool,
+        enableCppExceptionsV2: Bool
+    ) {
+        var canSendReports = false
+
+        if CrashInstallationState.shared.installation == nil {
+            guard let options = self.options else { return }
```
Comment (philprime) [inline Sources/Swift/Integrations/SentryCrash/SentryCrashIntegration.swift]: `l`: The early exit should contain debug logs

File: Sources/Swift/Integrations/SentryCrash/SentryCrashIntegration.swift [hunk 6]
```diff
@@ -0,0 +1,301 @@
...
+
+            let inAppLogic = SentryInAppLogic(inAppIncludes: options.inAppIncludes)
+
+            let installation = SentryCrashInstallationReporter(
+                inAppLogic: inAppLogic,
+                crashWrapper: self.crashWrapper,
+                dispatchQueue: self.dispatchQueueWrapper
+            )
+
+            CrashInstallationState.shared.installation = installation
```
Comment (philprime) [inline Sources/Swift/Integrations/SentryCrash/SentryCrashIntegration.swift]: `h`: I read the comments above that the crash integration is a singleton, but couldn't we delegate this to the SentryDependencyContainer instead so that this integration is not a singleton? That would make unit testing easier, especially when working with mocks which do not need to be singletons.

Comment (itaybre) [reply Sources/Swift/Integrations/SentryCrash/SentryCrashIntegration.swift]: Far enough, moving it

File: Sources/Swift/Integrations/SentryCrash/SentryCrashIntegration.swift (hunk 4 above)
Comment (itaybre) [reply Sources/Swift/Integrations/SentryCrash/SentryCrashIntegration.swift]: Made some additional test an analysis, and seems like we do not need the static state.
With locks, everything seems to be working

File: Sources/Swift/Integrations/SentryCrash/SentryCrashIntegration.swift [hunk 7]
```diff
@@ -0,0 +1,246 @@
...
+
+        super.init()
+
+        self.sessionHandler = dependencies.getCrashIntegrationSessionBuilder(options)
+        self.scopeObserver = SentryCrashScopeObserver(maxBreadcrumbs: Int(options.maxBreadcrumbs))
+
+        guard self.sessionHandler != nil, self.scopeObserver != nil else {
+            SentrySDKLog.warning("Failed to initialize SentryCrashIntegration dependencies")
+            return nil
+        }
```
[the remark this answers is not in the document]
Comment (itaybre) [reply Sources/Swift/Integrations/SentryCrash/SentryCrashIntegration.swift:57]: If `fileManager` is nil, so the session handler and the integration won't install.
False alert

File: Sources/Swift/Integrations/SentryCrash/SentryCrashIntegrationSessionHandler.swift [hunk 8]
```diff
@@ -0,0 +1,86 @@
...
+        guard let session = fileManager.readCurrentSession() else {
+            SentrySDKLog.debug("No current session found to end.")
+            return
+        }
+
+        #if (os(iOS) || os(tvOS) || os(visionOS)) && !SENTRY_NO_UIKIT
+        let shouldEndAsCrashed = crashWrapper.crashedLastLaunch || watchdogTerminationLogic.isWatchdogTermination()
+        #else
+        let shouldEndAsCrashed = crashWrapper.crashedLastLaunch
+        #endif
```
[the remark this answers is not in the document]
Comment (itaybre) [reply Sources/Swift/Integrations/SentryCrash/SentryCrashIntegrationSessionHandler.swift:55]: `os(iOS)` is true for macCatalyst

File: Sources/Swift/Core/Integrations/Integrations.swift (hunk 2 above)
Comment (itaybre) [reply Sources/Swift/Core/Integrations/Integrations.swift:39]: Created: https://github.com/getsentry/sentry-cocoa/issues/7202
