### PR TITLE
fix: SentryAppStateManager should always stop when closing the SDK

### LINKED ISSUE #2455: AppStateManager doesn't unsubscribe correctly
### Platform

iOS

### Installed

Manually

### Version

7.31.2

### Steps to Reproduce

1. Call SentrySDK.start two times
2. Call SentrySDK.close

### Expected Result

SentryAppStateManager should unsubscribe from notifications here
https://github.com/getsentry/sentry-cocoa/blob/907d2ce340b8295d7debd3371a94e5fd1d720ffe/Sources/Sentry/SentryAppStateManager.m#L95-L98

### Actual Result

SentryAppStateManager doesn't unsubscribe from notifications cause startCount is bigger than 0 https://github.com/getsentry/sentry-cocoa/blob/907d2ce340b8295d7debd3371a94e5fd1d720ffe/Sources/Sentry/SentryAppStateManager.m#L95

### PR DESCRIPTION
**Pull request by kevinrenskers**
## :scroll: Description

Force stop the `SentryAppStateManager` when calling `SentrySDK.close()`, even if you started the SDK multiple times. 

## :bulb: Motivation and Context

Closes #2455

## :green_heart: How did you test it?

Multiple unit tests. We have a test for `SentryAppStateManager` that tests the actual unsubscribing of the notification center, and an integration test that starts the SDK twice, stops it, and checks the start count of the `SentryAppStateManager`, which should now be zero. This test doesn't explicitly test the notification center unsubscribing as I can't really pass the mock center here. But we know that if the start count hits zero, that we do unsubscribe, that's what the first test checks.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

**Comment by kevinrenskers** [comment]
```
Testing failed:
	No visible @interface for 'SentryAppStateManager' declares the selector 'stop:'
	Testing cancelled because the build failed.
```

Wait, what? I've definitely added it to `SentryAppStateManager.h`, and locally it compiles just fine.

File: Sources/Sentry/include/SentryAppStateManager.h [hunk 1]
```diff
@@ -2,24 +2,28 @@
...
                          sysctl:(SentrySysctl *)sysctl
-           dispatchQueueWrapper:(SentryDispatchQueueWrapper *)dispatchQueueWrapper;
+           dispatchQueueWrapper:(SentryDispatchQueueWrapper *)dispatchQueueWrapper
+      notificationCenterWrapper:(SentryNSNotificationCenterWrapper *)notificationCenterWrapper;
 
 #if SENTRY_HAS_UIKIT
 
 - (void)start;
 - (void)stop;
+- (void)stop:(BOOL)forceStop;
```
Comment (armcknight) [inline Sources/Sentry/include/SentryAppStateManager.h:26]: Could you include a doc comment or rename this so that `stop:NO`/`stop:YES` is more obvious what it's doing at callsites?

File: Sources/Sentry/SentryAppStateManager.m [hunk 2]
```diff
@@ -85,43 +84,48 @@ - (void)start
...
 {
     if (self.startCount <= 0) {
         return;
     }
 
-    self.startCount -= 1;
+    if (forceStop) {
+        self.startCount = 0;
+    } else {
+        self.startCount -= 1;
```
Comment (armcknight) [inline Sources/Sentry/SentryAppStateManager.m:100]: So if `forceStop` is not `YES`, then we require developers to correctly balance calls to start/stop? Why can't we just always reset `startCount` to 0?

**Review by armcknight — APPROVED** [review]
Just a question and suggestion but overall LGTM 👍🏻

File: Sources/Sentry/SentryAppStateManager.m (hunk 2 above)
Comment (kevinrenskers) [reply Sources/Sentry/SentryAppStateManager.m:100]: There are 2 integrations that start this manager. And only if both are stopped, should this manager be stopped as well. The only exception is if the entire SDK is closed, (which doesn't call the stop method on every integration). So then we force this to be stopped.

But yeah normally they have to be balanced.

File: Sources/Sentry/include/SentryAppStateManager.h (hunk 1 above)
Comment (kevinrenskers) [reply Sources/Sentry/include/SentryAppStateManager.h]: Done
