### PR TITLE
fix: Resolve broken pipes in make generate-public-api

### LINKED ISSUE #7060: fix: Resolve broken pipes in make generate-public-api
> [!NOTE]
> The pull request "[fix: Resolve broken pipes in make generate-public-api](https://github.com/getsentry/sentry-cocoa/pull/7059)" was created by @philprime but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

Fixes error 141 (SIGPIPE) that occurred when parsing xcodebuild version output with `set -euo pipefail` enabled. The issue happened because piping xcodebuild output directly to awk caused a broken pipe when awk exited early.

Changes:
- Read full xcodebuild output into a variable before parsing to avoid broken pipe
- Remove verbose tracing flag (`-x`) from set command
- Add progress echo statements for better visibility during script execution

This ensures the script runs successfully when Xcode 26 is selected and automatically switches to Xcode 16 for API generation.

#skip-changelog

### PR DESCRIPTION
**Pull request by philprime**
Fixes error 141 (SIGPIPE) that occurred when parsing xcodebuild version output with `set -euo pipefail` enabled. The issue happened because piping xcodebuild output directly to awk caused a broken pipe when awk exited early:

```
$ make generate-public-api
./scripts/update-api.sh
make: *** [generate-public-api] Error 141

$ make generate-public-api
./scripts/update-api.sh
Xcode 26.1.1 is currently selected, but found Xcode 16 at /Applications/Xcode-16.4.0.app
Using Xcode 16 for this script execution...
make: *** [generate-public-api] Error 141
```

Changes:
- Read full xcodebuild output into a variable before parsing to avoid broken pipe
- Remove verbose tracing flag (`-x`) from set command
- Add progress echo statements for better visibility during script execution

This ensures the script runs successfully when Xcode 26 is selected and automatically switches to Xcode 16 for API generation.

#skip-changelog

Closes #7060

### CODE REVIEW

File: scripts/update-api.sh [hunk 1]
```diff
@@ -2,7 +2,9 @@
 set -euo pipefail
 
 # Check if Xcode 16 is selected
-XCODE_VERSION=$(xcodebuild -version | head -n 1 | awk '{print $2}')
+# Read full output first to avoid broken pipe (SIGPIPE) error with pipefail
+XCODE_VERSION_OUTPUT=$(xcodebuild -version 2>&1)
```
Comment (philprime) [inline scripts/update-api.sh]:
```suggestion
XCODE_VERSION_OUTPUT=$(xcodebuild -version)
```

File: scripts/update-api.sh [hunk 2]
```diff
@@ -15,7 +17,9 @@ if [[ "$XCODE_MAJOR_VERSION" != "16" ]]; then
         export DEVELOPER_DIR="$XCODE_16_PATH/Contents/Developer"
         
         # Verify the Xcode 16 installation works
-        XCODE_16_VERSION=$(xcodebuild -version | head -n 1 | awk '{print $2}')
+        # Read full output first to avoid broken pipe (SIGPIPE) error with pipefail
+        XCODE_16_VERSION_OUTPUT=$(xcodebuild -version 2>&1)
```
Comment (philprime) [inline scripts/update-api.sh]:
```suggestion
        XCODE_16_VERSION_OUTPUT=$(xcodebuild -version)
```

File: scripts/update-api.sh [hunk 3]
```diff
@@ -32,14 +36,18 @@ if [[ "$XCODE_MAJOR_VERSION" != "16" ]]; then
     fi
 fi
 
+echo "Building Sentry-Dynamic slice"
```
Comment (philippsuess) [inline scripts/update-api.sh]: `l`: Maybe worth using the log methods from `ci-utils.sh`?
