### PR TITLE
fix: Respect existing baggage header instead of overwriting it

### LINKED ISSUE #1911: Respect already existing baggage header on outgoing http requests
### Description

Preparing for Dynamic Sampling we added the baggage header to outgoing http requests. 
Since this is an open protocol, other products may also use this header and we should not replace it.

If the header already exists we should just append sentry specific items.

### PR DESCRIPTION
**Pull request by kevinrenskers**
## :scroll: Description

`SentryNetworkTracker` adds a baggage header with some sentry keys and values, but it does so by completely overwriting any possibly existing baggage header. And when we remove the baggage header when `SentrySDK.currentHub.scope.span` is `nil`, we also do that by removing the entire baggage header instead of only the `sentry-trace_id` key that we actually need to remove.

Now we respect the existing baggage header, if it's there, by modifying it.

## :bulb: Motivation and Context

Closes #1911

## :green_heart: How did you test it?

Unit tests.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

File: Sources/Sentry/SentryBaggage.m [hunk 1]
```diff
@@ -32,9 +32,16 @@ - (instancetype)initWithTraceId:(SentryId *)traceId
...
-    NSMutableDictionary *information =
-        @{ @"sentry-trace_id" : _traceId.sentryIdString, @"sentry-public_key" : _publicKey }
-            .mutableCopy;
+    return [self toHTTPHeaderWithOriginalBaggage:nil];
+}
+
+- (NSString *)toHTTPHeaderWithOriginalBaggage:(NSDictionary *_Nullable)originalBaggage
+{
+    NSMutableDictionary *information
+        = originalBaggage.mutableCopy ?: [[NSMutableDictionary alloc] init];
```
Comment (brustolin) [inline Sources/Sentry/SentryBaggage.m:41]: I never thought of using Elvis operator with objc. Nice!!

File: Sources/Sentry/SentryNetworkTracker.m [hunk 2]
```diff
@@ -274,6 +275,13 @@ - (SentrySpanStatus)spanStatusForHttpResponseStatusCode:(NSInteger)statusCode
     return kSentrySpanStatusUndefined;
 }
 
+- (NSString *)removeSentryTraceIdFromBaggage:(NSString *)baggage
+{
+    NSMutableDictionary *original = [SentrySerialization decodeBaggage:baggage].mutableCopy;
+    [original removeObjectForKey:@"sentry-trace_id"];
+    return [SentrySerialization baggageEncodedDictionary:original];
```
Comment (brustolin) [inline Sources/Sentry/SentryNetworkTracker.m:282]: We should remove every sentry item from the baggage, not only the trace_id.

Comment (kevinrenskers) [reply Sources/Sentry/SentryNetworkTracker.m:282]: I wasn't sure if that was necessary and in the end I thought not. After all we're sending this to Sentry, and apart from the trace id it all seems safe to send?

Can you explain why we should remove all of them?

Comment (brustolin) [reply Sources/Sentry/SentryNetworkTracker.m:282]: Just to play nice with the app. We shouldn't send any byte that is not necessary.

Comment (kevinrenskers) [reply Sources/Sentry/SentryNetworkTracker.m]: Done

**Comment by kevinrenskers** [comment]
The only test that keeps failing is the "UI Tests on iOS 12 Simulator" one, with the usual "Failed to get matching snapshots: Timed out while evaluating UI query". But I haven't touched the UI in this PR at all, so that's weird. I'll download the iOS 12 simulator on my computer, see if I can spot the problem.

**Comment by kevinrenskers** [comment]
Sample app looks like this in iOS 12 🙈

Simulator Screen Shot - iPhone 8 - 2022-07-22 at 12 41 09

Fixed it.

**Comment by kevinrenskers** [comment]
`testSplitView` keeps failing locally. This is how it looks like on iOS 12 vs iOS 15:

 

I'm also getting literally endless errors in the console in iOS 12 on the split view:

```
Sentry - debug:: Failed to get pthread handle for mach thread 5123
Sentry - error:: thread_suspend(handle_) failed with kern return code: 268435459, description: Unknown error.
```

The exact same thing runs fine from iOS 13 and up though, without these errors.

Anybody got an idea on how to fix this?

**Comment by kevinrenskers** [comment]
It might have started with https://github.com/getsentry/sentry-cocoa/pull/1978?

I'll create a new issue to fix the UI test in iOS 12, I don't think it should block this PR.

**Comment by kevinrenskers** [comment]
We have one failing UI test on iOS 12, which is unrelated to this PR and has started happening a while ago. I created a separate issue for this (https://github.com/getsentry/sentry-cocoa/issues/2000), I don't think it should block this PR.

**Review by brustolin — APPROVED** [review]
LGTM

**Review by brustolin — APPROVED** [review]
LGTM
