### PR TITLE
fix: dont call through to NSLog from profiler sampling thread

### LINKED ISSUE #3336: -[SentryLogOutput log:] SIGTRAP
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.13.0

### Steps to Reproduce

<details><summary>Crash Report</summary>
<p>

```
Crashlytics - Stack trace
Application: com.weo.projectz
Platform: apple
Version: 1.4.2 (2)
Issue: d3e019da21d973d44bb486bf75a439c6
Session: cf1fff15e1254a0ebc6304b9f718a4d1_DNE_0_v2
Date: Sun Oct 08 2023 16:30:22 GMT+0800 (中国标准时间)

Crashed: com.apple.main-thread
0  libsystem_platform.dylib       0x6244 _os_unfair_lock_corruption_abort + 52
1  libsystem_platform.dylib       0x102c _os_unfair_lock_lock_slow + 300
2  CoreFoundation                 0xeb648 _logToStderr + 148
3  CoreFoundation                 0x166500 __CFLogCString + 84
4  CoreFoundation                 0x94c8c _CFLogvEx2Predicate + 344
5  CoreFoundation                 0xa3548 _CFLogvEx3 + 252
6  Foundation                     0xa45c0 _NSLogv + 124
7  Foundation                     0xa2f58 NSLog + 56
8  Sentry                         0x4b774 -[SentryLogOutput log:] + 10 (SentryLogOutput.m:10)
9  Sentry                         0x4b6d4 +[SentryLog logWithMessage:andLevel:] + 29 (SentryLog.m:29)
10 Sentry                         0x604ec -[SentryProfiler stopForReason:] + 489 (SentryProfiler.mm:489)
11 CoreFoundation                 0x37590 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
12 CoreFoundation                 0xdb828 ___CFXRegistrationPost_block_invoke + 88
13 CoreFoundation                 0xbe8b8 _CFXRegistrationPost + 440
14 CoreFoundation                 0x4bafc _CFXNotificationPost + 700
15 Foundation                     0x5cd18 -[NSNotificationCenter postNotificationName:object:userInfo:] + 92
16 UIKitCore                      0x28d8e8 -[UIApplication _deactivateForReason:notify:] + 1216
17 UIKitCore                      0x28bc30 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 176
18 UIKitCore                      0x28ba84 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 620
19 UIKitCore                      0x28b634 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 252
20 UIKitCore                      0x28b500 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 148
21 UIKitCore                      0x978a68 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:] + 736
22 UIKitCore                      0xa17074 _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion + 224
23 UIKitCore                      0x138c70 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 316
24 UIKitCore                      0x5aa1ac __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.223 + 556
25 UIKitCore                      0x209c60 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 216
26 UIKitCore                      0x209ad0 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 244
27 UIKitCore                      0x209910 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 336
28 FrontBoardServices             0x3ac8 -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:] + 420
29 FrontBoardServices             0x3904 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2 + 152
30 FrontBoardServices             0x7120 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 168
31 FrontBoardServices             0x703c __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke + 344
32 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
33 libdispatch.dylib              0x791c _dispatch_block_invoke_direct + 264
34 FrontBoardServices             0x1124c __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 52
35 FrontBoardServices             0x10de8 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 220
36 FrontBoardServices             0x13694 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
37 CoreFoundation                 0xd3128 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
38 CoreFoundation                 0xdf7b4 __CFRunLoopDoSource0 + 176
39 CoreFoundation                 0x64648 __CFRunLoopDoSources0 + 340
40 CoreFoundation                 0x7a0d4 __CFRunLoopRun + 828
41 CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
42 GraphicsServices               0x135c GSEventRunModal + 164
43 UIKitCore                      0x39cf58 -[UIApplication _run] + 888
44 UIKitCore                      0x39cbbc UIApplicationMain + 340
45 libswiftUIKit.dylib            0x350b0 UIApplicationMain(_:_:_:_:) + 104
46 JACO                           0x509e8 main + 4297574888 (UIConst.swift:4297574888)
47 ???                            0x1e11ecdec (缺少)

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
7  Foundation                     0x41fb4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0x41e9c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x4cfcc8 -[UIEventFetcher threadMain] + 416
10 Foundation                     0x5b524 __NSThread__start__ + 716
11 libsystem_pthread.dylib        0x16b8 _pthread_start + 148
12 libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  libc++.1.dylib                 0x12f8c std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  ZegoExpressEngine              0x67d0c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
4  ZegoExpressEngine              0x67c34 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
5  ZegoExpressEngine              0x67bd0 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
6  ZegoExpressEngine              0x67b6c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
7  ZegoExpressEngine              0x66e50 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
8  ZegoExpressEngine              0x66d2c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
9  ZegoExpressEngine              0x66cfc (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
10 ZegoExpressEngine              0x67370 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
11 libsystem_pthread.dylib        0x16b8 _pthread_start + 148
12 libsystem_pthread.dylib        0xb88 thread_start + 8

mt
0  libsystem_kernel.dylib         0x4390 poll + 8
1  ZegoExpressEngine              0x5bd60 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
2  ZegoExpressEngine              0x5f4f0 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
3  ZegoExpressEngine              0x5f298 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
4  ZegoExpressEngine              0x56e3c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  FirebaseCrashlytics            0x17d38 FIRCLSMachExceptionServer + 192 (FIRCLSMachException.c:192)
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1164 __semwait_signal + 8
1  libsystem_c.dylib              0x5888 nanosleep + 220
2  libsystem_c.dylib              0x16b1c sleep + 52
3  ZegoExpressEngine              0x30b8cc (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

ZEGO Exception Handler (Secondary)
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0xd884 thread_suspend + 112
3  ZegoExpressEngine              0x31087c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

ZEGO Exception Handler (Primary)
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13c0c mach_msg2_internal + 232
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  ZegoExpressEngine              0x3108a4 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

tmon
0  libsystem_kernel.dylib         0x4390 poll + 8
1  ZegoExpressEngine              0x5bd60 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
2  ZegoExpressEngine              0x5f4f0 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
3  ZegoExpressEngine              0x5f298 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
4  ZegoExpressEngine              0x56e3c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1164 __semwait_signal + 8
1  libsystem_c.dylib              0x5888 nanosleep + 220
2  libsystem_c.dylib              0x16b1c sleep + 52
3  Sentry                         0x19b9c monitorCachedData + 145 (SentryCrashCachedData.c:145)
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

SentryCrash Exception Handler (Secondary)
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  Sentry                         0x25e30 handleExceptions + 316 (SentryCrashMonitor_MachException.c:316)
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

io.sentry.app-hang-tracker
0  libsystem_kernel.dylib         0x1164 __semwait_signal + 8
1  libsystem_c.dylib              0x5888 nanosleep + 220
2  Foundation                     0xb27ac +[NSThread sleepForTimeInterval:] + 160
3  Sentry                         0x9054 -[SentryANRTracker detectANRs] + 103 (SentryANRTracker.m:103)
4  Foundation                     0x5b524 __NSThread__start__ + 716
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
7  CFNetwork                      0x2586f0 _CFURLStorageSessionDisableCache + 60900
8  Foundation                     0x5b524 __NSThread__start__ + 716
9  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
10 libsystem_pthread.dylib        0xb88 thread_start + 8

timer-mon
0  libsystem_kernel.dylib         0x4390 poll + 8
1  ZegoExpressEngine              0x5bd60 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
2  ZegoExpressEngine              0x5f4f0 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
3  ZegoExpressEngine              0x5f298 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
4  ZegoExpressEngine              0x56e3c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

hc
0  libsystem_kernel.dylib         0x4390 poll + 8
1  ZegoExpressEngine              0x5bd60 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
2  ZegoExpressEngine              0x5f4f0 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
3  ZegoExpressEngine              0x5f298 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
4  ZegoExpressEngine              0x56e3c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

net
0  libsystem_kernel.dylib         0x4390 poll + 8
1  ZegoExpressEngine              0x5bd60 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
2  ZegoExpressEngine              0x5f4f0 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
3  ZegoExpressEngine              0x5f298 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
4  ZegoExpressEngine              0x56e3c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

dc
0  libsystem_kernel.dylib         0x4390 poll + 8
1  ZegoExpressEngine              0x5bd60 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
2  ZegoExpressEngine              0x5f4f0 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
3  ZegoExpressEngine              0x5f298 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
4  ZegoExpressEngine              0x56e3c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

zr
0  libsystem_kernel.dylib         0x4390 poll + 8
1  ZegoExpressEngine              0x5bd60 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
2  ZegoExpressEngine              0x5f4f0 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
3  ZegoExpressEngine              0x5f298 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
4  ZegoExpressEngine              0x56e3c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

ag
0  libsystem_kernel.dylib         0x4390 poll + 8
1  ZegoExpressEngine              0x5bd60 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
2  ZegoExpressEngine              0x5f4f0 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
3  ZegoExpressEngine              0x5f298 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
4  ZegoExpressEngine              0x56e3c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x4390 poll + 8
1  ZegoExpressEngine              0x7d616c zego_register_ai_voice_changer_get_speaker_list_callback + 3971976
2  ZegoExpressEngine              0x7d5168 zego_register_ai_voice_changer_get_speaker_list_callback + 3967876
3  ZegoExpressEngine              0x940ddc zego_register_ai_voice_changer_get_speaker_list_callback + 5457912
4  ZegoExpressEngine              0x940c94 zego_register_ai_voice_changer_get_speaker_list_callback + 5457584
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x1808 select$DARWIN_EXTSN + 8
1  libsystem_kernel.dylib         0x1808 __select + 8
2  CoreFoundation                 0xc899c __CFSocketManager + 636
3  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
4  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread_RcpsClientImpl 0x0x11741c2c0
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  RongIMLibCore                  0x2151c4 rcrtc::Event::Wait(int) + 180
3  RongIMLibCore                  0x221410 rcrtc::NullSocketServer::Wait(int, bool) + 16
4  RongIMLibCore                  0x21fcf4 rcrtc::MessageQueue::Get(rcrtc::Message*, int, bool) + 964
5  RongIMLibCore                  0x235eb8 rcrtc::Thread::ProcessMessages(int) + 132
6  RongIMLibCore                  0x235ccc rcrtc::Thread::PreRun(void*) + 112
7  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
8  libsystem_pthread.dylib        0xb88 thread_start + 8

thread_log
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  RongIMLibCore                  0x2151c4 rcrtc::Event::Wait(int) + 180
3  RongIMLibCore                  0x221410 rcrtc::NullSocketServer::Wait(int, bool) + 16
4  RongIMLibCore                  0x21fcf4 rcrtc::MessageQueue::Get(rcrtc::Message*, int, bool) + 964
5  RongIMLibCore                  0x235eb8 rcrtc::Thread::ProcessMessages(int) + 132
6  RongIMLibCore                  0x235ccc rcrtc::Thread::PreRun(void*) + 112
7  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
8  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  libc++.1.dylib                 0x12f8c std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  ZegoExpressEngine              0x67d0c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
4  ZegoExpressEngine              0x67c34 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
5  ZegoExpressEngine              0x67bd0 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
6  ZegoExpressEngine              0x16f53c (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
7  ZegoExpressEngine              0x16d870 (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
8  ZegoExpressEngine              0x16f3dc (缺少 UUID 2acd569ed2913d3987defd1a4f728c69)
9  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
10 libsystem_pthread.dylib        0xb88 thread_start + 8

ADeviceProxy_00
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  ZegoExpressEngine              0x4de758 zego_register_ai_voice_changer_get_speaker_list_callback + 860532
3  ZegoExpressEngine              0x4de8a8 zego_register_ai_voice_changer_get_speaker_list_callback + 860868
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

CTimer
0  libsystem_kernel.dylib         0xc38 semaphore_timedwait_trap + 8
1  ZegoExpressEngine              0x50a32c zego_register_ai_voice_changer_get_speaker_list_callback + 1039688
2  ZegoExpressEngine              0x50b930 zego_register_ai_voice_changer_get_speaker_list_callback + 1045324
3  ZegoExpressEngine              0x50a2a8 zego_register_ai_voice_changer_get_speaker_list_callback + 1039556
4  ZegoExpressEngine              0x50a134 zego_register_ai_voice_changer_get_speaker_list_callback + 1039184
5  ZegoExpressEngine              0x50a21c zego_register_ai_voice_changer_get_speaker_list_callback + 1039416
6  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
7  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
7  Foundation                     0x41fb4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0x41e48 -[NSRunLoop(NSRunLoop) run] + 64
9  ZegoExpressEngine              0x5a4aac zego_register_ai_voice_changer_get_speaker_list_callback + 1672392
10 Foundation                     0x5b524 __NSThread__start__ + 716
11 libsystem_pthread.dylib        0x16b8 _pthread_start + 148
12 libsystem_pthread.dylib        0xb88 thread_start + 8

com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
7  CoreFoundation                 0xc1ea4 CFRunLoopRun + 64
8  CoreMotion                     0x131a8 CLMotionActivity::isTypeInVehicle(CLMotionActivity::Type) + 23160
9  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
10 libsystem_pthread.dylib        0xb88 thread_start + 8

AURemoteIO::IOThread
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  libEmbeddedSystemAUs.dylib     0xa8148 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, AURemoteIO::IOThread::IOThread(AURemoteIO&, caulk::thread::attributes const&, caulk::mach::os_workgroup_managed const&)::'lambda'(), std::__1::tuple<> > >(void*)
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

 *1707667
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  RongIMLibCore                  0x453e44 rc_mars::comm::Condition::wait(rc_mars::comm::BaseScopedLock<rc_mars::comm::Mutex>&, long) + 344
3  RongIMLibCore                  0x44f60c rc_mars::xlog::XloggerAppender::__AsyncLogThread() + 372
4  RongIMLibCore                  0x453c40 rc_mars::comm::Thread::start_routine(void*) + 76
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread_RmtpSocket 0x0x10aa9ae00
0  libsystem_kernel.dylib         0x25dc kevent + 8
1  RongIMLibCore                  0x226a54 rcrtc::PhysicalSocketServer::WaitKevent(int) + 232
2  RongIMLibCore                  0x21fcf4 rcrtc::MessageQueue::Get(rcrtc::Message*, int, bool) + 964
3  RongIMLibCore                  0x235eb8 rcrtc::Thread::ProcessMessages(int) + 132
4  RongIMLibCore                  0x235ccc rcrtc::Thread::PreRun(void*) + 112
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

flv-play-tcp
0  ZegoExpressEngine              0x82717c zego_register_ai_voice_changer_get_speaker_list_callback + 4303768
1  ZegoExpressEngine              0x837508 zego_register_ai_voice_changer_get_speaker_list_callback + 4370212
2  ZegoExpressEngine              0x7df52c zego_register_ai_voice_changer_get_speaker_list_callback + 4009800
3  ZegoExpressEngine              0x838754 zego_register_ai_voice_changer_get_speaker_list_callback + 4374896
4  ZegoExpressEngine              0x4587a8 zego_register_ai_voice_changer_get_speaker_list_callback + 311748
5  ZegoExpressEngine              0x50f7e8 zego_register_ai_voice_changer_get_speaker_list_callback + 1061380
6  ZegoExpressEngine              0x512f1c zego_register_ai_voice_changer_get_speaker_list_callback + 1075512
7  ZegoExpressEngine              0x513194 zego_register_ai_voice_changer_get_speaker_list_callback + 1076144
8  ZegoExpressEngine              0x51260c zego_register_ai_voice_changer_get_speaker_list_callback + 1073192
9  ZegoExpressEngine              0x5309dc zego_register_ai_voice_changer_get_speaker_list_callback + 1197048
10 ZegoExpressEngine              0x4ebbac zego_register_ai_voice_changer_get_speaker_list_callback + 914888
11 ZegoExpressEngine              0x4ecfe0 zego_register_ai_voice_changer_get_speaker_list_callback + 920060
12 ZegoExpressEngine              0x498930 zego_register_ai_voice_changer_get_speaker_list_callback + 574284
13 ZegoExpressEngine              0x497adc zego_register_ai_voice_changer_get_speaker_list_callback + 570616
14 ZegoExpressEngine              0x50a2a8 zego_register_ai_voice_changer_get_speaker_list_callback + 1039556
15 ZegoExpressEngine              0x50a134 zego_register_ai_voice_changer_get_speaker_list_callback + 1039184
16 ZegoExpressEngine              0x50a21c zego_register_ai_voice_changer_get_speaker_list_callback + 1039416
17 libsystem_pthread.dylib        0x16b8 _pthread_start + 148
18 libsystem_pthread.dylib        0xb88 thread_start + 8

APMIdentityWorkerQueue
0  libsystem_kernel.dylib         0x17dc __ulock_wait + 8
1  libdispatch.dylib              0x489c _dlock_wait + 56
2  libdispatch.dylib              0x4598 _dispatch_wait_on_address + 140
3  libdispatch.dylib              0x4c4c _dispatch_group_wait_slow + 56
4  libdispatch.dylib              0x7e38 dispatch_block_wait + 284
5  JACO                           0x182cd94 -[APMDefaultIdentitySupport resettableDeviceID] + 533748
6  JACO                           0x183e2ec __32-[APMIdentity updateIdentifiers]_block_invoke + 604748
7  libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
8  libdispatch.dylib              0x3eac _dispatch_client_callout + 20
9  libdispatch.dylib              0xb534 _dispatch_lane_serial_drain + 668
10 libdispatch.dylib              0xc0a4 _dispatch_lane_invoke + 384
11 libdispatch.dylib              0x16cdc _dispatch_workloop_worker_thread + 648
12 libsystem_pthread.dylib        0xddc _pthread_wqthread + 288
13 libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

com.google.fira.worker
0  libsystem_kernel.dylib         0x11fc kevent_id + 8
1  libdispatch.dylib              0x26e58 _dispatch_kq_poll + 228
2  libdispatch.dylib              0x2781c _dispatch_event_loop_wait_for_ownership + 436
3  libdispatch.dylib              0x136f8 __DISPATCH_WAIT_FOR_QUEUE__ + 340
4  libdispatch.dylib              0x132c0 _dispatch_sync_f_slow + 148
5  JACO                           0x183e57c -[APMIdentity shouldSetLastAdvertisingIDResetUserProperty] + 605404
6  JACO                           0x18592bc -[APMMeasurement(Event) writeEvent:isPublicEvent:isRealtime:] + 715292
7  JACO                           0x1857368 __57-[APMMeasurement(Event) writeFilteredEventOnWorkerQueue:]_block_invoke + 707272
8  JACO                           0x18a139c -[APMSqliteStore performTransactionWithError:block:] + 1010428
9  JACO                           0x1820d2c -[APMDatabase performTransaction:] + 484492
10 JACO                           0x1857154 -[APMMeasurement(Event) writeFilteredEventOnWorkerQueue:] + 706740
11 JACO                           0x1856e68 -[APMMeasurement(Event) writeEventOnWorkerQueue:] + 705992
12 JACO                           0x1856904 -[APMMeasurement(Event) handleEventOnWorkerQueue:] + 704612
13 JACO                           0x184c724 -[APMMeasurement logEventOnWorkerQueue:notifyEventListeners:] + 663172
14 JACO                           0x184c69c -[APMMeasurement logEventOnWorkerQueueWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:] + 663036
15 JACO                           0x184c430 __151-[APMMeasurement logEventWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:]_block_invoke + 662416
16 JACO                           0x189857c __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 974044
17 libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
18 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
19 libdispatch.dylib              0xb534 _dispatch_lane_serial_drain + 668
20 libdispatch.dylib              0xc0a4 _dispatch_lane_invoke + 384
21 libdispatch.dylib              0x16cdc _dispatch_workloop_worker_thread + 648
22 libsystem_pthread.dylib        0xddc _pthread_wqthread + 288
23 libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

APMDefaultIdentitySupport
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  libdispatch.dylib              0x1f20c _dispatch_mach_send_and_wait_for_reply + 548
5  libdispatch.dylib              0x1f59c dispatch_mach_send_with_result_and_wait_for_reply + 60
6  libxpc.dylib                   0x10218 xpc_connection_send_message_with_reply_sync + 240
7  Foundation                     0xa2f18 __NSXPCCONNECTION_IS_WAITING_FOR_A_SYNCHRONOUS_REPLY__ + 16
8  Foundation                     0x362c4 -[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:] + 2192
9  CoreFoundation                 0x1fea8 ___forwarding___ + 1016
10 CoreFoundation                 0x86900 _CF_forwarding_prep_0 + 96
11 CoreServices                   0x8279c __56-[LSApplicationWorkspace deviceIdentifierForAdvertising]_block_invoke + 264
12 CoreServices                   0x477f8 _LSRetryForConnectionInterrupted + 56
13 CoreServices                   0x8262c -[LSApplicationWorkspace deviceIdentifierForAdvertising] + 160
14 AdSupport                      0x1950 -[ASIdentifierManager advertisingIdentifier] + 156
15 JACO                           0x18a7548 -[APMPlatformIdentitySupport resettableDeviceID] + 1035432
16 JACO                           0x182ce20 __47-[APMDefaultIdentitySupport resettableDeviceID]_block_invoke + 533888
17 libdispatch.dylib              0x12fc4 _dispatch_block_async_invoke2 + 148
18 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
19 libdispatch.dylib              0xb534 _dispatch_lane_serial_drain + 668
20 libdispatch.dylib              0xc0a4 _dispatch_lane_invoke + 384
21 libdispatch.dylib              0x16cdc _dispatch_workloop_worker_thread + 648
22 libsystem_pthread.dylib        0xddc _pthread_wqthread + 288
23 libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0xb74 start_wqthread + 254

JavaScriptCore libpas scavenger
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  JavaScriptCore                 0x113cc4 scavenger_thread_main + 1428
3  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
4  libsystem_pthread.dylib        0xb88 thread_start + 8

com.apple.CFNetwork.Connection
0  CoreFoundation                 0x2790 -[NSTaggedPointerString isEqual:] + 554
1  CoreFoundation                 0x1681c -[NSMutableDictionary __addObject:forKey:] + 76
2  Security                       0x532c der_decode_dictionary + 248
3  Security                       0x12c70 der_decode_plist + 1164
4  Security                       0x10b694 CFPropertyListCreateWithDERData + 96
5  Security                       0x100628 SecTrustDeserialize + 56
6  CFNetwork                      0xfa118 CFURLDownloadCancel + 58028
7  CFNetwork                      0xf9bac CFURLDownloadCancel + 56640
8  libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
9  libdispatch.dylib              0x3eac _dispatch_client_callout + 20
10 libdispatch.dylib              0xb534 _dispatch_lane_serial_drain + 668
11 libdispatch.dylib              0xc0d8 _dispatch_lane_invoke + 436
12 libdispatch.dylib              0xd394 _dispatch_workloop_invoke + 1764
13 libdispatch.dylib              0x16cdc _dispatch_workloop_worker_thread + 648
14 libsystem_pthread.dylib        0xddc _pthread_wqthread + 288
15 libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8
```

</p>
</details> 

### Expected Result

No Crash

### Actual Result

Crash

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by armcknight**
fixes #3336 

Let's just avoid calling through to NSLog from the profiler's sampling thread until we can get a different logging solution in place, if we decide we need these logs at some point in the future.

### CODE REVIEW

File: Sources/Sentry/include/SentryProfilingLogging.hpp [hunk 1]
```diff
@@ -19,12 +21,22 @@ namespace profiling {
...
+#    define SENTRY_PROF_LOG_DEBUG(...)                                                             \
+        sentry::profiling::log(sentry::profiling::LogLevel::Debug, __VA_ARGS__)
+#    define SENTRY_PROF_LOG_WARN(...)                                                              \
+        sentry::profiling::log(sentry::profiling::LogLevel::Warning, __VA_ARGS__)
+#    define SENTRY_PROF_LOG_ERROR(...)                                                             \
+        sentry::profiling::log(sentry::profiling::LogLevel::Error, __VA_ARGS__)
+
+#else
+
+// don't do anything with these in production until we can get a logging solution in place that
```
Comment (indragiek) [inline Sources/Sentry/include/SentryProfilingLogging.hpp:33]: add a brief explanation and a link to my comment on the issue (https://github.com/getsentry/sentry-cocoa/issues/3336#issuecomment-1802892052) so we have a reference for why using NSLog here is bad

**Review by indragiek — APPROVED** [review]

**Review by philipphofmann — APPROVED** [review]
LGTM.
