### PR TITLE
ref: Renames `SentrySpan` class to `SentrySpanInternal`

### LINKED ISSUE #7176: ref: Renames `SentrySpan` class to `SentrySpanInternal`
> [!NOTE]
> The pull request "[ref: Renames `SentrySpan` class to `SentrySpanInternal`](https://github.com/getsentry/sentry-cocoa/pull/7172)" was created by @itaybre but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

## :scroll: Description

Renames the class `SentrySpan` to `SentrySpanInternal`, keeping `SentrySpan` only to the protocol.
Only the protocol is a public API, so no breaking changes were made

## :bulb: Motivation and Context

We have 2 types with identical names, one a protocol and another a class.
While converting the SentryCrashIntegration to Swift, I ran into issues with them having the same name in ObjC.

## :pencil: Checklist

You have to check all boxes before merging:

- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### PR DESCRIPTION
**Pull request by itaybre**
## :scroll: Description

Renames the class `SentrySpan` to `SentrySpanInternal`, keeping `SentrySpan` only to the protocol.
Only the protocol is a public API, so no breaking changes were made

## :bulb: Motivation and Context

We have 2 types with identical names, one a protocol and another a class.
While converting the SentryCrashIntegration to Swift, I ran into issues with them having the same name in ObjC.

## :pencil: Checklist

You have to check all boxes before merging:

- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

Closes #7176

### CODE REVIEW

**Comment by itaybre** [comment]
@sentry review

**Comment by itaybre** [comment]
> LGTM, but might we worth to ask one of our coding agents to verify we caught all use cases of `SentrySpan` which need to be renamed

Should be fine since if I missed any case, it shouldn't compile
But I triggered the review anyway

File: Sources/Sentry/include/SentrySpanInternal.h [hunk 1]
```diff
@@ -15,7 +15,7 @@ NS_ASSUME_NONNULL_BEGIN
 @class SentryFramesTracker;
 #endif // SENTRY_HAS_UIKIT
 
-@interface SentrySpan : NSObject <SentrySpan, SentrySerializable>
+@interface SentrySpanInternal : NSObject <SentrySpan, SentrySerializable>
```
Comment (philippsuess) [inline Sources/Sentry/include/SentrySpanInternal.h:20]: `m`: Maybe it's worth renaming the file as well.

Comment (philippsuess) [inline Sources/Sentry/include/SentrySpanInternal.h:20]: `m`: Maybe worth adding a comment explaining that this was called `SentrySpan` before, and there's not a good reason for that, and why we renamed it.

File: Sources/Sentry/SentryCoreDataTracker.m [hunk 2]
```diff
@@ -37,8 +37,8 @@ - (NSArray *)managedObjectContext:(NSManagedObjectContext *)context
                             error:(NSError **)error
                       originalImp:(NSArray *(NS_NOESCAPE ^)(NSFetchRequest *, NSError **))original
 {
-    id<SentrySpan> _Nullable currentSpan = [SentrySDKInternal.currentHub.scope span];
-    id<SentrySpan> _Nullable fetchSpan;
+    SentrySpanInternal *_Nullable currentSpan = [SentrySDKInternal.currentHub.scope span];
+    SentrySpanInternal *_Nullable fetchSpan;
```
Comment (philippsuess) [inline Sources/Sentry/SentryCoreDataTracker.m]: `m`: I don't think we should have to change this here. We should still be able to use the protocol and not the class. What drove you to change this?

File: Sources/Sentry/Public/SentryScope.h [hunk 3]
```diff
@@ -13,6 +13,7 @@
 @class SentryBreadcrumb;
 @class SentryOptions;
 @class SentryUser;
+@class SentrySpanInternal;
```
Comment (philippsuess) [inline Sources/Sentry/Public/SentryScope.h]: `h`: SentryScope is public. That shouldn't have to be here.
```suggestion
```

File: Sources/Sentry/SentryScope.m [hunk 4]
```diff
@@ -147,23 +147,23 @@ - (void)setPropagationContext:(SentryPropagationContext *)propagationContext
     }
 }
 
-- (nullable id<SentrySpan>)span
+- (nullable SentrySpanInternal *)span
```
Comment (philippsuess) [inline Sources/Sentry/SentryScope.m]: `m`: That shouldn't have to change. This should stay the same. What drove you to change this?

**Review by philipphofmann — COMMENTED** [review]
There are several replacements of `id<SentrySpan>` with `SentrySpanInternal`. I don't think these should be required.

File: Tests/SentryTests/SentryScopeSwiftTests.swift [hunk 5]
```diff
@@ -1057,5 +1057,5 @@ private final class NotOfTypeSpan: NSObject, Span {
     func serialize() -> [String: Any] { return [:] }
 }
 
-private final class SubClassOfSentrySpan: SentrySpan {}
+private final class SubClassOfSentrySpan: SentrySpanInternal {}
```
Comment (philippsuess) [inline Tests/SentryTests/SentryScopeSwiftTests.swift]: `l`: 
```suggestion
private final class SubClassOfSentrySpanInternal: SentrySpanInternal {}
```

File: Sources/Sentry/Public/SentryScope.h (hunk 3 above)
Comment (itaybre) [reply Sources/Sentry/Public/SentryScope.h]: Good catch, it should be the protocol in here then

File: Sources/Sentry/SentryScope.m (hunk 4 above)
Comment (itaybre) [reply Sources/Sentry/SentryScope.m]: Probably CrashIntegration, but doesn't seems needed here.
Will undo this change

File: Sources/Sentry/SentryCoreDataTracker.m (hunk 2 above)
Comment (itaybre) [reply Sources/Sentry/SentryCoreDataTracker.m]: `SentrySpanInternal` has an extra function `setFrames` which is used below.
SentrySpan and SentrySpanInternal are almost interchangeable, the internal class just has some additional functions

**Comment by itaybre** [comment]
> There are several replacements of `id<SentrySpan>` with `SentrySpanInternal`. I don't think these should be required.

There is no reason to use `id<SentrySpan>` instead of `SentrySpanInternal` internally, the protocol is just the public interface

File: Sources/Sentry/include/SentrySpanInternal.h [hunk 6]
```diff
@@ -15,7 +15,9 @@ NS_ASSUME_NONNULL_BEGIN
 @class SentryFramesTracker;
 #endif // SENTRY_HAS_UIKIT
 
-@interface SentrySpan : NSObject <SentrySpan, SentrySerializable>
+// This class used to be named SentrySpan, but it was renamed to SentrySpanInternal to avoid
+// confusion with the public SentrySpan protocol.
```
Comment (philippsuess) [inline Sources/Sentry/include/SentrySpanInternal.h:19]: Thank you 🥇
