### PR TITLE
fix: Encode SwiftUI internal class names in session replay redaction to prevent App Store rejections

### LINKED ISSUE #7126: fix: Encode SwiftUI internal class names in session replay redaction to prevent App Store rejections
> [!NOTE]
> The pull request "[fix: Encode SwiftUI internal class names in session replay redaction to prevent App Store rejections](https://github.com/getsentry/sentry-cocoa/pull/7123)" was created by @itaybre but did not reference an issue. Therefore this issue was created for better visibility in external tools like Linear.

## :scroll: Description

Base64 encode a couple of Apple private classes to avoid triggering Apple's string verification

## :bulb: Motivation and Context

Fixes: https://github.com/getsentry/sentry-cocoa/issues/7121

Apple seems to run some static checks when testing apps which detect some SwiftUI classes we try to avoid.
Encoding it, should fix the problem

## :pencil: Checklist

You have to check all boxes before merging:

- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### PR DESCRIPTION
**Pull request by itaybre**
## :scroll: Description

Base64 encode a couple of Apple private classes to avoid triggering Apple's string verification

## :bulb: Motivation and Context

Fixes: https://github.com/getsentry/sentry-cocoa/issues/7121

Apple seems to run some static checks when testing apps which detect some SwiftUI classes we try to avoid.
Encoding it, should fix the problem

## :pencil: Checklist

You have to check all boxes before merging:

- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

Closes #7126

### CODE REVIEW

File: Sources/Swift/Core/Tools/ViewCapture/SentryUIRedactBuilder.swift [hunk 1]
```diff
@@ -142,15 +142,25 @@ final class SentryUIRedactBuilder {
             redactClasses.insert(ClassIdentifier(classId: "SwiftUI.CGDrawingView"))
 
             // Used to render SwiftUI.Text on iOS versions prior to iOS 18
-            redactClasses.insert(ClassIdentifier(classId: "_TtCOCV7SwiftUI11DisplayList11ViewUpdater8Platform13CGDrawingView"))
+            // This is the base64 representation of `_TtCOCV7SwiftUI11DisplayList11ViewUpdater8Platform13CGDrawingView`
+            // Encoded to avoid triggering apple's rejections, see https://github.com/getsentry/sentry-cocoa/issues/7121
```
Comment (philprime) [inline Sources/Swift/Core/Tools/ViewCapture/SentryUIRedactBuilder.swift]:
```suggestion
            // Encoded to avoid triggering Apple's false-positive app review rejections, see https://github.com/getsentry/sentry-cocoa/issues/7121
```

File: Sources/Swift/Core/Tools/ViewCapture/SentryUIRedactBuilder.swift [hunk 2]
```diff
@@ -142,15 +142,25 @@ final class SentryUIRedactBuilder {
...
 
         }
         
         if options.maskAllImages {
             redactClasses.insert(ClassIdentifier(objcType: UIImageView.self))
 
             // Used by SwiftUI.Image to display SFSymbols, e.g. `Image(systemName: "star.fill")`
-            redactClasses.insert(ClassIdentifier(classId: "_TtC7SwiftUIP33_A34643117F00277B93DEBAB70EC0697122_UIShapeHitTestingView"))
+            // This is the base64 representation of `_TtC7SwiftUIP33_A34643117F00277B93DEBAB70EC0697122_UIShapeHitTestingView`
+            // Encoded to avoid triggering apple's rejections, see https://github.com/getsentry/sentry-cocoa/issues/7121
```
Comment (philprime) [inline Sources/Swift/Core/Tools/ViewCapture/SentryUIRedactBuilder.swift]:
```suggestion
            // Encoded to avoid triggering Apple's false-positive app review rejections, see https://github.com/getsentry/sentry-cocoa/issues/7121
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,5 +1,11 @@
 # Changelog
 
+## Unreleased
+
+### Fixes
+
+- Encode SwiftUI internal class names in session replay redaction to avoid App Store rejections (#7123)
```
Comment (philprime) [inline CHANGELOG.md]:
```suggestion
- Encode SwiftUI internal class names in session replay redaction to avoid false-positive App Store review rejections (#7123)
```

**Review by philprime — APPROVED** [review]
LGTM but we need to ensure our wording states that we are not trying to circumvent the review, just handling false-positives
