### PR TITLE
fix: Crashed session not being reported as crashed

### LINKED ISSUE #3181: crash sessions no report
### Platform

iOS

### Installed

Manually

### Version

Sentry 23.7.0.dev0 f52e733

### Steps to Reproduce

1. use the demo ios-objectiveC
2. click the button crash , wait the crash, and reopen demo (retry couple times)
3. check the release or project
4. the crash free sessions always 100%

i read the source code, 
image
the Integrations order will effect.

### Expected Result

have the right crash free sessions

### Actual Result

the crash free sessions always 100%

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by brustolin**
## :scroll: Description

We [recently](https://github.com/getsentry/sentry-cocoa/pull/3157/files#diff-a29fc90c9efdf9bef7ce45c2687a50708114e90208d518b9fe3bad5ef8e0951b) changed the integration order, which is causing a problem to report crashed sessions.

This PR fix the order of integration.

## :bulb: Motivation and Context

close #3181 

## :green_heart: How did you test it?

Sample

## :pencil: Checklist

You have to check all boxes before merging:

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

## :crystal_ball: Next steps

Investigate a way to update the integrations so they don't require a specific order.

### CODE REVIEW

File: Sources/Sentry/SentryOptions.m [hunk 1]
```diff
@@ -56,6 +56,7 @@ - (void)setMeasurement:(SentryMeasurementValue *)measurement
 {
     NSMutableArray<NSString *> *defaultIntegrations =
```
Comment (kahest) [inline Sources/Sentry/SentryOptions.m:57]: `H`: add a note that the order of integrations is important and must not be changed

**Review by armcknight — APPROVED** [review]

File: Sources/Sentry/SentryOptions.m [hunk 2]
```diff
@@ -54,8 +54,11 @@ - (void)setMeasurement:(SentryMeasurementValue *)measurement
 
 + (NSArray<NSString *> *)defaultIntegrations
 {
+    // The order of integrations here is important.
```
Comment (philipphofmann) [inline Sources/Sentry/SentryOptions.m:57]: Thanks for the vital comment 🥇
